### PR TITLE
NMS-8856: Resource graph forecast page lacks header

### PR DESCRIPTION
**Pull request by agalue**
Resource graph forecast page lacks header

* JIRA: http://issues.opennms.org/browse/NMS-8856

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by j-white** [comment]
These were intentionally omitted because the original implementation opened as a pop-up window, similar to the NRTG button. Personally, I'd prefer to see this open as a pop-up rather than adding those headers.

Also, the current breadcrumbs on this page only show the link to 'Home', there is nothing to return the user back to the 'Resource Graphs' or the 'Results' page.

**Comment by agalue** [comment]
That makes sense, and would explain why the headers were omitted, but it is surprising to find that it was implemented this way instead of launching a pop-up window (which is not hard to do, and I agree it is better). This is just another example of the consequences of not having things well documented. So, should I close this one, and create another that actually opens a new pop-up window (even knowing that some browsers block this ability by default) ?

**Comment by agalue** [comment]
@j-white I have another solution (tested on my environment), based on the current NRTG implementation that will open a popUp for the Forecast page (similar to NRTG) which will use the `graph/forecast.jsp` unchanged, but will require a small change on `WEB-INF/jsp/graph/results.jsp`. Let me know if that's more aligned for what you think we should have as a solution so I can go ahead and close this PR and create another one (or re-use the branch by reverting the change if that's easier).

**Comment by j-white** [comment]
Yeah, I'd go with the pop-up instead.

**Comment by agalue** [comment]
> Yeah, I'd go with the pop-up instead.

Done!

**Pull request merged**
