### PR TITLE
NMS-12811: change UEI so it does not block alarms from trap with same UEI

### PR DESCRIPTION
**Pull request by dschlenk**
### All Contributors

* [X] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [X] Have you made a comment in that issue which points back to this PR?
* [X] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12811

### CODE REVIEW

**Comment by dschlenk** [comment]
LMK if I should rebase to something else since it most certainly is changing a file in `$ONMS_HOME/etc/` as that's where the problem is.

**Comment by j-white** [comment]
We normally avoid changing files in `$ONMS_HOME/etc/` in the `foundation-*` branches.

It seems like the right thing to do here would be to fix NMS-12755 rather than working around it by changing the config.

**Comment by dschlenk** [comment]
@j-white sure, I was led to believe it was unlikely to get fixed so I figured the config should change in that case

**Comment by RangerRick** [comment]
Agree we should avoid messing with existing configs, but at the very least we can retarget this to foundation-2020 and up for new releases as a breaking change.

**Comment by dschlenk** [comment]
@j-white I'd love to fix the underlying issue. Any ideas on where to start looking? It changed between 18 and 19. I think trapd was reworked a bit for 19?

**Comment by j-white** [comment]
Closing this since NMS-12755 was fixed.

**Pull request closed without merging**
