### PR TITLE
NMS-10260: Streamline contribution docs in GitHub repository

### PR DESCRIPTION
**Pull request by indigo423**
* JIRA: http://issues.opennms.org/browse/NMS-10260

### CODE REVIEW

**Comment by indigo423** [comment]
Never thought I can break a test with this PR :)

**Comment by j-white** [comment]
You've hit a flapper :)

**Comment by indigo423** [comment]
Seems like `Failed to run make-installer.sh: No such file or directory` flapped again.

**Comment by RangerRick** [comment]
Passed this time, gonna merge it.

**Pull request merged**
