### PR TITLE
NMS-8601: Changed links in requisition UI to buttons and made them right-aligned

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-8601

### CODE REVIEW

**Comment by agalue** [comment]
Looks reasonable to me. I don't remember if there are smoke tests checking those things, but if Bamboo passes, I think this is good to be merged.

**Comment by mvrueden** [comment]
I tried out this branch, looks good in general, but the font of the icon label is weird. See jira issue for more details.

**Comment by mvrueden** [comment]
The buttons look good now. The only thing which still bothers me is the "tooltip" in the "more actions" popup as it exactly says the same as each item is telling me. It should be removed from my point of view.

**Comment by mvrueden** [comment]
Looks good now 👍

**Pull request merged**
