### PR TITLE
NMS-11021: Document DskTableMonitor

### PR DESCRIPTION
**Pull request by mfuhrmann**
### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://opennms.atlassian.net/) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the Jira link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the Jira issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-11021

### CODE REVIEW

**Review by Bonrob2 — APPROVED** [review]
LGTM. Thanks.
Had some unusual issues with local building, but the file on GitHub looks fine. Also interesting, that we use different template for monitors and detectors on where we put the common parameters text. This is consistent with the rest of the monitor chapters.

**Comment by Bonrob2** [comment]
> @Bonrob2 We don't have a detector for this.

No problem. Do we need to add something that there is no corresponding detector? I don't think we do that with any of the existing monitors that don't have detectors.

**Comment by Bonrob2** [comment]
> @Bonrob2 I think this does not make sense. Detecting failed or non-failed disk? I think also the SNMP monitor/detectors can do this job. You would have to handle those [static OIDs ](https://github.com/OpenNMS/opennms/blob/da6badc4b51442f2461310ce9f1249db4aea4bd5/features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/DskTableMonitor.java#L62-L63) in the monitor/detector configuration.
> 
> Right now I don't see the added value for this monitor.

We could document that this monitor has been superseded by SNMP/Monitor detectors, and then create a ticket for the development team to deprecate this monitor. Or we can just not document it and create a ticket for the development team to deprecate it. 

I think if most of these monitors aren't used, then we should just close the tickets. We can create placeholder pages in the docs that invite people to contribute and that way we can determine whether anyone actually needs docs for them. 
I haven't had time to do that work yet.

**Comment by mfuhrmann** [comment]
@Bonrob2 and I clarified the misunderstanding in a chat. We will merge this PR like it is.

**Pull request merged**
