### PR TITLE
Update Full Stack Diagram

### PR DESCRIPTION
**Pull request by marshallmassengill**
Updating the diagram to refer to a generic Time Series storage instead of Cassandra.

### CODE REVIEW

**Comment by marshallmassengill** [comment]
@indigo423 - from talking to you the other day, I think this should carry through on the Horizon and Meridian docs but let me know if I should target a different branch.

**Comment by indigo423** [comment]
> @indigo423 - from talking to you the other day, I think this should carry through on the Horizon and Meridian docs but let me know if I should target a different branch.

Do we have a source file someone can edit? If we add just the PNG, there wouldn't be anyone who can make adjustments to that image?

**Comment by marshallmassengill** [comment]
I can add it somewhere.  Do we have a place to do that?  I don't think it should go in this directory but I could be wrong.

**Comment by indigo423** [comment]
> I can add it somewhere. Do we have a place to do that? I don't think it should go in this directory but I could be wrong.

Next to the PNG with the same name, that way someone has a chance to modify it.

**Review by indigo423 — DISMISSED** [review]
That is helpful.

**Comment by marshallmassengill** [comment]
Can we get this merged?

**Comment by marshallmassengill** [comment]
It looks like it picked up my pre-auth doc changes now.  I thought this has been merged already so ended up updating that branch on my repo to add that one too.

**Comment by dino2gnt** [comment]
lgtm...

**Review by dino2gnt — APPROVED** [review]

**Review by indigo423 — APPROVED** [review]
I think what you probably want is to update this image for Meridian 2021 onwards up to the next Horizon. You would need to make the PR against the foundation-2021 branch to make that automatically happen.

* https://docs.opennms.com/meridian/2021/index.html because that is the oldest version we commercially support.

Otherwise LGTM for me.

**Comment by marshallmassengill** [comment]
Bleh... should have known I couldn't just swap the base.  I'm not that worried about this going back to 2021 at the moment, this should be ok.

**Review by dino2gnt — APPROVED** [review]
:+1:

**Pull request merged**
