### PR TITLE
NMS-10684: Close the JMXConnector if an exception occurs when connecting

### PR DESCRIPTION
**Pull request by j-white**
JIRA: https://issues.opennms.org/browse/NMS-10684

### CODE REVIEW

**Comment by mvrueden** [comment]
This PR is targeted for `foundation-2017`, however the issue defines a fixed version of `meridian.2016.*`. Please re-target or adjust fix version accordingly.

Besides this, LGTM.

**Comment by smith-opennms** [comment]
I will re-target this to ```foundation-2016```

**Comment by smith-opennms** [comment]
Cancel that. Porting back to ```Foundation-2016``` is a mess.
Recommend we update the JIRA fix version and back port if there's an absolute need.

**Comment by mvrueden** [comment]
Okay, I updated the jira issue. Can you please enlighten us, why it is a mess? Just for transparency reasons.

**Comment by smith-opennms** [comment]
Jesse's changes were based on JmxConfig changes you made back in foundation-2017.
I tried bringing the jmxConfig changes back to foundation-2016 too, but they were based on a variety of other changes made in foundation-2017. The number of dependent changes kept growing and IMO exceeded the merits of bringing this fix back to that branch.

**Comment by mvrueden** [comment]
Yeah makes sense. Thanks for sharing.

**Pull request merged**
