### PR TITLE
NMS-12910: Add perspectivepollerd logging entry

### PR DESCRIPTION
**Pull request by indigo423**
### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [x] If this is a new or updated feature, is there documentation for the new behavior?
* [x] If this is new code, are there unit and/or integration tests?
* [x] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

Allow configuring the log level for the Perspective Poller daemon.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12910

### CODE REVIEW

**Review by christianpape — APPROVED** [review]
```
  ________                      __   
 /  _____/______   ____ _____ _/  |_ 
/   \  __\_  __ \_/ __ \\__  \\   __\
\    \_\  \  | \/\  ___/ / __ \|  |  
 \______  /__|    \___  >____  /__|  
        \/            \/     \/      
```

**Comment by indigo423** [comment]
> ```
>   ________                      __   
>  /  _____/______   ____ _____ _/  |_ 
> /   \  __\_  __ \_/ __ \\__  \\   __\
> \    \_\  \  | \/\  ___/ / __ \|  |  
>  \______  /__|    \___  >____  /__|  
>         \/            \/     \/      
> ```

 _____ _                 _        _ 
|_   _| |               | |      | |
  | | | |__   __ _ _ __ | | _____| |
  | | | '_ \ / _` | '_ \| |/ / __| |
  | | | | | | (_| | | | |   <\__ \_|
  \_/ |_| |_|\__,_|_| |_|_|\_\___(_)

**Review by RangerRick — APPROVED** [review]
This changeset is too complicated to merge, please add unit tests.

(just kidding, LGTM)

**Comment by indigo423** [comment]
> This changeset is too complicated to merge, please add unit tests.
> 
> (just kidding, LGTM)

Just the fun parts :D

**Pull request merged**
