### PR TITLE
NMS-9724: add validation of the event before attempting to send it

### PR DESCRIPTION
**Pull request by RangerRick**
This PR adds some basic validation of the event object(s) when `POST`ed to the event rest service.

* JIRA: http://issues.opennms.org/browse/NMS-9724

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by j-white** [comment]
Shouldn't we be using the XSD to perform these validations instead of writing extra code for null and count checks?

**Comment by RangerRick** [comment]
All that work was done in {{foundation-2017}} and backporting it is way beyond the scope of fixing a few high-value targets IMHO.

**Comment by j-white** [comment]
I agree it's not worth back-porting. This approach of adding boilerplate validation code feels wrong to me though - it's error prone, requires an explicit call to validate, and difficult to maintain.

**Comment by RangerRick** [comment]
I believe the reason the event objects were not marked with `@ValidateUsing` was for throughput/performance reasons, but I honestly don't know how much of an impact JAXB validation is on that, maybe it's worth just turning it back on.

**Comment by RangerRick** [comment]
I've updated it to use JPA validation tags instead and call a validator on POST.

**Comment by j-white** [comment]
The updates to use the validation API look good.

Since that seems to address the underlying issue, we may want to skip enabling the ValidateUsing tags unless we understand the impacts. Particularly because this targets the `foundation-2016` branch.

**Comment by RangerRick** [comment]
Makes sense, I'll update the branch.

**Pull request merged**
