### PR TITLE
NMS-14988: Set additional entity expansion options

### PR DESCRIPTION
**Pull request by amay94**
See the [OWASP cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#spring-framework-mvcoxm-xxe-vulnerabilities) on XEE prevention.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

### CODE REVIEW

**Review by aramosvizcarra — COMMENTED** [review]
LGTM, not sure if the test failing has anything todo with the rrd change.

**Comment by amay94** [comment]
> LGTM, not sure if the test failing has anything todo with the rrd change.

The test was failing because we have tests that use config files with DOCTYPE declarations. It looks like RRD dumps contain those by default, so I updated the fix to only apply to XML received from rest endpoints

**Comment by RangerRick** [comment]
Pretty sure the failures are real since RRD XML dumps have `DOCTYPE` set (created by `rrdtool dump`). Jasper Reports also have `DOCTYPE` defined, although Jasper _probably_ already does its own parsing.

`git grep DOCTYPE | grep src/test` should show you where potential pitfalls are.

**Review by RangerRick — APPROVED** [review]

**Review by christianpape — APPROVED** [review]
LGTM.

**Pull request merged**
