### PR TITLE
HZN-1143: Use DTOs for the event and alarm endpoints.

### PR DESCRIPTION
**Pull request by j-white**
JIRA: https://issues.opennms.org/browse/HZN-1143

Here we update the alarm and event REST endpoints in the v2 API to use DTOs.

The DTOs are built from the corresponding entities using mappers, built with the help of MapStruct.

The DTOs are maintained in a separate project, with minimal dependencies on other artifacts so that these can be easily imported by other projects.

### CODE REVIEW

**Comment by RangerRick** [comment]
Are you purposefully excluding some properties that exist on the v1 objects?

```diff
# event v1 vs. v2
--- /tmp/v1.json        2017-08-28 11:27:41.000000000 -0400
+++ /tmp/v2.json        2017-08-28 11:27:51.000000000 -0400
@@ -4,8 +4,9 @@
     "display": "Y",
     "host": "With-Teeth.local",
     "id": 379,
-    "ifIndex": null,
     "ipAddress": "192.168.211.16",
+    "label": "OpenNMS-defined node event: nodeRegainedService",
+    "location": "Default",
     "log": "Y",
     "logMessage": "\n      The SSH outage on interface 192.168.211.16 has been\n      cleared. Service is restored.\n    ",
     "nodeId": 2,
```

```diff
# alarm v1 vs. v2
--- /tmp/v1.json        2017-08-28 11:25:32.000000000 -0400
+++ /tmp/v2.json        2017-08-28 11:25:22.000000000 -0400
@@ -1,5 +1,4 @@
 {
-    "ackId": 88,
     "clearKey": "uei.opennms.org/nodes/nodeLostService::2:192.168.211.16:SSH",
     "count": 1,
     "description": "<p>The SSH service on interface 192.168.211.16 was\n      previously down and has been restored.</p>\n      <p>This event is generated when a service which had\n      previously failed polling attempts is again responding to\n      polls by OpenNMS. </p> <p>This event will cause\n      any active outages associated with this service/interface\n      combination to be cleared.</p>",
@@ -13,8 +12,9 @@
         "display": "Y",
         "host": "With-Teeth.local",
         "id": 379,
-        "ifIndex": null,
         "ipAddress": "192.168.211.16",
+        "label": "OpenNMS-defined node event: nodeRegainedService",
+        "location": "Default",
         "log": "Y",
         "logMessage": "\n      The SSH outage on interface 192.168.211.16 has been\n      cleared. Service is restored.\n    ",
         "nodeId": 2,
@@ -29,13 +29,10 @@
         "uei": "uei.opennms.org/nodes/nodeRegainedService"
     },
     "lastEventTime": 1503933714585,
+    "location": "Default",
     "logMessage": "\n      The SSH outage on interface 192.168.211.16 has been\n      cleared. Service is restored.\n    ",
-    "managedObjectInstance": null,
-    "managedObjectType": null,
     "nodeId": 2,
     "nodeLabel": "Synology",
-    "ossPrimaryKey": null,
-    "qosAlarmState": null,
     "reductionKey": "uei.opennms.org/nodes/nodeRegainedService::2:192.168.211.16:SSH",
     "serviceType": {
         "id": 3,
@@ -46,6 +43,5 @@
     "suppressedUntil": 1503933714585,
     "type": 2,
     "uei": "uei.opennms.org/nodes/nodeRegainedService",
-    "x733AlarmType": null,
     "x733ProbableCause": 0
 }
```

**Comment by RangerRick** [comment]
Oh, I see, it just excludes values that are null.

**Comment by RangerRick** [comment]
On closer look it appears it's not just null values... `ackId` is missing from the v2 alarm.  Also for a list response (like `/alarms`) offset is `null` when it's un-set but it should always be an integer (`0`) or parsing on the JS side will get weird.

**Comment by j-white** [comment]
I purposely ignored `ackId`, since it was marked with the `@Transient` and only returns the actual `alarmId`. If there's a good reason to keep it, we can add it though.

**Comment by RangerRick** [comment]
The list wrapper returns a `0` in v1, and a `null` in v2... Or do you mean that's a v2 bug not specific to DTO changes?

```diff
--- /tmp/v1.json	2017-08-28 11:32:15.000000000 -0400
+++ /tmp/v2.json	2017-08-28 11:32:06.000000000 -0400
@@ -1,7 +1,6 @@
 {
     "alarm": [
         {
-            "ackId": 89,
             "clearKey": "uei.opennms.org/nodes/nodeDown::6",
             "count": 1,
             "description": "<p>Node Downward-Spiral.local which was previously down is\n      now up.</p> <p>This event is generated when node\n      outage processing determines that all interfaces on the node\n      are up.</p> <p>This event will cause any active\n      outages associated with this node to be cleared.</p>",
@@ -14,7 +13,8 @@
                 "display": "Y",
                 "host": "With-Teeth.local",
                 "id": 381,
-                "ifIndex": null,
+                "label": "OpenNMS-defined node event: nodeUp",
+                "location": "Default",
                 "log": "Y",
                 "logMessage": "\n      Node Downward-Spiral.local is up.\n    ",
                 "nodeId": 6,
@@ -26,19 +26,16 @@
                         "value": "Downward-Spiral.local"
                     }
                 ],
-                "serviceType": null,
                 "severity": "NORMAL",
                 "source": "OpenNMS.Poller.DefaultPollContext",
                 "time": 1503934102585,
                 "uei": "uei.opennms.org/nodes/nodeUp"
             },
             "lastEventTime": 1503934102585,
+            "location": "Default",
             "logMessage": "\n      Node Downward-Spiral.local is up.\n    ",
-            "managedObjectInstance": null,
-            "managedObjectType": null,
             "nodeId": 6,
             "nodeLabel": "Downward-Spiral.local",
-            "ossPrimaryKey": null,
             "parameters": [
                 {
                     "name": "nodelabel",
@@ -46,19 +43,15 @@
                     "value": "Downward-Spiral.local"
                 }
             ],
-            "qosAlarmState": null,
             "reductionKey": "uei.opennms.org/nodes/nodeUp::6",
-            "serviceType": null,
             "severity": "NORMAL",
             "suppressedTime": 1503934102585,
             "suppressedUntil": 1503934102585,
             "type": 2,
             "uei": "uei.opennms.org/nodes/nodeUp",
-            "x733AlarmType": null,
             "x733ProbableCause": 0
         },
         {
-            "ackId": 85,
             "count": 2,
             "description": "<p>All interfaces on node Downward-Spiral.local are\n      down.</p> <p>This event is generated when node\n      outage processing determines that all interfaces on the node\n      are down.</p> <p>New outage records have been\n      created and service level availability calculations will be\n      impacted until this outage is resolved.</p>",
             "firstAutomationTime": 1503933610725,
@@ -72,7 +65,8 @@
                 "display": "Y",
                 "host": "With-Teeth.local",
                 "id": 380,
-                "ifIndex": null,
+                "label": "OpenNMS-defined node event: nodeDown",
+                "location": "Default",
                 "log": "Y",
                 "logMessage": "\n      Node Downward-Spiral.local is down. \n    ",
                 "nodeId": 6,
@@ -84,19 +78,16 @@
                         "value": "Downward-Spiral.local"
                     }
                 ],
-                "serviceType": null,
                 "severity": "MAJOR",
                 "source": "OpenNMS.Poller.DefaultPollContext",
                 "time": 1503933915007,
                 "uei": "uei.opennms.org/nodes/nodeDown"
             },
             "lastEventTime": 1503933915007,
+            "location": "Default",
             "logMessage": "\n      Node Downward-Spiral.local is down. \n    ",
-            "managedObjectInstance": null,
-            "managedObjectType": null,
             "nodeId": 6,
             "nodeLabel": "Downward-Spiral.local",
-            "ossPrimaryKey": null,
             "parameters": [
                 {
                     "name": "nodelabel",
@@ -104,19 +95,15 @@
                     "value": "Downward-Spiral.local"
                 }
             ],
-            "qosAlarmState": null,
             "reductionKey": "uei.opennms.org/nodes/nodeDown::6",
-            "serviceType": null,
             "severity": "CLEARED",
             "suppressedTime": 1503933418809,
             "suppressedUntil": 1503933418809,
             "type": 1,
             "uei": "uei.opennms.org/nodes/nodeDown",
-            "x733AlarmType": null,
             "x733ProbableCause": 0
         },
         {
-            "ackId": 81,
             "count": 1,
             "description": "A provisioning adapter failed for host: .<p>\n      <p>Message: Dynamic Reverse DNS provisioning failed: <none>:1: unexpected tokens at end of record </p>",
             "firstEventTime": 1503932518698,
@@ -127,7 +114,8 @@
                 "description": "A provisioning adapter failed for host: .<p>\n      <p>Message: Dynamic Reverse DNS provisioning failed: <none>:1: unexpected tokens at end of record </p>",
                 "display": "Y",
                 "id": 370,
-                "ifIndex": null,
+                "label": "OpenNMS-defined Provisioning Adapter Failed message",
+                "location": "Default",
                 "log": "Y",
                 "logMessage": "\n      <p> ::Dynamic Reverse DNS provisioning failed: <none>:1: unexpected tokens at end of record </p>\n    ",
                 "nodeId": 3,
@@ -139,19 +127,16 @@
                         "value": "Dynamic Reverse DNS provisioning failed: <none>:1: unexpected tokens at end of record"
                     }
                 ],
-                "serviceType": null,
                 "severity": "MAJOR",
                 "source": "Provisioner",
                 "time": 1503932518698,
                 "uei": "uei.opennms.org/provisioner/provisioningAdapterFailed"
             },
             "lastEventTime": 1503932518698,
+            "location": "Default",
             "logMessage": "\n      <p> ::Dynamic Reverse DNS provisioning failed: <none>:1: unexpected tokens at end of record </p>\n    ",
-            "managedObjectInstance": null,
-            "managedObjectType": null,
             "nodeId": 3,
             "nodeLabel": "Ubiquiti EdgeRouter PoE",
-            "ossPrimaryKey": null,
             "parameters": [
                 {
                     "name": "reason",
@@ -159,19 +144,15 @@
                     "value": "Dynamic Reverse DNS provisioning failed: <none>:1: unexpected tokens at end of record"
                 }
             ],
-            "qosAlarmState": null,
             "reductionKey": "uei.opennms.org/provisioner/provisioningAdapterFailed::Dynamic Reverse DNS provisioning failed: <none>:1: unexpected tokens at end of record",
-            "serviceType": null,
             "severity": "MAJOR",
             "suppressedTime": 1503932518698,
             "suppressedUntil": 1503932518698,
             "type": 3,
             "uei": "uei.opennms.org/provisioner/provisioningAdapterFailed",
-            "x733AlarmType": null,
             "x733ProbableCause": 0
         },
         {
-            "ackId": 79,
             "count": 2,
             "description": "A provisioning adapter failed for host: .<p>\n      <p>Message: Dynamic DNS provisioning failed: org.xbill.DNS.TextParseException: '': empty name </p>",
             "firstEventTime": 1503932500068,
@@ -182,7 +163,8 @@
                 "description": "A provisioning adapter failed for host: .<p>\n      <p>Message: Dynamic DNS provisioning failed: org.xbill.DNS.TextParseException: '': empty name </p>",
                 "display": "Y",
                 "id": 369,
-                "ifIndex": null,
+                "label": "OpenNMS-defined Provisioning Adapter Failed message",
+                "location": "Default",
                 "log": "Y",
                 "logMessage": "\n      <p> ::Dynamic DNS provisioning failed: org.xbill.DNS.TextParseException: '': empty name </p>\n    ",
                 "nodeId": 3,
@@ -194,19 +176,16 @@
                         "value": "Dynamic DNS provisioning failed: org.xbill.DNS.TextParseException: '': empty name"
                     }
                 ],
-                "serviceType": null,
                 "severity": "MAJOR",
                 "source": "Provisioner",
                 "time": 1503932518685,
                 "uei": "uei.opennms.org/provisioner/provisioningAdapterFailed"
             },
             "lastEventTime": 1503932518685,
+            "location": "Default",
             "logMessage": "\n      <p> ::Dynamic DNS provisioning failed: org.xbill.DNS.TextParseException: '': empty name </p>\n    ",
-            "managedObjectInstance": null,
-            "managedObjectType": null,
             "nodeId": 2,
             "nodeLabel": "Synology",
-            "ossPrimaryKey": null,
             "parameters": [
                 {
                     "name": "reason",
@@ -214,19 +193,15 @@
                     "value": "Dynamic DNS provisioning failed: org.xbill.DNS.TextParseException: '': empty name"
                 }
             ],
-            "qosAlarmState": null,
             "reductionKey": "uei.opennms.org/provisioner/provisioningAdapterFailed::Dynamic DNS provisioning failed: org.xbill.DNS.TextParseException: '': empty name",
-            "serviceType": null,
             "severity": "MAJOR",
             "suppressedTime": 1503932500068,
             "suppressedUntil": 1503932500068,
             "type": 3,
             "uei": "uei.opennms.org/provisioner/provisioningAdapterFailed",
-            "x733AlarmType": null,
             "x733ProbableCause": 0
         },
         {
-            "ackId": 80,
             "count": 1,
             "description": "A provisioning adapter failed for host: .<p>\n      <p>Message: Dynamic Reverse DNS provisioning failed: null </p>",
             "firstEventTime": 1503932500097,
@@ -237,7 +212,8 @@
                 "description": "A provisioning adapter failed for host: .<p>\n      <p>Message: Dynamic Reverse DNS provisioning failed: null </p>",
                 "display": "Y",
                 "id": 367,
-                "ifIndex": null,
+                "label": "OpenNMS-defined Provisioning Adapter Failed message",
+                "location": "Default",
                 "log": "Y",
                 "logMessage": "\n      <p> ::Dynamic Reverse DNS provisioning failed: null </p>\n    ",
                 "nodeId": 2,
@@ -249,19 +225,16 @@
                         "value": "Dynamic Reverse DNS provisioning failed: null"
                     }
                 ],
-                "serviceType": null,
                 "severity": "MAJOR",
                 "source": "Provisioner",
                 "time": 1503932500097,
                 "uei": "uei.opennms.org/provisioner/provisioningAdapterFailed"
             },
             "lastEventTime": 1503932500097,
+            "location": "Default",
             "logMessage": "\n      <p> ::Dynamic Reverse DNS provisioning failed: null </p>\n    ",
-            "managedObjectInstance": null,
-            "managedObjectType": null,
             "nodeId": 2,
             "nodeLabel": "Synology",
-            "ossPrimaryKey": null,
             "parameters": [
                 {
                     "name": "reason",
@@ -269,19 +242,15 @@
                     "value": "Dynamic Reverse DNS provisioning failed: null"
                 }
             ],
-            "qosAlarmState": null,
             "reductionKey": "uei.opennms.org/provisioner/provisioningAdapterFailed::Dynamic Reverse DNS provisioning failed: null",
-            "serviceType": null,
             "severity": "MAJOR",
             "suppressedTime": 1503932500097,
             "suppressedUntil": 1503932500097,
             "type": 3,
             "uei": "uei.opennms.org/provisioner/provisioningAdapterFailed",
-            "x733AlarmType": null,
             "x733ProbableCause": 0
         },
         {
-            "ackId": 78,
             "count": 1,
             "description": "<p>SNMP data collection on interface 127.0.0.1\n      failed.</p>",
             "firstEventTime": 1503932194079,
@@ -294,8 +263,9 @@
                 "display": "Y",
                 "host": "With-Teeth.local",
                 "id": 358,
-                "ifIndex": null,
                 "ipAddress": "127.0.0.1",
+                "label": "OpenNMS-defined node event: dataCollectionFailed",
+                "location": "Default",
                 "log": "Y",
                 "logMessage": "\n      SNMP data collection on interface 127.0.0.1 failed with 'Timeout retrieving 'SnmpCollectors for 127.0.0.1' for 127.0.0.1.'.\n    ",
                 "nodeId": 5,
@@ -317,12 +287,10 @@
                 "uei": "uei.opennms.org/nodes/dataCollectionFailed"
             },
             "lastEventTime": 1503932194079,
+            "location": "Default",
             "logMessage": "\n      SNMP data collection on interface 127.0.0.1 failed with 'Timeout retrieving 'SnmpCollectors for 127.0.0.1' for 127.0.0.1.'.\n    ",
-            "managedObjectInstance": null,
-            "managedObjectType": null,
             "nodeId": 5,
             "nodeLabel": "Sin.local",
-            "ossPrimaryKey": null,
             "parameters": [
                 {
                     "name": "reason",
@@ -330,7 +298,6 @@
                     "value": "Timeout retrieving 'SnmpCollectors for 127.0.0.1' for 127.0.0.1."
                 }
             ],
-            "qosAlarmState": null,
             "reductionKey": "uei.opennms.org/nodes/dataCollectionFailed::5",
             "serviceType": {
                 "id": 1,
@@ -341,11 +308,10 @@
             "suppressedUntil": 1503932194079,
             "type": 1,
             "uei": "uei.opennms.org/nodes/dataCollectionFailed",
-            "x733AlarmType": null,
             "x733ProbableCause": 0
         }
     ],
     "count": 6,
-    "offset": 0,
+    "offset": null,
     "totalCount": 6
 }
```

**Comment by j-white** [comment]
The later, the current v2 endpoint (prior to these changes) returns a `null` for the offset.

**Comment by j-white** [comment]
As for the other missing values, the nulls aren't included in the response, they are returned when set.

It appears that the JAXB JSON Serializer we use will only include a null value if it is annotated with `@XmlAttribute`, but not when annotated with `@XmlElement`.

**Comment by RangerRick** [comment]
Yeah, I'll open a separate bug about the `offset` thing, otherwise it sounds good then, I'll go ahead and merge.

**Pull request merged**
