### PR TITLE
NMS-10413: Prefix all shell commands with "opennms"

### PR DESCRIPTION
**Pull request by patrick-schweizer**
* Jira: https://issues.opennms.org/browse/NMS-10413

### CODE REVIEW

**Comment by j-white** [comment]
That's a lot of shell commands :)

Changes look good, just need to agree with everyone on the best branch to target.

**Comment by patrick-schweizer** [comment]
> That's a lot of shell commands :)
> 
> Changes look good, just need to agree with everyone on the best branch to target.
what do you think? Is it better to target develop?

**Comment by patrick-schweizer** [comment]
@j-white as discussed I rebased to branch develop

**Comment by patrick-schweizer** [comment]
this PR is on hold until it is decided what to do with the ticket. Discussions go towards scoping instead of prefixing

**Comment by pbrane** [comment]
Wahoo!

**Pull request merged**
