### PR TITLE
NMS-10698: attempt to be more forgiving in timing of requisition tests

### PR DESCRIPTION
**Pull request by RangerRick**
A small PR to attempt to fix the EditInRequisition test to not flap.

* JIRA: http://issues.opennms.org/browse/NMS-10698

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by mvrueden** [comment]
Looking at Bamboo, this seems to have made things worse :)
https://bamboo.opennms.org/browse/OPENNMS-OPENNMS15

**Comment by RangerRick** [comment]
hehe, yeah, I'm still playing with it  :)  I should probably mark it triage

I don't have my full bamboo-like test environment setup, and on Friday I didn't feel like remote-X'ing in to a bamboo machine to fix my changes up.  I can do it today.

**Comment by RangerRick** [comment]
this should be better now, I had a thinko in my previous commit  :)

**Comment by RangerRick** [comment]
Any objections to me merging this now? It went green.

**Comment by mvrueden** [comment]
If it went green twice, you can merge it :)

**Pull request merged**
