### PR TITLE
NMS-11720: Run as non-root

### PR DESCRIPTION
**Pull request by indigo423**
Refactored the container image to run as non-root by default and runs with an arbitrary user id to be compatible to run in Open Shift. The following things are changed on a high level:

* cap_net_raw is set for the Java binary
* support [Arbitrary User IDs](https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html)
* Unify the directory structure so we don't have different situations when we install from RPM vs. tarball installation

JIRA: https://issues.opennms.org/browse/NMS-11720

As requested, I've uploaded an image to DockerHub with opennms/horizon:nms-11720.

### CODE REVIEW

**Comment by indigo423** [comment]
@agalue @Naicisum it would be nice to verify if this image can be tested in an Open Shift infrastructure to make sure it works as expected.

**Comment by agalue** [comment]
Here is a screenshot proving it is running:

opennms-in-openshift

```bash
➜  openshift git:(master) ✗ oc project
Using project "opennms" on server "https://192.168.99.140:8443".
➜  openshift git:(master) ✗ oc get pod
NAME                 READY     STATUS    RESTARTS   AGE
onms-0               1/1       Running   0          10m
postgresql-1-q2pvw   1/1       Running   1          23m
```

**Comment by indigo423** [comment]
> I'll defer to @agalue on this one and his tests looks good for me. My OpenShift environment is much more restrictive and would not be as generalized.
> 
> I would however add `umask 002` to the beginning of your `bootstrap.sh` script. It seems to help alleviate some issues inside OpenShift with how some programs create/manipulate files.

@Naicisum I've set umask 002 in our entry point as first instruction. I'll did a test locally and it had no other side effects. Let's see if we pass the smoke tests with it.

**Comment by indigo423** [comment]
* ✅ [Minimal](https://circleci.com/workflow-run/043527e6-1271-4b0a-9648-7c3c3afdc280) smoke tests pass
* ✅ [Full](https://circleci.com/workflow-run/3c8485fe-aabf-416c-a68c-e43aad004709) smoke tests pass

**Pull request merged**
