### PR TITLE
NMS-12775 fix interfaceSnmpByIfIndex for interfaces with no physaddr

### PR DESCRIPTION
**Pull request by nilmagus**
### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [n/a] If this is a new or updated feature, is there documentation for the new behavior?
* [n/a] If this is new code, are there unit and/or integration tests?
* [n/a] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12775

### CODE REVIEW

**Comment by RangerRick** [comment]
@cgorantla from our discussions in chat this _seems_ like it should be OK but I'd like your feedback on this since I'm guessing you have a better idea of the impact than I do.

**Comment by RangerRick** [comment]
Also if this is actually doing wrong things in current production, should this be in `foundation-2019` or `release-26.x`?

**Comment by cgorantla** [comment]
Looks fine to me.  Yeah, this may have to re targetted to `foundation-2019` at least.

**Comment by nilmagus** [comment]
@cgorantla re-targeted PR to `foundation-2019`

**Comment by cgorantla** [comment]
@nilmagus  need to rebase your branch to `foundation-2019`

**Comment by j-white** [comment]
Changes look good to me. Omitting the "-" when the value is null matches the logic in https://github.com/OpenNMS/opennms/blob/foundation-2019/core/lib/src/main/java/org/opennms/core/utils/RrdLabelUtils.java#L66

**Comment by RangerRick** [comment]
FYI, I just pushed a version of this rebased to `foundation-2019` to [OpenNMS:pr/jira/NMS-12775-smoke ](https://github.com/OpenNMS/opennms/tree/pr/jira/NMS-12775-smoke).  If [it passes in circle](https://app.circleci.com/pipelines/github/OpenNMS/opennms/6890/workflows/273ea64d-bf2d-4711-813c-60d2d3bdb965) we can merge that version instead.  It went green in the `develop` version.

**Comment by RangerRick** [comment]
It passed, I went ahead and merged the other version of this branch.

**Pull request closed without merging**
