### PR TITLE
changed an instance of MIB to OID in bridge-discovery.adoc

### PR DESCRIPTION
**Pull request by StCyr**

### CODE REVIEW

**Comment by mvrueden** [comment]
Hey @StCyr can you merge your branch with HZN-42 to resolve the merge conflicts?
Let me know if you need help with that or if you want me to do it.

**Comment by StCyr** [comment]
better now?

2015-10-07 12:42 GMT+02:00 mvrueden <notifications@github.com>:

**Comment by mvrueden** [comment]
Yes, thank you very much :)

**Comment by mvrueden** [comment]
Hey @StCyr the branch you want to merge this change into does not exist anymore and was also already merged to `develop`. I manually picked your changes and pushed it to `develop` instead (See commit https://github.com/OpenNMS/opennms/commit/ddc3eaed68e9c5505676f145c9693009e2529adb) for details.
I am closing this pull request.
Thank you very much :+1:

**Pull request closed without merging**
