### PR TITLE
NMS-9649: Align WS-Management collection definitions with WMI ones

### PR DESCRIPTION
**Pull request by jeffgdotorg**
Also made a few small enhancements and fixes along the way.

* JIRA: http://issues.opennms.org/browse/NMS-9649

### CODE REVIEW

**Comment by j-white** [comment]
Some of these resources types referenced here used the `IndexStorageStrategy`.

From the [docs](http://docs.opennms.org/opennms/releases/20.1.0/guide-admin/guide-admin.html#ga-performance-mgmt-collectors-wsman-collector):

When using a generic resource type, the IndexStorageStrategy cannot be used since records have no implicit index. Instead, you must use an alternative such as the SiblingColumnStorageStrategy.

**Comment by jeffgdotorg** [comment]
Good catch, thanks @j-white . Will fix those up.

**Comment by jeffgdotorg** [comment]
Resource-type problem addressed. I left the node-level attributes unchanged.

**Comment by j-white** [comment]
Cool. Looks better now. :+1:

**Pull request merged**
