### PR TITLE
NMS-7798: Add Sonicwall Events

### PR DESCRIPTION
**Pull request by mfuhrmann**
JIRA: http://issues.opennms.org/browse/NMS-7798
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS95

### CODE REVIEW

**Comment by soleger** [comment]
This definition is waaaaay too verbose. Each trap appears to have a single varbind and the list of possible values is several hundred values, each the same for every trap.

For each trap type, I would imagine that very few of the varbind values are possible. The list of hundreds of values needs to be reduced to the values that can actually occur for each trap.

**Comment by mfuhrmann** [comment]
I will try to clean up the file.

**Comment by soleger** [comment]
Can you change the UEI prefix from:
```
uei.opennms.org/traps/sonicwall
```
to:
```
uei.opennms.org/vendor/SonicWall
```
A majority of the traps use uei.opennms.org/vendor instead of uei.opennms.org/traps.

**Comment by soleger** [comment]
When this is merged, it MUST be merged manually as a squash merge to avoid committing the original, enormous file into the main OpenNMS repo.

**Comment by dschlenk** [comment]
FWIW typically vendor traps have uei.opennms.org/vendor/<VendorName>/traps as the prefix so as to distinguish from other event sources (syslog, etc).

**Comment by indigo423** [comment]
Cleaned up vendor names and recreated pull request with a single commit solved in #352.

**Pull request closed without merging**
