### PR TITLE
HZN-375: Added option to specifiy nameserver to DnsResolutionMonitor

### PR DESCRIPTION
**Pull request by fooker**
Fixes http://issues.opennms.org/browse/HZN-375.

Please review and merge.

Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS96

### CODE REVIEW

**Comment by mvrueden** [comment]
Please add the bamboo link so we can easyly see if bamboo is happy.

**Comment by soleger** [comment]
I would prefer that we merge this to develop since it rewrites the monitor completely. Also, the poll failure reason strings are different and somewhat less informative. Can we combine the old string and the new string into a longer description of the failure?

**Comment by fooker** [comment]
I'm OK with merging against develop.

I've changed the reason strings because the old ones are not correct: the old version says that only a A record was found if no AAAA record was found. This disregards the case where no record was returned at all.

If you can point me to a better message or have some hints which details to includ I will be happy to include that.

**Comment by opennms-bamboo** [comment]
Welcome @opennms-bamboo.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @opennms-bamboo.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by fooker** [comment]
I recreated the pull request against develop: #331.

**Comment by opennms-bamboo** [comment]
Welcome @opennms-bamboo.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @opennms-bamboo.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by mvrueden** [comment]
You can ignore the Welcome @opennms-bamboo message and merge it anyway, as soon as  this pull request is approved.

**Pull request closed without merging**
