### PR TITLE
NMS-16136: Convert node store to pinia

### PR DESCRIPTION
**Pull request by synqotik**
Convert node and also event stores from `vuex` to `pinia` and removed the corresponding `vuex` code. Needed before doing more work on Node Structure.

Had to refactor the `Pagination` control a bit to use `pinia` store methods/properties instead of creating strings for `vuex`. `Pagination:query` prop takes a method that takes `QueryParameters` only; if another param like node id is needed, caller supplies it inside the referenced methods.

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16136

### CODE REVIEW

**Comment by synqotik** [comment]
Smoke test is failing due to an unrelated issue being fixed elsewhere.

**Review by mikewrosey — APPROVED** [review]
lgtm. Nice to remove all those vuex files!

**Comment by synqotik** [comment]
> lgtm. Nice to remove all those vuex files!

hopefully will all be gone soon :)

**Comment by synqotik** [comment]
Merging since smoke test error is not related to this code.

**Pull request merged**
