### PR TITLE
HZN-1208: Introduce Classification Rest API

### PR DESCRIPTION
**Pull request by mvrueden**
* Jira: https://issues.opennms.org/browse/HZN-1208

### CODE REVIEW

**Comment by j-white** [comment]
I suspect we'll need some changes here once we start building the UI, but this looks like a good start.

Can we also include documentation for the provided endpoints?

**Comment by mvrueden** [comment]
I'd postpone documenting the endpoint until we have the ui build. 
I already started hacking on the ui bits and changed stuff. 
So I'd vote to postpone merging this, as some changes are required.

**Comment by mvrueden** [comment]
I created issue https://issues.opennms.org/browse/HZN-1236 to track the REST API Documentation progress.

**Comment by mvrueden** [comment]
PR https://github.com/OpenNMS/opennms/pull/1849 addresses a performance issue in the classification engine. We should gather some metrics from the results there before merging this, to ensure that we actually improved it. So we may want to hold off a bit before merging this.

**Comment by j-white** [comment]
Looks really good. I'll merge once Bamboo goes green.

**Pull request merged**
