### PR TITLE
NMS-9754: RTC subscription events should not be persisted to DB

### PR DESCRIPTION
**Pull request by jeffgdotorg**
* JIRA: http://issues.opennms.org/browse/NMS-9754

### CODE REVIEW

**Comment by soleger** [comment]
This is a config change so it can't be targeted for `foundation` without impacting upgrades.

**Comment by indigo423** [comment]
Can we use a section in the "Whats new" section which comes from a JIRA component "Configuration Files"? This way people have one spot to look when they do updates.

**Comment by j-white** [comment]
Can we just re-target this to develop? May as well have it in new releases, then not at all.

**Comment by mvrueden** [comment]
Retargeted to `develop`. It is now conflicting @jeffgdotorg can you take a look?

**Comment by jeffgdotorg** [comment]
As @j-white says, better to get this in the next Horizon than never. Targeted the issue to Horizon 26, requested review.

**Comment by jeffgdotorg** [comment]
(Fixed conflict)

**Comment by indigo423** [comment]
@jeffgdotorg If we want this to have in 26.0.0 we have to retarget to release-26.0.0 branch instead of develop. Develop is going to be 27.0.0-SNAPSHOT.

**Pull request merged**
