### PR TITLE
NMS-10690: Upgrade Maven & Plugins to latest releases

### PR DESCRIPTION
**Pull request by roskens**
NMS-10690: Upgrade Maven & Plugins to latest releases

* JIRA: http://issues.opennms.org/browse/NMS-10690

### CODE REVIEW

**Comment by mvrueden** [comment]
Is there a particular reason, why updating maven and related plugins? 
Are the plugin version updates required?
I am asking, because I know that at some point upgrading the `maven-deploy-plugin` will break Bamboo.

**Comment by roskens** [comment]
Articles I've read on the internet recommend updating maven & plugins to their latest versions to fix issues when running jdk9+.

**Comment by mvrueden** [comment]
> Articles I've read on the internet recommend updating maven & plugins to their latest versions to fix issues when running jdk9+.

In order to make these changes work, we must change our Bamboo jobs. If we merge this as is, this will break `mvn deploy`.

**Comment by j-white** [comment]
Changing the `maven-bundle-plugin` is always risky too. 

I suggest we break this out instead of trying to do a bulk upgrade, too much risk involved and we're not actually solving anything specific.

**Comment by roskens** [comment]
> > Articles I've read on the internet recommend updating maven & plugins to their latest versions to fix issues when running jdk9+.
> 
> In order to make these changes work, we must change our Bamboo jobs. If we merge this as is, this will break `mvn deploy`.

How would one know if a `mvn deploy` will break?  Can we get that documented somewhere?

I can split the plugin updates up into additional commits or into additional PRs if that would be preferred.

**Pull request closed without merging**
