### PR TITLE
NMS-14688: DCB Rest API and UI updates to capture when user enters DCB

### PR DESCRIPTION
**Pull request by synqotik**
Updates to be able to capture when a user enters the Device Configuration Backup page in the UI Preview. This will be used to update a usage analytics counter.

- Rest API updated to have an optional 'pageEnter' query param
- Query param set to 'true' in UI when DCB Vue component is mounted

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14688

### CODE REVIEW

**Comment by cgorantla** [comment]
If we need to capture UI page entries, shouldn't that be separate Rest service ?

**Comment by synqotik** [comment]
> If we need to capture UI page entries, shouldn't that be separate Rest service ?

Possibly, we should have a discussion on this.

**Review by amay94 — APPROVED** [review]
I can't speak to the typescript / vue changes, but the backend changes look good.

**Review by mikewrosey — APPROVED** [review]

**Comment by synqotik** [comment]
I'll merge this once builds are green, we can discuss separate endpoint separately and also fix this if we go that route.

**Pull request merged**
