### PR TITLE
NMS-12150: Allow editing an existing Report Schedule

### PR DESCRIPTION
**Pull request by mvrueden**
Here we provide the functionality to edit an already scheduled report.
Error Handling is still a bit user-unfriendly, but will be addressed soon.

I created a `report-details` directive to re-use it when either creating the schedule and editing it later on.

@RangerRick the edit button now works :)

JIRA: https://issues.opennms.org/browse/NMS-12150

### CODE REVIEW

**Comment by RangerRick** [comment]
At first glance, this looks good.  Working on testing it locally right now.

**Comment by RangerRick** [comment]
Just tried creating a new report on my own machine and leaving everything default, I get this error:
report could not be scheduled

Turns out it's because I still had the old scheduled report saved from last time I tested your editor changes, so the auto-generated name conflicts with an existing one.  It looks like the actual error ("already exists") is not bubbling up properly.  In the logs I see this:

```
org.quartz.ObjectAlreadyExistsException: Unable to store Trigger with name: 'local_Grafana-Dashboard-Report-1ppp admin' and group: 'reporting', because one already exists with this iden
tification.
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1179) ~[quartz-2.2.3.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$4.executeVoid(JobStoreSupport.java:1159) ~[quartz-2.2.3.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3719) ~[quartz-2.2.3.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3717) ~[quartz-2.2.3.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:245) ~[quartz-2.2.3.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1155) ~[quartz-2.2.3.jar:?]
        at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:932) ~[quartz-2.2.3.jar:?]
        at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:258) ~[quartz-2.2.3.jar:?]
        at org.opennms.web.svclayer.support.DefaultSchedulerService.addCronTrigger(DefaultSchedulerService.java:238) [opennms-web-api-25.0.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) [org.apache.servicemix.bundles.spring-aop-4.2.9.RELEASE_1.jar:?]
```

Also, the default report range seems weird, I expect people will be confused by running a report from 1 day ago to 1 day ago.  Shouldn't it be "1 day ago to now" or something?

1 day ago to 1 day ago

I did test editing an existing report and my changes do seem to persist properly. 👍

**Comment by mvrueden** [comment]
The error messages need to be improved and are not part of this PR. See issue [NMS-12151](https://issues.opennms.org/browse/NMS-12151) for more details.

I can look into the default value handling, but this is not the focus of this PR.

**Comment by mvrueden** [comment]
I am going ahead and merge this, as the things mentioned in the PR will be addressed soon.

**Pull request merged**
