### PR TITLE
NMS-12823: Application Topology Provider Status

### PR DESCRIPTION
**Pull request by patrick-schweizer**
This PR fixed the search for Appliations and adds a table "Current Outages" to the Application Topology Map.

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12823

All current (non resolved) outages of associated monitored location of the displayed applications are shown in the table:
 
image

When clicked on the outage id a popop with the outage detail information is shown:

image

### CODE REVIEW

**Comment by patrick-schweizer** [comment]
@fooker , @christianpape is this how you imagined the table?

**Comment by patrick-schweizer** [comment]
@fooker , @christianpape , @indigo423, I changed the title of the tab as discussed to "Current Perspective Outages"

**Review by christianpape — APPROVED** [review]
LGTM

**Review by indigo423 — COMMENTED** [review]
👍LGTM! Thank you

**Pull request merged**
