### PR TITLE
NMS-7903: Improved docs for Elasticsearch integration

### PR DESCRIPTION
**Pull request by unicolet**

### CODE REVIEW

**Comment by indigo423** [comment]
@unicolet I've sent you a pull request with a review of your docs. Really cool :+1:

**Comment by indigo423** [comment]
Can you cleanup the commits to a single commit with git rebase -ii against develop?
Here is a tutorial for it: http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit
Please let me know if you have trouble.

**Comment by mvrueden** [comment]
@unicolet, if you are doing the rebase, can you please include the issue number on each commit message? That would be awesome :)

**Comment by indigo423** [comment]
Yes you are able to write a useful commit message and get rid of all the typo fixes. A commit message is the following structure:

```
NMS-<number>: Subject

some text some text some text some text some text 
some text some text some text some text some text
some text some text some text some text some text
some text.
```

**Comment by unicolet** [comment]
I gave it a try, but this rebase thing is taking too long for me to figure out. If anyone wants to give it a stab join me at:

https://ide.c9.io/unicolet/opennms

and I will grant you r/w access

**Comment by indigo423** [comment]
Hi Umberto,

sure no problem, if you add me to your repository. I can do this for you.

Thank you very much.

--
Ronny Trommer, OGP, Germany :: Fulda :: Stuttgart
Web: http://www.opennms.org <http://www.opennms.org/>

PGP Key Fingerprint: 4A1B 4D06 FEEC 244D 38EF  8074 9075 B2E5 08A2 451E
PGP Key Server1: https://keyserver.pgp.com <https://keyserver.pgp.com/>
PGP Key Server2: http://pgp.mit.edu/ <http://pgp.mit.edu/>

**Pull request merged**
