### PR TITLE
Clean up help for opennms:stress-metrics, add example for --rra

### PR DESCRIPTION
**Pull request by dino2gnt**
### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [ ] Have you made a comment in that issue which points back to this PR?
* [ ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

No jira.  This is only copyediting and the addition of an example in a case where I found the usage unclear.

### CODE REVIEW

**Review by mmahacek — APPROVED** [review]
Looks good to me.  Makes the text more concise, and the RRA example helps.

**Comment by agalue** [comment]
Actually, for the RRA description, it doesn't default to what's inside `datacollection-config.xml`; it defaults to what's hardcoded [here](https://github.com/OpenNMS/opennms/blob/65e0718a6ed9f9d9d17d72cf22ef58a98ddca2d9/features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/CollectCommand.java#L77). Without alterations of the configuration, the content of `CollectCommand.DEFAULT_RRA` matches the content of the default collection in `datacollection-config.xml`. Still, nothing prevents you from having something different (or even have multiple `snmp-collections`). If that's the case, those customizations are ignored; hence the reason why I added a way to specifies the `rras` on this command years ago.

**Comment by dino2gnt** [comment]
I've altered the text to make it clearer that the RRAs are not read from an existing config.

**Review by agalue — APPROVED** [review]
LGTM

**Pull request merged**
