### PR TITLE
HZN-344: Provide a tool for importing existing .rrd / .jrb metrics into Newts

### PR DESCRIPTION
**Pull request by fooker**
Added a tool for converting existing metric repositories to NewTS.

JIRA: http://issues.opennms.org/browse/HZN-344
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS235

### CODE REVIEW

**Comment by indigo423** [comment]
Why does this pull request has so many commits from Alejandro and Jesse?

**Comment by j-white** [comment]
Collaboration.

**Comment by indigo423** [comment]
check :)

**Comment by agalue** [comment]
Ronny, because I started the work (extracting, or actually do my best effort to extract the raw values from the stored data on RRD/JRB files using my opennms-rrd-model), and then the issue was assigned to someone else ;)

**Comment by indigo423** [comment]
ok got it, just thought - Wow reviewer will have fun :)

**Comment by j-white** [comment]
Bamboo is still failing on this one.

**Comment by j-white** [comment]
@fooker can we revert to Newts v1.3.2 before merging this, or is there something is v1.3.3 that's required now? I don't think I'll have time to release Newts v1.3.3 before OpenNMS 17.0.0 is released.

**Comment by j-white** [comment]
I'm getting UnmarshalExceptions when trying to convert JRobin archives:

```
Exception in thread "ForkJoinPool-1-worker-4" Exception in thread "ForkJoinPool-1-worker-3" Exception in thread "ForkJoinPool-1-worker-6" org.opennms.features.newts.converter.NewtsConverterError: Can't parse JRB/RRD /home/jesse/git/opennms/target/opennms/share/rrd/response/127.0.0.1/icmp.(rrd/jrb): Can't parse RRD Dump
	at org.opennms.features.newts.converter.NewtsConverterError.create(NewtsConverterError.java:50)
	at org.opennms.features.newts.converter.NewtsConverter.processResource(NewtsConverter.java:460)
	at org.opennms.features.newts.converter.NewtsConverter.lambda$null$2(NewtsConverter.java:388)
	at org.opennms.features.newts.converter.NewtsConverter$$Lambda$9/1011480396.run(Unknown Source)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.jrobin.core.RrdException: Can't parse RRD Dump
	at org.opennms.netmgt.rrd.model.RrdConvertUtils.dumpRrd(RrdConvertUtils.java:102)
	at org.opennms.features.newts.converter.NewtsConverter.processResource(NewtsConverter.java:453)
	... 7 more
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at org.opennms.netmgt.rrd.model.RrdConvertUtils.dumpRrd(RrdConvertUtils.java:100)
	... 8 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	... 12 more
```

**Comment by fooker** [comment]
The tool itself will work fine with newts-1.3.2. But the integration tests will fail, because newts will calculate some values with a larger error. As the tool is not super-critical, I propose to merge this as soon as 17.0.1 is coming. Maybe we can hand out the tool before to customers asking for it and get some more feedback.

**Comment by fooker** [comment]
@j-white can you provide the jrb file which is failing?

**Comment by fooker** [comment]
@j-white you have to call the tool using ```-t false``` to make it work with JRobin files.

**Comment by fooker** [comment]
As this was not merged in v17.0.0 please open another pull request against branch ```release-17.0.1```.

**Comment by fooker** [comment]
New Pull request: https://github.com/OpenNMS/opennms/pull/478

**Pull request closed without merging**
