### PR TITLE
NMS-8015: remove SMS reflector from tools and RXTX from build

### PR DESCRIPTION
**Pull request by RangerRick**
While the SMS reflector has been removed for a few major releases, the RXTX dependencies have remained.  Remove RXTX and remove the SMS reflector from opennms-tools since it has gone unmaintained and unused.

### CODE REVIEW

**Comment by pbrane** [comment]
I think it is quite possible that someone could be using the RXTX stuff for "out of band" notifications.  I would, if I had time to implement it.  Could we pull this into an opennms-tools branch or is it there already?

**Comment by RangerRick** [comment]
It's there already, and no one has even checked if it still works for 2 major releases.  It would take some work to modernize it and fix the rxtx dependencies to be in the tools version rather than in OpenNMS proper.

**Comment by pbrane** [comment]
Okay.

**Comment by soleger** [comment]
We can also do OOB SMS notifications by following Tarus' recent blog post:

http://www.adventuresinoss.com/2015/09/03/send-an-sms-with-opennms/

**Comment by pbrane** [comment]
Yeah, I was looking for plugin support within the JVM.  But, I agree, that works, too.

David

**Pull request merged**
