### PR TITLE
Added Hibernate Support for org.opennms.netmgt.capsd 

### PR DESCRIPTION
**Pull request by vishwaAbhinav**
Created a prototype for Hibernate usage in openNMS, as a pre-requirement task for project "Finish converting OpenNMS to use Hibernate".

### CODE REVIEW

**Comment by indigo423** [comment]
@thedesloge we should close this issue unmerged, CapsD is removed.

**Comment by soleger** [comment]
There is still some code in this pull request outside of Capsd that might be useful. We should try rebasing it off of develop and see what changes remain.

**Comment by soleger** [comment]
I'm working on merging these changes now.

**Comment by soleger** [comment]
After reviewing the changes, the only unique thing added was Hibernate mappings to the servicemap and servermap tables but because these tables are unused, there is not need to merge the pull request. I've opened JIRA issue NMS-7689 regarding removal of these tables. I'm going to mark this pull request as closed. Abhinav, we appreciate the changes but unfortunately Capsd was deprecated and the changes were not needed. If you would like to work on more Hibernate conversion tasks, there are many listed under the following bug in JIRA: http://issues.opennms.org/browse/HZN-261

Thanks!

**Pull request closed without merging**
