### PR TITLE
NMS-14041: correct G1 perm/eden/old/survivor mbean names in jmx collection

### PR DESCRIPTION
**Pull request by dino2gnt**
This change may have been introduced when we moved past JDK 8.  Did not verify beyond these names being correct for current versions of JDK 11.

Tagged for `foundation-2019` because the release notes  for M2019 state "We recommend the latest version of OpenJDK 11" and in that case, these metrics are broken all the way back.  Let me know if that's not okay.

### All Contributors

* [ ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14041

### CODE REVIEW

**Comment by dherdt** [comment]
I propose to use instead of "G1" this: "*" - it works also for older and probably newer JVMs
Also i have in my JVM no "Perm Gen". I think that "Metaspace" must be used  instead of it (or additionally to have compatibility with older JVMS).

**Review by dherdt — APPROVED** [review]
Looks good

**Review by RangerRick — APPROVED** [review]
normally I would ask "are you sure you want to change configs in old releases?" but you're support so it's your problem when people's configs change and you have to manually update configs ;)

**Comment by cgorantla** [comment]
> normally I would ask "are you sure you want to change configs in old releases?" but you're support so it's your problem when people's configs change and you have to manually update configs ;)

May be we need to add a note to breaking changes ( may be it's rare there is chance that customers edit  [jmx-datacollection-config.xml](https://github.com/OpenNMS/opennms/pull/5145/files#diff-b775274ad17acfa9ccba188bdbb0f99f312c95689d5917186686008aa6353ec6))

**Comment by RangerRick** [comment]
> May be we need to add a note to breaking changes ( may be it's rare there is chance that customers edit [jmx-datacollection-config.xml](https://github.com/OpenNMS/opennms/pull/5145/files#diff-b775274ad17acfa9ccba188bdbb0f99f312c95689d5917186686008aa6353ec6))

yeah, that's a good idea

**Comment by dino2gnt** [comment]
From my point of view, the jsr160 collection in jmx-datacollection-config.xml is exclusively used to monitor the OpenNMS JVM itself.  I can't think of a customer environment where this has been heavily edited (versus being completely replaced with something else) or where this collection is being leveraged to collect metrics on a JVM that isn't OpenNMS.

The rest of Client Services appear to be okay with it, so I'm wiling to give it a go.

**Comment by cgorantla** [comment]
No objection on fixing and merging this to `foundation-2019` but a note to breaking changes will be good to track any changes to config.

**Pull request merged**
