### PR TITLE
Happy New Year 2016

### PR DESCRIPTION
**Pull request by jeffgdotorg**
Copyright year updates in web UI

### CODE REVIEW

**Comment by agalue** [comment]
The header with the date exist on all the .java files (and several but not all the .jsp as well). Should we update them as well ?

**Comment by jeffgdotorg** [comment]
The dates in the non-user-facing files get updated only when something else in those files is changed.

**Comment by agalue** [comment]
I asked because you changed the headers I'm referring here on the JSPs involved in this pull request, but either way, that sounds good to me.

**Comment by indigo423** [comment]
I bet @RangerRick has a boilerplate update script which fixes all that :) :cross finger:

**Comment by RangerRick** [comment]
I have a script that gets you 90% there, but needs a lot of hand management.  :)

**Pull request merged**
