### PR TITLE
NMS-14565: backport Guava fixes to foundation-2022

### PR DESCRIPTION
**Pull request by RangerRick**
This is a backport of the work done for NMS-14209 (in https://github.com/OpenNMS/opennms/pull/5072) to `foundation-2022`.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14565

### CODE REVIEW

**Comment by RangerRick** [comment]
I guess everyone's afraid of this one? 😅

Really this is mostly an FYI, the changes are basically the same as what's been in H30 for a couple of months, I just held off pushing it to a Meridian release until we'd had a little time to find unintended consequences. AFAICT there weren't any in 30 because of my Guava changes, so it should be pretty safe.

**Comment by RangerRick** [comment]
(but I do still want someone to look it over and make sure there's nothing that jumps out at you)

**Comment by deejgregor** [comment]
> (but I do still want someone to look it over and make sure there's nothing that jumps out at you)

Ooops. I forgot I was poked for this one. I’ll take a look by tomorrow if that’s soon enough.

**Review by deejgregor — APPROVED** [review]

**Review by Naicisum — APPROVED** [review]
LGTM, my only feed back is I noticed a pattern change in the behavior of Cassandra interaction with respect to OpenNMS. Nothing that requires attention, just enough deviation to warrant a foot note.

**Review by fooker — APPROVED** [review]

**Review by cgorantla — APPROVED** [review]

**Review by christianpape — APPROVED** [review]

**Pull request merged**
