### PR TITLE
NMS-9092: Add support for value modifier and base units in VMware data collection

### PR DESCRIPTION
**Pull request by indigo423**
Add support to VMware meta data for performance metrics to read base units and value modifier to be persisted instead of just the raw data.

* JIRA: http://issues.opennms.org/browse/NMS-9092

### CODE REVIEW

**Comment by soleger** [comment]
To target this for Meridian 2017, you'll have to wait until we create the foundation-2017 branch and then target the PR at it.

**Comment by j-white** [comment]
There are merge conflicts here now caused by the changes in HZN-1008.

**Comment by indigo423** [comment]
@christianpape cool thanks for solving the merge conflicts

**Comment by soleger** [comment]
I committed these changes rebased to foundation-2017. I'll also commit the conflict resolutions when the changes are merged to develop. Closing PR.

**Pull request closed without merging**
