### PR TITLE
HZN-347: Expose Newts metrics via JMX

### PR DESCRIPTION
**Pull request by fooker**
Added a metric reporter which exposes all newts specific metrics via JMX.

Issue: http://issues.opennms.org/browse/HZN-347
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS127

### CODE REVIEW

**Comment by mvrueden** [comment]
Jesse is on vacation. Maybe someone else can review it.

**Comment by opennms-bamboo** [comment]
Welcome @opennms-bamboo.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @opennms-bamboo.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @opennms-bamboo.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @opennms-bamboo.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by mvrueden** [comment]
Hey Ulf, too much Jägermeister? Can you please calm down and redo the OCA check?

**Comment by mvrueden** [comment]
Ulf, redo OCA

**Comment by mvrueden** [comment]
I added Ulf to the executed OCA list, so he is not welcoming himself anymore.

**Comment by soleger** [comment]
It's impossible to see the relevant changes here because there are a lot of recent develop changes merged into this. We should merge from develop into features-newts to minimize the diff before reviewing.

**Comment by fooker** [comment]
The merge of develop was done by @RangerRick. I think it's related to some recent changes required for bamboo. I reverted the merge to make this PR more clear. Afterwards we should follow the procedure @soleger promoted.

**Pull request merged**
