### PR TITLE
NMS-13981 - Weak Password Policy

### PR DESCRIPTION
**Pull request by isoftsolutions**
I followed the instructions of Jeff and added a gpdr based minimum recommadation of password complexity.
(minimum 12 characters, consisting of 1 special character, 1 upper case letter, 1 lower case letter and 1 number)

https://issues.opennms.org/browse/NMS-13981

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

### CODE REVIEW

**Review by synqotik — CHANGES_REQUESTED** [review]
This looks good for the client side. However, need same checks on server side, and also check for max 128 characters.
Code in: https://github.com/OpenNMS/opennms/blob/89285c3fc8f885b226868f39430fe0ffb5542769/opennms-webapp/src/main/java/org/opennms/web/account/selfService/NewPasswordActionServlet.java

If you want, could approve this PR to get client side code merged, then open another PR for server side.

**Review by synqotik — DISMISSED** [review]
LGTM!

**Comment by synqotik** [comment]
Good point, need to follow up with Jeff G. on this.

**Comment by isoftsolutions** [comment]
> How does this interact with a shipped default admin password of 'admin' ?

This changes have nothing to do with default password. There is no impact, actually. Only when you change your password.

**Comment by isoftsolutions** [comment]
IMHO: after the first login, the user have to change the default admin password. That's the right way to avoid some risks.

**Review by synqotik — APPROVED** [review]

**Pull request merged**
