### PR TITLE
Fix DefaultRrdSummaryService race condition

### PR DESCRIPTION
**Pull request by ivansjg**
There is a race condition on `DefailtRrdSummaryService` class which is the root of many errors if you make requests quick enough to the following endpoint: https://opennms.host/opennms/summary/results.htm .

In my opinion this is because the variable `m_lastStarted` is shared among all threads, so I decoupled it wrapping it in a `ThreadLocal`.

JIRA: ?

Todo:
- [ ] Create JIRA issue and branch from develop with JIRA issue number
- [x] OCA signed (http://www.opennms.org/wiki/Contributor_Agreement)
- [ ] Verify if this patch is required in latest develop
- [ ] Code review
- [ ] Pass unit tests
- [ ] Merge to develop and close JIRA issue

### CODE REVIEW

**Comment by indigo423** [comment]
Alfred, please check the OCA

**Comment by opennms-bamboo** [comment]
Welcome Ivan San Jose (isanjose@riplife.es).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Ivan San Jose (isanjose@riplife.es).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by ivansjg** [comment]
I've just sent you the OCA signed. Sorry for the delay.
Regards.

**Comment by RangerRick** [comment]
Ulf, could you check Ivan's OCA again?

**Comment by indigo423** [comment]
Ulf, could you check Ivan's OCA again?

**Comment by RangerRick** [comment]
(Ulf bot apparently has an issue, Markus is looking into it right now.  <g>)

**Comment by mvrueden** [comment]
Hey Ulf, please approve isanjose@riplife.es as ivansjg.

**Comment by soleger** [comment]
I've manually merged this commit into develop for inclusion in OpenNMS 17. Thanks Ivan!

**Comment by j-white** [comment]
FYI, this commit actually broke the RrdSummaryController. See https://issues.opennms.org/browse/NMS-8743 for details.

**Pull request closed without merging**
