### PR TITLE
NMS-4549: Add Santera Events

### PR DESCRIPTION
**Pull request by mfuhrmann**
I did not change eventconf.xml because I don't know if it is too much for including them per default.

JIRA: http://issues.opennms.org/browse/NMS-4549
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS414-1

### CODE REVIEW

**Comment by indigo423** [comment]
What, I miss is the include in the eventconf.xml?

**Comment by indigo423** [comment]
Bamboo failed for the reason we have the event files but they are not included in the eventconf.xml

http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS94-UNIT-1/test/case/128340924

**Comment by mfuhrmann** [comment]
If ONMS can handle it without any problems, we should merge it. But I'm not a ONMS developer. I don't know if it is too big.
The feature list will look nice with it: "We added ~4000 events for Santera devices" :-)

**Comment by dschlenk** [comment]
maybe throw it in the examples directory?

**Comment by indigo423** [comment]
@dschlenk I like this idea. What do you think @mfuhrmann.

**Comment by indigo423** [comment]
See comment in JIRA issue

**Pull request closed without merging**
