### PR TITLE
NMS-13007: PrometheusCollector tries to persist non-integer values

### PR DESCRIPTION
**Pull request by dino2gnt**
… counter datasources

### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13007

### CODE REVIEW

**Comment by dino2gnt** [comment]
This is failing integration tests, but I won't have a chance to look at it until next week.

**Comment by j-white** [comment]
Nice job in identifying this.

I think it would be more appropriate to fix this in the RRD strategy itself, rather than baking this into the collector. Something like:
```
diff --git a/features/collection/persistence-rrd/src/main/java/org/opennms/netmgt/collection/persistence/rrd/RrdPersistOperationBuilder.java b/features/collection/persistence-rrd/src/main/java/org/opennms/netmgt/collection/persistence/rrd/RrdPersistOperationBuilder.java
index 6b022345bb4..3a0e59f2ab9 100644
--- a/features/collection/persistence-rrd/src/main/java/org/opennms/netmgt/collection/persistence/rrd/RrdPersistOperationBuilder.java
+++ b/features/collection/persistence-rrd/src/main/java/org/opennms/netmgt/collection/persistence/rrd/RrdPersistOperationBuilder.java
@@ -167,6 +167,10 @@ public class RrdPersistOperationBuilder implements PersistOperationBuilder {
     }
 
     public static String mapValue(Number num) {
+        return mapValue(num, AttributeType.GAUGE);
+    }
+
+    public static String mapValue(Number num, AttributeType type) {
         if (num == null) {
             return "U";
         }
@@ -178,7 +182,12 @@ public class RrdPersistOperationBuilder implements PersistOperationBuilder {
         NumberFormat nf = NumberFormat.getInstance(Locale.US);
         nf.setGroupingUsed(false);
         nf.setMinimumFractionDigits(0);
-        nf.setMaximumFractionDigits(Integer.MAX_VALUE);
+        if (AttributeType.COUNTER.equals(type)) {
+            // No decimals allowed for counters
+            nf.setMaximumFractionDigits(0);
+        } else {
+            nf.setMaximumFractionDigits(Integer.MAX_VALUE);
+        }
         nf.setMinimumIntegerDigits(0);
         nf.setMaximumIntegerDigits(Integer.MAX_VALUE);
         return nf.format(num);
@@ -225,7 +234,7 @@ public class RrdPersistOperationBuilder implements PersistOperationBuilder {
             } else {
                 first = false;
             }
-            values.append(mapValue(value));
+            values.append(mapValue(value, attrDef.getType()));
         }
         return values.toString();
     }
diff --git a/features/collection/persistence-rrd/src/test/java/org/opennms/features/collection/persistence/rrd/RrdPersistOperationBuilderTest.java b/features/collection/persistence-rrd/src/test/java/org/opennms/features/collection/persistence/rrd/RrdPersistOperationBuilderTest.java
index 1db0e716466..34f05fa2ab3 100644
--- a/features/collection/persistence-rrd/src/test/java/org/opennms/features/collection/persistence/rrd/RrdPersistOperationBuilderTest.java
+++ b/features/collection/persistence-rrd/src/test/java/org/opennms/features/collection/persistence/rrd/RrdPersistOperationBuilderTest.java
@@ -34,6 +34,7 @@ import java.text.NumberFormat;
 import java.util.Locale;
 
 import org.junit.Test;
+import org.opennms.netmgt.collection.api.AttributeType;
 import org.opennms.netmgt.collection.persistence.rrd.RrdPersistOperationBuilder;
 
 public class RrdPersistOperationBuilderTest {
@@ -49,6 +50,11 @@ public class RrdPersistOperationBuilderTest {
         assertEquals("U", RrdPersistOperationBuilder.mapValue(null));
         assertEquals("U", RrdPersistOperationBuilder.mapValue(Double.NaN));
         assertEquals("U", RrdPersistOperationBuilder.mapValue(Double.POSITIVE_INFINITY));
+
+        assertEquals("2", RrdPersistOperationBuilder.mapValue(2.0000d, AttributeType.COUNTER));
+        assertEquals("2", RrdPersistOperationBuilder.mapValue(2.0000d, AttributeType.GAUGE));
+        assertEquals("2", RrdPersistOperationBuilder.mapValue(2.0001d, AttributeType.COUNTER));
+        assertEquals("2.0001", RrdPersistOperationBuilder.mapValue(2.0001d, AttributeType.GAUGE));
     }
 
     @Test
```

**Comment by dino2gnt** [comment]
I agree, that makes far more sense.  I'll move the bits around.

**Comment by j-white** [comment]
Works for me. May want to consider targeting the `release-27` branch so that this makes it into 27.x instead of waiting for 28.0.0.

**Comment by dino2gnt** [comment]
Switched to `release-27.x`  

Clear to merge?

**Review by j-white — APPROVED** [review]

**Pull request merged**
