### PR TITLE
NMS-9465: HTTPS response time

### PR DESCRIPTION
**Pull request by mfuhrmann**
https://issues.opennms.org/browse/NMS-9465

### CODE REVIEW

**Comment by indigo423** [comment]
Can we retarget to foundation? Thank you for your contribution.

**Comment by soleger** [comment]
@indigo Are you satisfied with retargeting to foundation-2017? This would introduce configuration file changes for older foundations.

**Comment by indigo423** [comment]
@soleger no problem with that, I was unsure cause it fixes a bug and develop seemed to me very late as a merge target. Foundation 2017 is fine for me.

**Comment by soleger** [comment]
I'll rebase this branch against foundation-2017 and push to our repo. After it passes Bamboo, I'll go ahead and merge and close this PR.

**Comment by soleger** [comment]
Merged branch to foundation-2017. Closing this PR.

**Pull request closed without merging**
