### PR TITLE
NMS-8337: Introduce relaxed mode for Measurements API to allow empty …

### PR DESCRIPTION
**Pull request by mvrueden**
* JIRA: http://issues.opennms.org/browse/NMS-8337
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS634

### CODE REVIEW

**Comment by agalue** [comment]
@mvrueden Bamboo is complaining:
http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS634-UNIT-4

Please check those tests, and once everything goes green on Bamboo, I'll verify the solution on my testing environment and merge it.

**Comment by mvrueden** [comment]
@agalue I forgot to update the test. Bamboo should pass now.

**Comment by agalue** [comment]
Thanks a lot! I'll build it and test it.

**Comment by agalue** [comment]
It is working for me. The report is now generated properly with NaN for the non-existing metrics.

I tested it on a Newts environment to be sure that the Measurements API and the Cassandra backend are working.

I don't know how to test the remote report repositories, or if there is something else we should test prior merging this PR.

**Comment by mvrueden** [comment]
The remote report repositories use the same logic. 
No additional tests are required.

**Pull request merged**
