### PR TITLE
NMS-12636: Can't change password using the user self service

### PR DESCRIPTION
**Pull request by cgorantla**
### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12636
* Bamboo (Continuous Integration): https://bamboo.opennms.org/

### CODE REVIEW

**Comment by cgorantla** [comment]
This may not be final fix.  As I don't see any code changes other than Bootstrap elements on this page, I guess this may be coming from the search functionality feature.  Going to dig through changes. @RangerRick  let me know if you can throw some light on this.

**Comment by RangerRick** [comment]
Yeah, after our discussion in chat I would say we revert the search bar for now until we can figure out what's going on.  You want to do it, or shall I?

**Comment by cgorantla** [comment]
> Yeah, after our discussion in chat I would say we revert the search bar for now until we can figure out what's going on. You want to do it, or shall I?

Please go ahead and disable it.

**Comment by j-white** [comment]
There are some smoke tests related to the search bar that need to either be ignored, or for which we would need to enable it.

**Comment by cgorantla** [comment]
> There are some smoke tests related to the search bar that need to either be ignored, or for which we would need to enable it.

navbar.ftl changes are insufficient, Had to explicitly remove it from `bootstrap.jsp` as well

**Comment by cgorantla** [comment]
Works fine now :+1:

**Comment by cgorantla** [comment]
Created https://issues.opennms.org/browse/NMS-12646 for re-enabling search funtionality.
Everything is passing now. Merging

**Pull request merged**
