### PR TITLE
HZN-1581: Fixed type mismatch for VLAN value

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/HZN-1581

### CODE REVIEW

**Comment by mvrueden** [comment]
This was reported as "working" by a customer.

**Comment by mvrueden** [comment]
We discussed yesterday about adding tests here.
If too complicated tests may be omitted, as customer reported this as working.

**Comment by j-white** [comment]
We've seen a number of these type mismatches happen now. What's the challenge in adding tests for this? Something like: Mock the data, use the classes to write the BSON document, read the BSON document and make sure that all of the fields can be parsed

**Comment by christianpape** [comment]
Ok, you are right. I will start to work on a test to cover these errors...

**Comment by christianpape** [comment]
Added tests. Please review...

**Pull request merged**
