### PR TITLE
NMS-10268: render dateformat for Vaadin

### PR DESCRIPTION
**Pull request by patrick-schweizer**
* JIRA: https://issues.opennms.org/browse/NMS-10268

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by mvrueden** [comment]
@patrick-schweizer you mentioned, that you encounter this issue when starting OpenNMS:

```
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=dashlet-alarms; type=karaf.feature; version="[21.1.0.SNAPSHOT,21.1.0.SNAPSHOT]"; filter:="(&(osgi.identity=dashlet-alarms)(type=karaf.feature)(version>=21.1.0.SNAPSHOT)(version<=21.1.0.SNAPSHOT))" [caused by: Unable to resolve dashlet-alarms/21.1.0.SNAPSHOT: missing requirement [dashlet-alarms/21.1.0.SNAPSHOT] osgi.identity; osgi.identity=org.opennms.features.vaadin-dashlets.dashlet-alarms; type=osgi.bundle; version="[21.1.0.SNAPSHOT,21.1.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.opennms.features.vaadin-dashlets.dashlet-alarms/21.1.0.SNAPSHOT: missing requirement [org.opennms.features.vaadin-dashlets.dashlet-alarms/21.1.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.features.timeformat)(version>=21.1.0)(!(version>=22.0.0)))"]]
```

The problem is, that you added the new `DateTimeService` to module  `features/vaadin-dashlets/dashlet-alarms` but only define the dependency for it in the `pom.xml` of that module. Meaning it is only available during compile/test time. When Karaf is started however, so called `features` are installed and starts each bundle defining that feature. Defining the features is a separate step. To make things a bit more complicated, some of them are defined within a `features-maven-plugin` and some of them are defined in individual `features.xml` files and some of them are defined in an overall `features.xml`  file.

In the case of `dashlet-alarms` it is an individual `features.xml` file. See [vaadin-dashlets/dashlet-features/src/main/resources/features.xml](https://github.com/OpenNMS/opennms/blob/bce7362fa4bf97c275b00155eb73a2594aafafa5/features/vaadin-dashlets/dashlet-features/src/main/resources/features.xml#L9)

An example of the `features-maven-plugin` can be found [here](https://github.com/OpenNMS/opennms/blob/ce76a21384242dcfeb8eb002504c03119435b9b6/features/bsm/vaadin-adminpage/pom.xml#L33). This is deprecated and should no longer be used.

The general/overall features are defined in [container/features/](https://github.com/OpenNMS/opennms/blob/d442ebd9f9af4c4abfdd5aa2068459f7b717c1b8/container/features/src/main/resources/features.xml#L1)

**Comment by patrick-schweizer** [comment]
@mvrueden I added your snippet. But it seems there is still something missing, the feature is not starting. The error log seems to be similar as before:
`patrick@krassomat:/apps/git/opennms_foundation_2017$ grep "org.opennms.features.vaadin-dashlets.dashlet-alarms" -Hir target/opennms-21.1.0-SNAPSHOT/logs
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:14:52,680 INFO  org.apache.karaf.features.core:4.1.5(10) [features-1-thread-1] org.apache.karaf.features.internal.service.FeaturesServiceImpl:       mvn:org.opennms.features.vaadin-dashlets/dashlet-alarms/21.1.0-SNAPSHOT
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:14:53,942 INFO  org.apache.karaf.features.core:4.1.5(10) [features-1-thread-1] org.apache.karaf.features.internal.service.FeaturesServiceImpl:   mvn:org.opennms.features.vaadin-dashlets/dashlet-alarms/21.1.0-SNAPSHOT
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:14:53,945 DEBUG org.opennms.features.vaadin-dashlets.dashlet-alarms:21.1.0.SNAPSHOT(175) [features-1-thread-1] org.opennms.features.vaadin-dashlets.dashlet-alarms: BundleEvent INSTALLED - org.opennms.features.vaadin-dashlets.dashlet-alarms
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:14:55,717 DEBUG org.opennms.features.vaadin-dashlets.dashlet-alarms:21.1.0.SNAPSHOT(175) [features-1-thread-1] org.opennms.features.vaadin-dashlets.dashlet-alarms: BundleEvent RESOLVED - org.opennms.features.vaadin-dashlets.dashlet-alarms
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:14:59,291 INFO  org.apache.karaf.features.core:4.1.5(10) [features-1-thread-1] org.apache.karaf.features.internal.service.FeaturesServiceImpl:   org.opennms.features.vaadin-dashlets.dashlet-alarms/21.1.0.SNAPSHOT
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:14:59,292 DEBUG org.opennms.features.vaadin-dashlets.dashlet-alarms:21.1.0.SNAPSHOT(175) [features-1-thread-1] org.opennms.features.vaadin-dashlets.dashlet-alarms: BundleEvent STARTING - org.opennms.features.vaadin-dashlets.dashlet-alarms
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:14:59,296 INFO  org.apache.aries.blueprint.core:1.8.3(16) [features-1-thread-1] org.apache.aries.blueprint.container.BlueprintContainerImpl: Bundle org.opennms.features.vaadin-dashlets.dashlet-alarms/21.1.0.SNAPSHOT is waiting for dependencies [(objectClass=org.opennms.features.timeformat.TimeformatService)]
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:14:59,297 DEBUG org.opennms.features.vaadin-dashlets.dashlet-alarms:21.1.0.SNAPSHOT(175) [features-1-thread-1] org.opennms.features.vaadin-dashlets.dashlet-alarms: BundleEvent STARTED - org.opennms.features.vaadin-dashlets.dashlet-alarms
target/opennms-21.1.0-SNAPSHOT/logs/karaf.log:2018-07-24T15:19:59,299 ERROR org.apache.aries.blueprint.core:1.8.3(16) [Blueprint Extender: 1] org.apache.aries.blueprint.container.BlueprintContainerImpl: Unable to start blueprint container for bundle org.opennms.features.vaadin-dashlets.dashlet-alarms/21.1.0.SNAPSHOT due to unresolved dependencies [(objectClass=org.opennms.features.timeformat.TimeformatService)]
`

I tried a couple of things to get it running but no luck yet :-( Do you spot the problem? Thanks

**Comment by mvrueden** [comment]
@patrick-schweizer my original suggestion did not work, as the `TimeformatService` is probably going to live in the `jetty-webapps` classloader. Therefore  I modified the code so that the `TimeformatService` can be pulled in by the `alarm-dashelt`, with a slightly different approach.

If you need more information on what I did and why, please contact me at chat.opennms.com and we can go through it in detail.

**Comment by agalue** [comment]
You've chosen a Vaddin hater to provide a review ;)
Support has been crazy, so I'll give it a try next week depending on the work load.

**Comment by patrick-schweizer** [comment]
I close this PR in favor of: https://github.com/OpenNMS/opennms/pull/2080
which is rebased on the current foundation-2018 branch and includes the user specific time zone for time rendering

**Pull request closed without merging**
