### PR TITLE
NMS-8964 / NMS-8639 / NMS-8067: EnhancedLinkd fixes

### PR DESCRIPTION
**Pull request by rssntn67**
This pull request is create for fixing the following bugs for enhanced linkd so that 18.0.3 is released:

NMS-8964: Enlinkd Not Performing Bridge Topology Discovery
https://issues.opennms.org/browse/NMS-8964

NMS-8639: Concurrent Modification Exception Bridge Discovery Topology
https://issues.opennms.org/browse/NMS-8639

NMS-8067: ConstraintViolationException in Enlinkd for OSPF
https://issues.opennms.org/browse/NMS-8067

### CODE REVIEW

**Comment by rssntn67** [comment]
What about merging...anyone wants to review the code?

**Comment by pbrane** [comment]
> On Dec 22, 2016, at 3:38 PM, Antonio Russo <notifications@github.com> wrote:
> 
> What about merging...anyone wants to review the code?

Jake,

Most are on holiday so it might take a while longer than usual but we’ll get to it as soon as possible.  Thank you for working on these issues.


-Elwood

**Comment by rssntn67** [comment]
Elwood. Let's sing together, sweet home chicago.
 The band!

**Comment by rssntn67** [comment]
I have a very good test env...so I'm going to merge branch

**Comment by j-white** [comment]
@rssntn67 these changes triggered a number of merge conflicts from the `release-18.0.3` to the `release-19.0.0` branch. Can you take a look at resolving those? Thanks!

**Comment by rssntn67** [comment]
Sure! I'm checking the code just now!

**Comment by rssntn67** [comment]
just pushed on 19.0.0

MacBook-Pro-di-Antonio-Russo:opennms-services antonio$ git push
Counting objects: 248, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (34/34), done.
Writing objects: 100% (52/52), 6.37 KiB | 0 bytes/s, done.
Total 52 (delta 18), reused 0 (delta 0)
remote: Resolving deltas: 100% (18/18), completed with 18 local objects.
To git@github.com:OpenNMS/opennms.git
   bb28871..1dfcbd9  19.0.0 -> release-19.0.0

**Pull request merged**
