### PR TITLE
NMS-9140: Check permissions on ACKing through ReST

### PR DESCRIPTION
**Pull request by fooker**
* JIRA: http://issues.opennms.org/browse/NMS-9140

### CODE REVIEW

**Comment by mvrueden** [comment]
Why is it tagged as `backport` but the base branch is `develop`? It should probably be merged into `foundation-2017` instead.

**Comment by agalue** [comment]
> On Mar 23, 2017, at 7:09 AM, mvrueden <notifications@github.com> wrote:
> 
> Why is it tagged as backport but the base branch is develop? It should probably be merged into foundation-2017 instead.

I totally agree.

And as a side note, the acks end-point is not the only one that suffers the same permission problem.

**Comment by j-white** [comment]
@agalue can you elaborate on the other REST endpoints you know of that have the same problem?

**Comment by agalue** [comment]
> On Mar 23, 2017, at 8:26 AM, Jesse White <notifications@github.com> wrote:
> 
> @agalue <https://github.com/agalue> can you elaborate on the other REST endpoints you know of that have the same problem?


Absolutely, but as this is a PR for the ACK end-point, I think we should discuss this on Jira (of course, after creating an issue for each end-point with problem, or creating a common Jira issue for all end-points). Let me know what way do you prefer.

**Comment by j-white** [comment]
Okay. Let's focus on the `/acks` endpoint here then.

I'd opt for creating a single issue with the remaining endpoints, and we can then assess if we need to break them out into multiple issues or not.

**Comment by agalue** [comment]
> On Mar 23, 2017, at 8:34 AM, Jesse White <notifications@github.com> wrote:
> 
> Okay. Let's focus on the /acks endpoint here then.
> 
> I'd opt for creating a single issue with the remaining endpoints, and we can then assess if we need to break them out into multiple issues or not.
> 
Perfect!

**Comment by fooker** [comment]
The code has been written against foundation-2017, only the PR was wrong. I changed the PR accordingly.

**Comment by mvrueden** [comment]
You are probably going to kill me, but if this is a security fix, shouldn't this be targeted for `foundation-2016` instead? Or even `foundation`?

**Comment by agalue** [comment]
> On Mar 28, 2017, at 9:51 AM, mvrueden <notifications@github.com> wrote:
> 
> You are probably going to kill me, but if this is a security fix, shouldn't this be targeted for foundation-2016 instead? Or even foundation?


I have to agree with Markus here, as this is indeed a security fix.

In fact, I’m wondering if there is a way to either use the @Secured annotation that Spring Security provides, or even better, enforce security through applicationContext-spring-security.xml for any PUT/POST/DELETE request to make sure that a user should not have ROLE_READONLY, and should have either ROLE_ADMIN or ROLE_REST (or ROLE_PROVISION in terms of the requisitions) in order to perform these queries. That way we can fix ALL the end-points at once, instead of having separate PR like this one for each end-point, because a read-only users should not ack alarms, but it should also be rejected when modifying nodes, delete interfaces, change snmp credentials, modify requisitions, etc.

**Comment by mvrueden** [comment]
If spring does not support what we need, it is very easy to implement our own aspect to enforce our rules.

**Comment by agalue** [comment]
> On Mar 28, 2017, at 9:58 AM, mvrueden <notifications@github.com> wrote:
> 
> If spring does not support what we need, it is very easy to implement our own aspect to enforce our rules
> 
It does, we’re just not using the full capabilities of Spring Security. We can definitively enforce our rules, but if Spring Security was designed for this, why not using it ? In fact, I learnt how to use @Secured with SPEL in Spring 3 years ago.

**Comment by fooker** [comment]
I changed the base to `foundation-2016`. If this should be backported to `foundation`, this needs to be a separate commit / PR.

About the `@Security` annotation: I would prefer to do this in some kind of _Rework ReST  Security_ task.

**Comment by agalue** [comment]
> On Mar 28, 2017, at 10:22 AM, Dustin Frisch <notifications@github.com> wrote:
> I changed the base to foundation-2016. If this should be backported to foundation, this needs to be a separate commit / PR.
> 
Sounds good, as I know that something made for `foundation` cannot be automatically merged to `foundation-2016` or vice versa.
> About the @Security annotation: I would prefer to do this in some kind of Rework ReST Security task.
> 
I’m just trying to save time here, as I was planning to create a Jira issue for each end point that requires a similar treatment but it turns out that any end-point that allows DELETE, POST, PUT will required what you just did with the acks end-point.

So, do you think it worth patching every single end-point individually ? Or, make a solution that covers all of them considering that all share the same access rules ?

I’m good with both, but the second option sounds better.

**Comment by fooker** [comment]
> I’m good with both, but the second option sounds better.
Indeed. Especially, when it comes to security having a good framework and avoiding cumbersome repetition is crucial.

I just want to move the discussion to the overall story issue (can you provide a link to the story for reference?) and proceeding with this PR as it is for now.

**Comment by agalue** [comment]
> On Mar 28, 2017, at 4:54 PM, Dustin Frisch <notifications@github.com> wrote:
> 
> I just want to move the discussion to the overall story issue (can you provide a link to the story for reference?) and proceeding with this PR as it is for now.

You mean, discuss on Jira ?

Here’s what I’m talking about:
http://docs.spring.io/spring-security/site/docs/current/reference/html/el-access.html

The @Secured is an alternative but in code. Although, I prefer doing it on the Spring Security context, because that way the user can alter it according to their needs. Our current solution (and check AlarmRestService as a reference), or @Secured are examples of "hard-coded" solution that will require code changes in order to alter the access.

**Comment by fooker** [comment]
> You mean, discuss on Jira ?
Yup. I want to get the PR closed / merged and would like to avoid to document the discussion about a general solution somewhere in a PR only related to a single endpoint.

**Comment by agalue** [comment]
> On Mar 29, 2017, at 4:08 AM, Dustin Frisch <notifications@github.com> wrote:
> 
> Yup. I want to get the PR closed / merged and would like to avoid to document the discussion about a general solution somewhere in a PR only related to a single endpoint.

Sounds good. As this problem affects all the end-points with POST/PUT/DELETE, I would say close this PR, even close the Jira issue, and then we can create a "generic" issue to cover all the cases at once and discuss the solution there.

**Pull request merged**
