### PR TITLE
NMS-9330: Update a lot of minor dependencies

### PR DESCRIPTION
**Pull request by soleger**
There's nothing really risky here except maybe upgrading ecj since it's used by Drools. This fixes two deps that were dep-managed downward (ehcache and cglib-nodep).

* JIRA: http://issues.opennms.org/browse/NMS-9330

### CODE REVIEW

**Comment by soleger** [comment]
I ended up reverting the ecj upgrade anyway since it was causing some minor problems on a Spring MVC page. :)

**Comment by j-white** [comment]
Are we updating these to address any specific issues?

**Comment by soleger** [comment]
The ehcache, cglib, and ognl changes fix mismatches between JARs we're packaging and what code has been compiled against. Several are projects that have moved to new artifacts and the rest is just housekeeping.

**Comment by soleger** [comment]
Closing until I have time to review the problems in this branch.

**Pull request closed without merging**
