### PR TITLE
NMS-9065: Fixed the Asset pages JSPs to handle ACL filtering

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-9065

### CODE REVIEW

**Comment by agalue** [comment]
Looks good to me, if the karma tests and the smoke tests are passing, go ahead and merge it.

**Comment by agalue** [comment]
IMPORTANT: The Angular version of the asset page is available ONLY on 19. On 18 and older, the GWT version is used. Have you checked both versions ?

**Comment by christianpape** [comment]
I tested it 5min ago and the problem seems also exist with 19. The fix for the asset/nodelist.jsp here will also work for 19. This will prevent the nodes to be listed but if you know the nodeId you can still open the corresponding asset page.

**Comment by christianpape** [comment]
So, the idea is to create a second branch/PR with similar fixes for release-19.0.0. Do you agree?

**Comment by agalue** [comment]
> On Feb 1, 2017, at 10:04 AM, Christian Pape <notifications@github.com> wrote:
> 
> I tested it 5min ago and the problem seems also exist with 19. The fix for the asset/nodelist.jsp here will also work for 19. This will prevent the nodes to be listed but if you know the nodeId you can still open the corresponding asset page.

Excellent!

**Comment by agalue** [comment]
> On Feb 1, 2017, at 10:19 AM, Christian Pape <notifications@github.com> wrote:
> 
> So, the idea is to create a second branch/PR with similar fixes for release-19.0.0. Do you agree?

Makes sense if a patch for 18 doesn’t apply for 19 (because of GWT, or something else).

**Pull request merged**
