### PR TITLE
NMS-6287: [RFC] - Use the same format for confs as opennms writes

### PR DESCRIPTION
**Pull request by luizluca**
Files written by opennms has a different format than
the format that comes from etc-pristine. This generates
unecessary configuration conflits on each upgrade.

This pull request simply let OpenNMS write a bunch of config files and use this result as pristine configuration.

BTW, what is the correct branch to use?

I guess some problems are not only on pristine files but also on opennms xml writer (like the cases where xml header got removed).

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome @luizluca.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @luizluca.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by luizluca** [comment]
BTW, are all "<created>Thursday, December 8, 2016 6:54:51 PM GMT</created>" really necessary?

**Comment by indigo423** [comment]
@luizluca Is it possible to retarget your pull request against branch "develop", which is the next major release version. To get your changes accepted is possible for you to sign our OCA which you can find here: https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md

Thank you very much for your contribution.

**Comment by luizluca** [comment]
The OCA was already resolved. What is the best place to discuss? Jira? Maillist? Github?
The PR conflicts with some collectd and poller changes. I don't know if it is better to just skip them, redo all my work on a develop snapshot. (BTW, https://wiki.opennms.org/wiki/Download is inconsistent and I could not find a binary snapshot)

Maybe instead of trying to fix the config, we can avoid it to become a problem.

@indigo423 , on JIRA I detailed each configuration result after editing on OpenNMS. I have some doubts about what would be the expected XML output, like if it needs to include XML header, castor, etc. It seems that some XML uses a different codepath for building XML. "There can be only one"

It would be nice to have all XML writers to use a common codepath and an external tool that would let devs reformat an XML just like OpenNMS would. Something similar to "xmllint --format" but using OpenNMS conventions (that does not seems to exist). This tool could even become a standard test, avoiding commits that changes pristine configuration which would be reformated by OpenNMS.

So, the steps to fix it definitely that I could see are:
1. What is the correct XML format to use? Why are files written differently?
2. Uniform all file written by OpenNMS to the same format
3. Create a simple tool that reformats XML file and reformat all configs
4. Add an test that tries to reformat all confs and fails if they change.

**Comment by indigo423** [comment]
@luizluca the opennms-discuss mailinglist is the best place to discuss such a topic. I know @agalue spend already some time in doing configuration normalisation. The steps you described are totally right, I can also see something to built into git or bamboo which automatically normalise the XML files with git hooks on commit or Bamboo has a step for XML file normalisation so anyone can do whatever he wants, but as soon it gets committed it gets normalised automatically.

I'm totally with you to get this topic addressed cause it makes configuration merges unnecessarily hard.

**Comment by j-white** [comment]
I think we all agree that we should address this, and we already have some code that will help with the normalization. That said, I'm going to close this PR. We are going to warn users about the upcoming configuration file changes in the release notes for 20.0.0 (see NMS-9401) and make the changes in 21.0.0 (see NMS-6287).

**Pull request closed without merging**
