### PR TITLE
NMS-6284: Make karaf log to ${opennms.home}/logs

### PR DESCRIPTION
**Pull request by mvrueden**
* JIRA: https://issues.opennms.org/browse/NMS-6284

### CODE REVIEW

**Comment by soleger** [comment]
Should we retarget this for foundation-2016? Seems like a good change to have there as well.

**Comment by pbrane** [comment]
+1

**Comment by mvrueden** [comment]
Rebased to `foundation-2016`

**Comment by j-white** [comment]
Do we actually want to start moving logs around in a patch release? Seems more suitable for a major release to me.

**Comment by mvrueden** [comment]
I have no strong opinion about this.

**Comment by mvrueden** [comment]
@jeffgdotorg suggested to put it in `release-19.0.0` and no minor release. Rebasing.

**Pull request merged**
