### PR TITLE
NMS-10602: Fix time format in send-event.py

### PR DESCRIPTION
**Pull request by johnfzc**
* JIRA: http://issues.opennms.org/browse/NMS-10602

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome @johnfzc.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @johnfzc.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by johnfzc** [comment]
I should now be tagged with the OCA, is there a way to trigger a reprocess of this PR?

**Comment by mvrueden** [comment]
Ulf, please recheck the OCA

**Comment by mvrueden** [comment]
Thank you for providing the OCA. I triggered Ulf to recheck the OCA :)

**Comment by j-white** [comment]
Cherry-picked to `foundation-2018`. Thanks @johnfzc!

**Pull request closed without merging**
