### PR TITLE
NMS-12136: Enhance CircleCI workflow to reduce build times and tests

### PR DESCRIPTION
**Pull request by Naicisum**
NMS-12136: Enhance CircleCI workflow to reduce build times and tests
    * Takari Maven Libraries and Makerpm.sh parallel build
    * Enable Takari smart builder for CircleCI build step
    * CircleCI gather build logs from Makerpm.sh parallel build
    * Reconfigure CircleCI package resource size to handle parallelism
    * Modify Makerpm.sh, remove parallelism, add ability to specify spec(s), change CircleCI workflow to allow parallel package builds
    * Reconfigrue CircleCI packes resource size to handle package Takari smart builder
    * CircleCI split tests by timings
    * CircleCI split timing by classname
    * Reconfigure how integration tests are split for CircleCI, change where test results are saved
    * CircleCI disable maven checkstyle profile for integration tests
    * CircleCI increased debugging and minor corrections
    * CircleCI increase debugging and store test generation
    * CircleCI change integration tests maven execution parameters
    * CircleCI change maven execution parameters for integration tests
    * CircleCI add flag failIfNoTests=false to test process
    * CircleCI add flag skipITs=false and change from maven goal from test to verify
    * CircleCI enhance full smoke tests, correct typo in integration tests, speed up opennms.spec logic
    * CircleCI enhance test splitting by limiting scope to used projects
    * CircleCI add debugging and collect additional artifact
    * CircleCI correct order of operations bug for generating projects
    * CircleCI remove debugging and verbosity
    * Ignore opennms-es-rest manual junit tests
    * Move @Ignore labels for opennms-es-rest manual tests
    * Add import org.junit.Ignore to opennms-es-rest manual tests to fix compile error
    * Increase parallelism for integration tests to 12
    * Increase parallelism for smoke full to 10, ignore smoke minimal if full runs
    * Merge package and build steps, remove .git metadata, reduce workspace footptint
    * cleanup smoke script, increase smoke full parallelism to 12
    * Increase optimizations and reduce container sizes while keeping timing improvements
    * Set node memory limits
    * Detect avalilable cpus dynamically and build accordingly
    * Set threads manually due to issue with nproc and CircleCI containers
    * Reduce vaadin localWorkers to match build container CPU count
    * reduce java max memory from 1g to 768m for vaadin widgetset
    * reduce java max mem from 1g to 768m for other vaddin apps
    * Add smart builder back to sentinel and minion matching medium container of 2 vCPUs
    * Variables memory/cpu usage in pom.xml and dependent projects, restructure CircleCI config to use variables dependent on environment
    * Fix typo in config.yml
    * Fix typo in config.yml (again)
    * Remove cpu plugin help, default to 2 if param not passed, update config.yml for CircleCI
    * Fix typo in config.yml (again)
    * Fix typo in project pom.xml (late night brain)
    * Fix typos in minion.spec and create-sentinel-assembly.sh, migrate setting from config.yml to new branch
    * Increase resource_class for package-build tasks
    * set limits for package-build minion/sentinel
    * Add comments to config.yml

NMS-12136: Pass variables into scripts, simplify ignore path test logic
NMS-12136: Correct matching issue for ignore path logic

### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12136
* CircleCI (Continuous Integration): https://circleci.com/workflow-run/1187029d-08bb-448b-9b0d-9688527220e6
* Bamboo (Continuous Integration): https://bamboo.opennms.org/

### CODE REVIEW

**Comment by RangerRick** [comment]
at first glance LGTM

I think integration failed on a flapper in Bamboo, rerunning to be sure.

**Comment by Naicisum** [comment]
> Nice work!
> 
> There's a # of threads hard-coded in a few the packaging scripts i.e. `create-sentinel-assembly.sh`. Can we make these configurable from an env. var or similar instead? (The CircleCI env. isn't the only thing calling these.)

The variables have been inserted with default values if not set.
> 
> The `sed` based scripts used to build the test class names are quite opaque to me, and we now need to maintain the exclusion directories in 3 places (ignore-dir.sed, include-dir.sed & find-tests.py). Is it feasible to port all this logic to the `.py` script instead? This will be easier for us (me) to maintain going forward.

Porting into `py` is a bit more involved so I simply moved the logic to the bash script instead into its own function. It solves maintaining it in several places however it will still require learning some `sed` functionality.

The following sed line `'/^opennms-tools[/,].*/d'` reads as:
If the text `opennms-tools` is at the beginning of the line and the next character matches a `/` or `,` and match all remaining text `.*` then delete `d` the line.

Also fixed minor xml tag issue in one of the pom.xml

**Comment by j-white** [comment]
Changes look good. I just need to find some time to review the test handling a littler closer.

**Comment by j-white** [comment]
All looks good 🚅

**Pull request merged**
