### PR TITLE
Fix doc variable for Docker image version

### PR DESCRIPTION
**Pull request by mmahacek**
### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* JIRA (Issue Tracker): No Jira

### CODE REVIEW

**Comment by mmahacek** [comment]
> LGTM! Thanks!

Was that a comment or an approval?

**Comment by Bonrob2** [comment]
> > LGTM! Thanks!
> 
> Was that a comment or an approval?

Approval. I thought I had clicked Approve. Sorry.

**Review by RangerRick — APPROVED** [review]

**Comment by RangerRick** [comment]
FYI your build failure is an upstream thing, it's OK to merge this without checks being green

**Comment by RangerRick** [comment]
(or you can rebase, it's fixed in 31 now)

**Pull request merged**
