### PR TITLE
NMS-10272: Syslog messages should default to being associated with the hosts from which they were received

### PR DESCRIPTION
**Pull request by mattixtech**
* JIRA: http://issues.opennms.org/browse/NMS-10272

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome @mattixtech.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @mattixtech.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @mattixtech.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @mattixtech.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by j-white** [comment]
Hey Ulf, please recheck the OCA.

**Comment by j-white** [comment]
Thanks Ulf.

**Comment by j-white** [comment]
🎈

**Comment by mattixtech** [comment]
IntelliJ insisted on reformatting some of the code which is why a few lines I didn't touch changed.

**Comment by mvrueden** [comment]
@mattixtech https://wiki.opennms.org/wiki/IDEA_and_OpenNMS (-:

**Comment by mattixtech** [comment]
@mvrueden thanks, I'll go through that.

**Pull request merged**
