### PR TITLE
NMS-7123: Correctly expose SNMP4J noGetBulk property

### PR DESCRIPTION
**Pull request by jeffgdotorg**
Initial commit had a copy-paste error.

### CODE REVIEW

**Comment by agalue** [comment]
Your pull request contains hundreds of changes, even from other people. Could you pleas try again with just your changes ?

**Comment by RangerRick** [comment]
Yeah, I would rebase it against foundation-2016. (git rebase origin/foundation-2016) -- it should rebase cleanly.

**Comment by jeffgdotorg** [comment]
Sorry, I still suck at git. Rebasing.

**Comment by jeffgdotorg** [comment]
Eff it, starting over.

**Pull request closed without merging**
