### PR TITLE
NMS-12122: Remove ugly hack to expose ServiceRegistry

### PR DESCRIPTION
**Pull request by mvrueden**
* JIRA: https://issues.opennms.org/browse/NMS-12122

### CODE REVIEW

**Comment by mvrueden** [comment]
I build this already against develop and CircleCi said is good: https://circleci.com/workflow-run/aa787a51-2d2e-461c-aeea-bc0c0bb45ef3

**Comment by pbrane** [comment]
https://issues.opennms.org/browse/NMS-12122

**Comment by mvrueden** [comment]
As CircleCI already marked these as passing, I merged this manually forward to `develop`, so merging this will end up in `release-24.1.1` (where it should) and automatically merging it to `develop` will pass then as well, which would otherwise have failed (due to new maven bundle with wrong version (`24.1.1-SNAPSHOT` vs `25.0.0-SNAPSHOT`))

**Comment by mvrueden** [comment]
Test passed, I am merging this, even if deploy phase is outstanding.

**Pull request merged**
