### PR TITLE
NMS-13961: Synchronize access to service factories

### PR DESCRIPTION
**Pull request by swachter**
Issue: https://issues.opennms.org/browse/NMS-13961

### CODE REVIEW

**Comment by j-white** [comment]
Should this call be in a synchronized block as well? https://github.com/OpenNMS/opennms/blob/381d32e6688e1c13da587d2e49b169c718addf4b/features/telemetry/registry/src/main/java/org/opennms/netmgt/telemetry/protocols/registry/impl/TelemetryServiceRegistryImpl.java#L86

**Comment by swachter** [comment]
> Should this call be in a synchronized block as well?
> 
> https://github.com/OpenNMS/opennms/blob/381d32e6688e1c13da587d2e49b169c718addf4b/features/telemetry/registry/src/main/java/org/opennms/netmgt/telemetry/protocols/registry/impl/TelemetryServiceRegistryImpl.java#L86

No, it runs during instantiation.

**Review by cgorantla — DISMISSED** [review]

**Review by RangerRick — APPROVED** [review]
approved (but please rebase to `foundation-2019` first)

**Comment by j-white** [comment]
> No, it runs during instantiation.
 d'oh, right, thanks!

**Comment by swachter** [comment]
rebased on `foundation-2019`

**Review by j-white — APPROVED** [review]

**Pull request merged**
