### PR TITLE
NMS-9126: persist string attributes

### PR DESCRIPTION
**Pull request by tdefilip**
- Create a new persistence strategy that only send data to the TCP stream, without any persisting of data to the RRD or other physical database.  This allows us to get rid of persistence code related to DB writing.
- Allow for the new TCP persistence strategy to persist both numeric and string values to the TCP stream.
- Update the performance data protobuf message to hold a lit of double values and a list of string messages.

JIRA: http://issues.opennms.org/browse/NMS-9126

### CODE REVIEW

**Comment by tdefilip** [comment]
Is there any follow-up I need to do?

**Comment by j-white** [comment]
Thanks for the reminder. I'll take a look soon.

**Comment by j-white** [comment]
I pushed this to the `pr/jira/NMS-9126` branch, and it passed in Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1443

This works, but there's a lot of duplicate code with the existing TCP RRD strategies. I'll work on refactoring the solution.

**Comment by j-white** [comment]
@tdefilip, I've cleanup the code a little, and added a unit test in the `features/strings-over-tcp` branch: 
    https://github.com/OpenNMS/opennms/compare/foundation-2016...features/strings-over-tcp

Can you give this a whirl and confirm it works as expected? If so, I'll close this PR and open a new one from that branch. I also opted to revert the changes made in NMS-9120, since this update supersedes that functionality.

**Comment by tdefilip** [comment]
OK, I'll give it a look.  What are the git commands to be able to get that branch locally?

**Comment by j-white** [comment]
You can give this a try:
```
git checkout -b strings-over-tcp foundation-2016
git pull https://github.com/OpenNMS/opennms.git features/strings-over-tcp
```

**Comment by tdefilip** [comment]
Thanks!  I've tested your changes and everything works as expected.  All clear on my end.

**Comment by j-white** [comment]
Closing in favor of https://github.com/OpenNMS/opennms/pull/1410.

**Pull request closed without merging**
