### PR TITLE
NMS-10199:  multi-trend-box

### PR DESCRIPTION
**Pull request by mmahacek**
Extension of single-trend-line to display a 2x2 grid.

NMS-10199: Extend single-trend-box.jsp to display 4 trends

* JIRA: https://issues.opennms.org/browse/NMS-10199

### CODE REVIEW

**Comment by j-white** [comment]
Looks reasonable. How will users know that this exists?

**Comment by mmahacek** [comment]
That is a good question. I didn’t realize that the single-trend-line was even available until I started poking Around in the code. Could be something to add to the new documentation.

**Comment by mmahacek** [comment]
Okay, so I found the end of the Trend documentation has a brief blurb about using single-trend-box.jsp

**Comment by mvrueden** [comment]
The single trend line page may be used for debug/development purposes only. I'd ask @christianpape to ensure that the feature should be used. @christianpape, @fooker  any input on this?

**Comment by christianpape** [comment]
Looks good for me. Please add a few words to https://github.com/OpenNMS/opennms/blob/release-22.0.1/opennms-doc/guide-admin/src/asciidoc/text/webui/trend/introduction.adoc
so other user will also benefit from these changes.

**Comment by mmahacek** [comment]
I was trying something out, and didn't check my local branch when committing.  Only the "Adding Use Case Text" commit actually has changes to the documentation.

**Pull request closed without merging**
