### PR TITLE
NMS-13772: add file editor view, logs view

### PR DESCRIPTION
**Pull request by mikewrosey**
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13772

### CODE REVIEW

**Comment by j-white** [comment]
Edit files:
image

XML validation:
image

**Comment by j-white** [comment]
I'm not sure if this is something we will want to keep when we cut Horizon 30 next year, and whether or not we want to support this an actual feature. I do believe however that it would be very helpful to have in the tree while we develop and continue to make progress on the new UI.

I'm good to merge this, with the intent of revisiting it later in the release cycle and making a final decision then. What do other folks think?

**Comment by dino2gnt** [comment]
I think a hard cutover from "config files I can view and edit" to "everything is in the database and you configure it with some radio buttons and checkboxes :smirk:" is uncomfortably abrupt, and having an editor available in the UI is a good transitory step.

**Comment by indigo423** [comment]
well done @mikewrosey pretty rad :)

**Comment by RangerRick** [comment]
> I'm not sure if this is something we will want to keep when we cut Horizon 30 next year, and whether or not we want to support this an actual feature. I do believe however that it would be very helpful to have in the tree while we develop and continue to make progress on the new UI.

This seems like good insurance against the case that some config _isn't_ converted over yet by H30...

> I'm good to merge this, with the intent of revisiting it later in the release cycle and making a final decision then. What do other folks think?

Seems reasonable to me.

**Review by RangerRick — DISMISSED** [review]

**Review by j-white — APPROVED** [review]

**Review by j-white — APPROVED** [review]

**Comment by cgorantla** [comment]
This looks awesome. Great work @mikewrosey !

**Comment by mikewrosey** [comment]
thanks @indigo423 and @cgorantla !

**Pull request merged**
