### PR TITLE
NMS-13481: Reload interface-to-node cache non-blocking

### PR DESCRIPTION
**Pull request by fooker**
By re-building the cache without locking, the enrichment process can
continue to work while a re-build is inprocess.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13481

### CODE REVIEW

**Review by j-white — COMMENTED** [review]
Looks good to me. `dataSourceSync` is called in `init`, so calls won't be made until the cache is synchronized, and then subsequent refreshes will happen in the background.

**Review by christianpape — APPROVED** [review]
LGTM.

**Comment by RangerRick** [comment]
Should this go back to `release-28.x` or even `foundation-2021` if it applies?

**Comment by RangerRick** [comment]
Green!  Ship it! 🚀

**Pull request merged**
