### PR TITLE
HZN-1276: Updated Elasticsearch Template for Events

### PR DESCRIPTION
**Pull request by Naicisum**
* JIRA: http://issues.opennms.org/browse/HZN-1276

### CODE REVIEW

**Comment by j-white** [comment]
Pushed to `pr/jira/HZN-1276` to run it through Bamboo.

**Comment by j-white** [comment]
The tests for Elasticsearch 5 are failing with these changes. See https://bamboo.opennms.org/browse/OPENNMS-ONMS2122-SMOKE-1

**Comment by Naicisum** [comment]
PR1903 is a dependency, not only from the new p_oids mapping, but also depends on correctly parsing and structuring the JSON. I would recommend updating this branch against current drift and retesting.

**Comment by j-white** [comment]
I merged the latest `features/drift` into `pr/jira/HZN-1276` so that the tests get triggered again.

**Comment by j-white** [comment]
Closing this since the solution needs to be revised - either we need to support templates for multiple versions or drop support for earlier versions of ES.

**Pull request closed without merging**
