### PR TITLE
NMS-9878, NMS-9879, NMS-9880, NMS-9883: Various Classification UI fixes

### PR DESCRIPTION
**Pull request by mvrueden**
This PR addresses a few minor fixes in the Classification UI.
As they are so minor, I grouped them all together in one PR, separated by commits.

JIRA:
* https://issues.opennms.org/browse/NMS-9878
* https://issues.opennms.org/browse/NMS-9879
* https://issues.opennms.org/browse/NMS-9880
* https://issues.opennms.org/browse/NMS-9883

### CODE REVIEW

**Comment by j-white** [comment]
@indigo423 identified most of these, so I'd look for his input here.

**Comment by RangerRick** [comment]
@indigo423, you want to test this out? Or should I go ahead and merge it?

**Comment by indigo423** [comment]
I try several branches and to avoid problems, I have to cleanup .m2 and a built just sucks hours of my life. Additionally I ran in some errors like this which force me to try things again and again. To test things I would really like to have docker image as build artifact from bamboo from a branch like this here.

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.apache.maven.wagon:wagon-ssh-external:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.wagon:wagon-ssh-external:jar:2.6 @
[ERROR] Non-resolvable import POM: Could not transfer artifact org.apache.logging.log4j:log4j-bom:pom:2.8.2 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org @ line 3801, column 19
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.opennms:opennms:22.0.0-SNAPSHOT (/usr/src/opennms/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.maven.wagon:wagon-ssh-external:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.wagon:wagon-ssh-external:jar:2.6: Could not transfer artifact org.apache.maven.wagon:wagon-ssh-external:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known: Unknown host repo.maven.apache.org: Name or service not known -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.apache.logging.log4j:log4j-bom:pom:2.8.2 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org @ line 3801, column 19: Unknown host repo.maven.apache.org -> [Help 3]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
[ERROR] [Help 3] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by RangerRick** [comment]
Looks like you've got a very wrong URL for the repofile.  It should be something like `https://yum.opennms.org/repofiles/opennms-repo-branches-features-classification-ui-fixes-rhel7.noarch.rpm`

I have no idea how the docker stuff looks for repo files so I can't really help there.

**Comment by indigo423** [comment]
Link fixed but this is now the error

```
Error: Package: opennms-core-22.0.0-0.20180220.onms2063.features.classification.ui.fixes.2.noarch (opennms-repo-branches-features-classification-ui-fixes-common)
           Requires: jicmp6 >= 2.0.0
           Available: jicmp6-1.2.1-1.i386 (opennms-repo-branches-features-classification-ui-fixes-rhel7)
               jicmp6 = 1.2.1-1
Error: Package: opennms-core-22.0.0-0.20180220.onms2063.features.classification.ui.fixes.2.noarch (opennms-repo-branches-features-classification-ui-fixes-common)
           Requires: jicmp >= 2.0.0
           Available: jicmp-1.4.1-1.i386 (opennms-repo-branches-features-classification-ui-fixes-rhel7)
               jicmp = 1.4.1-1
```

**Comment by RangerRick** [comment]
same issue we've always had, until I can someday finish my repo tools, always install both the stable and branch repo RPMs when working with branches

**Comment by indigo423** [comment]
Verified on Version: 22.0.0-0.20180220.onms2063.features.classification.ui.fixes.2 from https://hub.docker.com/r/opennms/horizon-core-web/tags/ used tag classification-ui-fixes.

* NMS-9878: Approved
* NMS-9879: Approved
* NMS-9880: Approved
* NMS-9883: Approved

**Pull request merged**
