### PR TITLE
OIA-37: Update OIA eventconf to support event-sourced data collection

### PR DESCRIPTION
**Pull request by freddy61025**
https://issues.opennms.org/browse/OIA-37

### CODE REVIEW

**Review by cgorantla — APPROVED** [review]

**Comment by Bonrob2** [comment]
Hmm. wonder why this was tagged with a docs label.

**Comment by freddy61025** [comment]
> Hmm. wonder why this was tagged with a docs label.

I also don't understand. I have removed you when I notice that.

**Comment by Bonrob2** [comment]
> > Hmm. wonder why this was tagged with a docs label.
> 
> I also don't understand. I have removed you when I notice that.

Thanks. I got the email notification, added myself as a reviewer, then saw there were no doc files, so removed myself. Not a big deal, just odd.

**Comment by cgorantla** [comment]
> > Hmm. wonder why this was tagged with a docs label.
> 
> I also don't understand. I have removed you when I notice that.

before rebase you may have commits that have doc updates, now they don't is my understanding.

**Comment by cgorantla** [comment]
LGTM ! 
I guess you have to move it back to `1.0.0-SNAPSHOT`.

**Comment by freddy61025** [comment]
> LGTM ! I guess you have to move it back to `1.0.0-SNAPSHOT`.

Sure. I am waiting OIA side to merge first.

**Review by cgorantla — APPROVED** [review]

**Pull request merged**
