### PR TITLE
LTS-213: backport ticketer fixes from foundation-2017

### PR DESCRIPTION
**Pull request by RangerRick**
This PR backports the recent fix for a long-standing bug in vacuumd config because ticket state numbers changed sometime back in the murky past.

* JIRA: http://issues.opennms.org/browse/LTS-213

### CODE REVIEW

**Comment by agalue** [comment]
Any thought about the conflicts ?

**Comment by agalue** [comment]
`develop` ? I would expect `foundation-2016`

**Comment by RangerRick** [comment]
oops, good catch, always forget to change that  :)

**Comment by RangerRick** [comment]
Erp, I wonder if I accidentally pushed to the wrong branch, because these changes are already in `foundation-2016`.  *shrug*  Marking as closed, I guess.

**Pull request closed without merging**
