### PR TITLE
Fixed a typo in the BSM introduction documentation page

### PR DESCRIPTION
**Pull request by StCyr**
Hi,

This is small documentation update that doesn't require a JIRA issue imho.

Cheers,

Cyrille

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome Cyrille Bollu (cyrille@bollu.be).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Cyrille Bollu (cyrille@bollu.be).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by StCyr** [comment]
or maybe you can update my email address? ;-)

**Comment by mvrueden** [comment]
Hey Ulf, please approve cyrille@bollu.be as StCyr.

**Comment by mvrueden** [comment]
Ulf can you please recheck the contributors OCA?

**Comment by opennms-bamboo** [comment]
Welcome Cyrille Bollu (cyrille@bollu.be).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Cyrille Bollu (cyrille@bollu.be).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Pull request merged**
