### PR TITLE
NMS-15419: Update JDBC collection definition and graphs

### PR DESCRIPTION
**Pull request by mmahacek**
### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15419

### CODE REVIEW

**Review by ProjectJYL — APPROVED** [review]
Verified these by dropping into my Horizon 31 instance. I can see the data being collected and the graphs are displayed accordingly. It's working as expected.

**Comment by garcia-sr** [comment]
Meant to comment on this, but it works for me as well. Data collection is working.

**Review by garcia-sr — COMMENTED** [review]
LGTM

**Review by garcia-sr — COMMENTED** [review]
LGTM

**Pull request merged**
