### PR TITLE
NMS-16219: Remove plugin 'opennms-cloud-plugin' from installation

### PR DESCRIPTION
**Pull request by mershad-manesh**
### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16219

### CODE REVIEW

**Review by RangerRick — APPROVED** [review]

**Comment by indigo423** [comment]
@mershad-manesh @RangerRick The issue doesn't explain how to deal with some leftovers in Horizon which are the docs and we have some functionality in the Web UI that allows us to configure the plugin as well. Do we want to carry that along?

**Comment by indigo423** [comment]
> @mershad-manesh @RangerRick The issue doesn't explain how to deal with some leftovers in ~Horizon~ Meridian docs. Do we want to carry that along?

Seems like we provide the docs just in Meridian: https://github.com/OpenNMS/opennms/blob/develop/docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc

**Comment by cbialowas-onms** [comment]
Ronny, we discussed removal of docs for these changes as well and Bonnie will do that. I am not sure if it is tracked in a separate issue yet or not. @Bonrob2

**Comment by mershad-manesh** [comment]
> > @mershad-manesh @RangerRick The issue doesn't explain how to deal with some leftovers in ~Horizon~ Meridian docs. Do we want to carry that along?
> 
> Seems like we provide the docs just in Meridian: https://github.com/OpenNMS/opennms/blob/develop/docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc

Updating docs will be handled in a different issue (NMS-16231)

**Pull request merged**
