### PR TITLE
NMS-16167: Only display data of matching Collectd-package

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://opennms.atlassian.net/browse/NMS-16167

### CODE REVIEW

**Review by synqotik — APPROVED** [review]
Looks reasonable to me.

**Comment by christianpape** [comment]
> While the collection package is fixed, it looks like there was a reversion on the service parameters sections. (also may want to touch copyright dates at the top of the file) This patch: image
> 
> From a stock 32.0.5: image

I rebased to a release-31.x. Now this should look similar.

**Review by mmahacek — DISMISSED** [review]
Works and looks great! (tested on a 32.0.5 instance)

**Comment by mmahacek** [comment]
Can we update 2023 with the same version of this file too?  I just tested the `service.jsp` on a 2023.1.9 instance, and it works for displaying the correct collectd package as well as collectd service parameters.

**Comment by christianpape** [comment]
> Can we update 2023 with the same version of this file too? I just tested the `service.jsp` on a 2023.1.9 instance, and it works for displaying the correct collectd package as well as collectd service parameters.

done.

**Review by synqotik — APPROVED** [review]

**Pull request merged**
