### PR TITLE
NMS-10301: expose datetimeformat in InfoService REST Endpoint

### PR DESCRIPTION
**Pull request by patrick-schweizer**
* JIRA: https://issues.opennms.org/browse/NMS-10301

Please do not merge yet: This branch contains as well the changes from https://github.com/OpenNMS/opennms/pull/2080 (NMS-10268 render dateformat for Vaadin). I will rebase to foundation-2018 once NMS 10268 is merged.

@RangerRick you will need this endpoint to get the zoneId and format information to the client, for:
* https://issues.opennms.org/browse/NMS-10232 and
* https://issues.opennms.org/browse/NMS-10233
Could you check if the endpoint gives you the necessary information?

Example output:

```
{

    "displayVersion": "21.1.0-SNAPSHOT",
    "version": "21.1.0",
    "packageName": "opennms",
    "packageDescription": "OpenNMS",
    "ticketerConfig": {
        "plugin": null,
        "enabled": false
    },
    "datetimeformatConfig": {
        "zoneId": "America/St_Lucia",
        "datetimeformat": "yyyy-MM-dd'T'HH:mm:ssxxx"
    }

} 
```
Thanks!

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by RangerRick** [comment]
This  seems mostly reasonable to me. The only question I really have is: why add the APIs marked `@Deprecated` when this is a new API?  Anyone that needs to pass a Date in can just do `.toInstant()` anyways...

**Comment by mvrueden** [comment]
@christianpape can you verify that all the places in the Dashboard, Opsboard, Wallboard and Surveillance View (and the Vaadin applications you worked on) are covered?

**Comment by christianpape** [comment]
Seems to work fine in Dashboard, Surveillance View, Wallboard and OpsBoard.

**Comment by patrick-schweizer** [comment]
close and reopen to retrigger build

**Comment by patrick-schweizer** [comment]
rebased to current foundation-2018

**Comment by RangerRick** [comment]
Looking good to me.  I'm starting work on the Angular bit so I'll give it a real workout soon. :)

**Pull request merged**
