### PR TITLE
NMS-13173: Add operator instructions for graphInvalidated

### PR DESCRIPTION
**Pull request by mfuhrmann**
### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [x] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13173

### CODE REVIEW

**Comment by mfuhrmann** [comment]
Argh. @RangerRick Should I have picked `release-27.x`?

**Comment by mfuhrmann** [comment]
> Argh. @RangerRick Should I have picked `release-27.x`?

Can you please change it here to `release-27.x`; too?

**Review by christianpape — APPROVED** [review]
Ok

**Comment by jeffgdotorg** [comment]
I think we should leave `operinstruct` empty / absent and instead put the additional tip in the event's `descr` element.

**Comment by mfuhrmann** [comment]
@jeffgdotorg That's not absolutely true :see_no_evil: since I've added for example this one in past: https://github.com/OpenNMS/opennms/blob/a4691a07ced525c02a858b2829d43633a4f23f1e/opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml#L302 
The only reason why I am doing it like this is to be able to use them in notifications with `%operinstruct%`. If you have ONMS event-related "operator instructions" in the `descr` field and your custom events operator instructions in the `operinstruct` field we will never be able to use these mixed concepts in notifications. I wanted to avoid breaking this notification concept.
Putting the information in `operinstruct` does not break an existing concept afaik.

**Review by agalue — APPROVED** [review]
No strong opinion as I don't use BSM, but assuming that link is always valid no matter what and always works, it looks good to me.

**Pull request merged**
