### PR TITLE
NMS-12261: use backwards-compatible date serialization

### PR DESCRIPTION
**Pull request by RangerRick**
### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12261
* Bamboo (Continuous Integration): https://bamboo.opennms.org/

### CODE REVIEW

**Comment by j-white** [comment]
No problems in setting these flags when still using JDK 8?

Ideally we'd solve this in the code instead of having to set these flags everywhere, but it looks like that's captured in NMS-12263.

We also need to update: https://github.com/OpenNMS/opennms/blob/develop/opennms-container/horizon/assets/entrypoint.sh#L168

**Comment by RangerRick** [comment]
> No problems in setting these flags when still using JDK 8?

Hmm, good point.  Looks like JDK8 expects "JRE" and "CLDR" rather than "COMPAT" and "CLDR".  In JDK 11 they say:

`JRE: Represents a synonym to "COMPAT". This name is deprecated and will be removed in the future release of JDK.`

:/

Guess I should version-box them in the other scripts too.

> Ideally we'd solve this in the code instead of having to set these flags everywhere, but it looks like that's captured in NMS-12263.

Yeah, this is a short-term fix.  Long-term we need to make sure we can be forgiving of our inputs before CLDR becomes the default.

> We also need to update: https://github.com/OpenNMS/opennms/blob/develop/opennms-container/horizon/assets/entrypoint.sh#L168

Ooh, good catch.  Missed this one.

**Comment by RangerRick** [comment]
I just committed something that handles this, but it got real complicated.  I think I can do it in a simpler way, so marking as triage for now.  Don't bother reviewing until I've released it.

**Comment by j-white** [comment]
This is starting to looks like its more work than actual fixing the date formats.

**Comment by RangerRick** [comment]
Well, I was trying to reuse the code for getting the java version, which can get complicated across JDK/OpenJDK/betas/etc.  Breaking some of this out is actually something I'd been meaning to do for a while, this was just the trigger.  :)

**Comment by RangerRick** [comment]
Alright, I made [NMS-12266](http://issues.opennms.org/browse/NMS-12266) to track the actual base changes for the CLI module.  That simplifies _this_ patch immensely.  I went ahead and rebased it against `NMS-12266`, cleaned it up, and force-pushed it, because things had changed so much.

I'll wait for `NMS-12266` to finish and confirm it doesn't break anything, and then un-triage this after it at least passes circle.  (If it does. <grin>)

**Comment by RangerRick** [comment]
OK, this is the simplistic version that just changes OpenNMS to `COMPAT` but _not_ anything else.  All the tests pass, and it should be the most minimal version of this, but ultimately I think post-25 updating all our dates to be ISO-8601 is better and the previous patch should be revisited for [NMS-12263](https://issues.opennms.org/browse/NMS-12263).

**Comment by j-white** [comment]
We still need to update the start script for the container: https://github.com/OpenNMS/opennms/blob/bd4bd561276b389008ccaf5251acd13dd4bac50e/opennms-container/horizon/container-fs/entrypoint.sh#L134

Without this, I believe that the Docker container (& system tests) won't run with the new flag.

**Comment by RangerRick** [comment]
D'oh, good catch.  Cleaned that out when I pulled the other bits.  Guess *now* we'll see what happens...  :)

**Comment by RangerRick** [comment]
Ah good, looks like it still passes in circle with that change: https://github.com/OpenNMS/opennms/pull/2673

**Comment by RangerRick** [comment]
Closing this PR for now, I'm working on it under NMS-12263 anyway.

**Pull request closed without merging**
