### PR TITLE
Fix/docs build warnings

### PR DESCRIPTION
**Pull request by indigo423**
Fix the following doc build warnings:

```
asciidoctor: WARNING: skipping reference to missing attribute: minion_home
asciidoctor: WARNING: skipping reference to missing attribute: opennms_home
asciidoctor: WARNING: HostResourceSWRunDetector.adoc: line 11: section title out of sequence: expected level 1, got level 3
asciidoctor: WARNING: HostResourceSWRunDetector.adoc: line 18: section title out of sequence: expected level 1, got level 3
asciidoctor: WARNING: HostResourceSWRunDetector.adoc: line 28: section title out of sequence: expected level 1, got level 3
```

### CODE REVIEW

**Review by Bonrob2 — APPROVED** [review]
LGTM! Thanks.

**Review by Bonrob2 — APPROVED** [review]
LGTM!

**Comment by mmahacek** [comment]
I've got fixes for these queued up in https://github.com/OpenNMS/opennms/pull/3539 and https://github.com/OpenNMS/opennms/pull/3521

**Comment by indigo423** [comment]
> I've got fixes for these queued up in #3539 and #3521 (both of which are ready for review)
> 
> Can either merge this and I'll back out the corresponding changes from my PRs, or cancel this one and this will be resolved when merging the other two. Your call.

It's all yours :) Thanks for taking care!

**Pull request closed without merging**
