### PR TITLE
NMS-15340: Ensure thresholding session creation is done in transaction

### PR DESCRIPTION
**Pull request by fooker**
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15340

### CODE REVIEW

**Comment by dino2gnt** [comment]
This should target `foundation-2023`, no?

**Review by aramosvizcarra — COMMENTED** [review]
looks like there is a reference missing. I get the same error as CircleCI when copmpiling the project.

**Comment by fooker** [comment]
> looks like there is a reference missing. I get the same error as CircleCI when copmpiling the project.

Stupid rebasing error. Fixed.

**Review by christianpape — APPROVED** [review]
LGTM.

**Review by aramosvizcarra — APPROVED** [review]

**Pull request merged**
