### PR TITLE
JIRA 7817: Add %foreignsource% to event util expansion.

### PR DESCRIPTION
**Pull request by roskens**
JIRA issue NMS-7817 asked to have the provisioning requisition added as an expansion in notifications.

### CODE REVIEW

**Comment by roskens** [comment]
This isn't ready for merging. The bamboo build failed.

**Comment by mvrueden** [comment]
Hey Ron, please add a link to jira and bamboo.
Thanks.

**Comment by roskens** [comment]
JIRA: http://issues.opennms.org/browse/NMS-7817
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS106-2

Bamboo is green for this build. I'd like to verify this works though by installing the built rpms.

**Comment by agalue** [comment]
I know the initial request doesn't have it, but the foreignId might be useful as well, as it could be the ID on the CMDB or the inventory server used to populate the requisitions. Unfortunately, having both options will force the EventUtil implementation to execute 2 SQL queries.

**Comment by mvrueden** [comment]
As Alejandro suggested I added support for `foreignId` as well. In addition I changed the commit comments to have `NMS-7817: ` as a prefix.

**Comment by mvrueden** [comment]
The original bamboo build was deleted by bamboo. I manually added it again. 
The new URL is listed below:
 * JIRA: http://issues.opennms.org/browse/NMS-7817
 * Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS171

**Pull request merged**
