### PR TITLE
NMS-8635: Added an ImapsDetector and a ImapsMonitor

### PR DESCRIPTION
**Pull request by StCyr**
Hi,

Here's a contribution for an ImapsMonitor and an ImapsDectector.

It's not yet OK to merge but should be close enough for it being worth you have a look.

1) Tested on my 18.0.1: Detector worked but Monitor had an issue using the correct port (was still using 143 rather than 993).
2)  I made the necessary changes and recompiled it, but haven't had the time to test it yet.
3) If you're OK to accept this new monitor, it will also have to document it (shouldn't be a problem: I would almost just have to copy/paste HttpsMonitor's documentation)

* JIRA: http://issues.opennms.org/browse/NMS-8635
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS910-1

### CODE REVIEW

**Comment by StCyr** [comment]
Ok, I've just tested it on my 18.0.1 development box and it works as expected.

If you're willing to accept this monitor, I'll proceed with the documentation, and any other improvement/adjustement you might like.

Cyrille

**Comment by j-white** [comment]
The code changes look good to me. I think all we're missing here is an update to the docs.

**Comment by StCyr** [comment]
Ok, I've created the doc for the ImapsMonitor.

I'be also fixed 2 typos in other parts of the doc (https://github.com/OpenNMS/opennms/pull/953/commits/e4ae0425265eac9165dfad65cc58b94eeea1fe32 and https://github.com/OpenNMS/opennms/pull/953/commits/b179299578b82ab11173cec36aa6a0709a1e2dad)

I don't see anything else to do.

**Comment by j-white** [comment]
I've pulled this in to the `pr/NMS-8635` branch. Waiting on Bamboo.

**Comment by j-white** [comment]
We recently changed the way detectors are wired in, so I went ahead and updated the code in the `pr/NMS-8635` branch to reflect this. We should be good to merge this soon.

**Comment by j-white** [comment]
Manually merged to develop.

**Pull request closed without merging**
