### PR TITLE
NMS-13034: Expose telemetryd metrics with full names

### PR DESCRIPTION
**Pull request by fooker**
Build and expose metrics in telemetryd for parsers and adapters using a
unique, full qualified name. The name is build using the parent element
to allow duplicated names in parsers and adapters.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13034

### CODE REVIEW

**Review by christianpape — APPROVED** [review]
LGTM

**Comment by RangerRick** [comment]
Should this branch be a `-smoke` one so it runs through the full test suite?  Or do you think the `SinglePortFlowsIT` is enough to be sure this didn't break anything?

**Comment by fooker** [comment]
> Should this branch be a `-smoke` one so it runs through the full test suite? Or do you think the `SinglePortFlowsIT` is enough to be sure this didn't break anything?

full smoke test: https://app.circleci.com/pipelines/github/OpenNMS/opennms?branch=jira%2FNMS-13034-smoke

**Review by RangerRick — APPROVED** [review]

**Comment by cgorantla** [comment]
May be it's good to update `telemetryd-configuration.xml` in smoke-test overlay to have two listeners with the same parser just to make sure that it works.

**Comment by RangerRick** [comment]
So the tests are failing, and it appears there's probably another place that requires us to change `threshd-configuration.xml` -- but that means we're breaking this in a micro-release in a way that requires users to encode the queue name into their config, is that correct?  Is there a way to do this that hides it from the configs and just does it internally?

**Pull request merged**
