### PR TITLE
NMS-13865: Set version number for docs to the major version

### PR DESCRIPTION
**Pull request by indigo423**
Publish only docs for the major version number.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13865

### CODE REVIEW

**Comment by RangerRick** [comment]
this needs to be done against the `release-29.x` branch, "master" never gets merged anywhere, and it's not a source of truth (`master-29` is)

(we could call it `29-SNAPSHOT` there)

**Review by Bonrob2 — APPROVED** [review]
Looks good to me, once Ben's comment is addressed.

**Comment by indigo423** [comment]
@RangerRick renamed to 29-SNAPSHOT and changed base to release-29.x

**Review by RangerRick — APPROVED** [review]

**Comment by RangerRick** [comment]
👍 

once this is merged, I'll make the equivalent change in `master-29` (and `master`) so that we can trigger the stuff from https://github.com/OpenNMS/docs.opennms.com/pull/14 before next month's releases.

**Comment by indigo423** [comment]
@RangerRick the merge button is blocked, the approved buttons need to be pressed :)

**Review by RangerRick — APPROVED** [review]
oops, all good :)

**Pull request merged**
