### PR TITLE
NMS-9855: Fix asset record not having a node id when creating via REST

### PR DESCRIPTION
**Pull request by mvrueden**
* JIRA: https://issues.opennms.org/browse/NMS-9855

### CODE REVIEW

**Comment by mvrueden** [comment]
@RangerRick why was this PR closed? I was still working on it. Only thing which needs doing is fix problems and rebase against foundation. Please enlighten me.

**Comment by j-white** [comment]
The `release-21.0.4` branch was deleted, and all PRs targeting this branch we're automatically closed.

**Comment by mvrueden** [comment]
I reopend the PR and retargeted it to `foundation-2017`.

**Comment by mvrueden** [comment]
Created new PR https://github.com/OpenNMS/opennms/pull/1873 as I cannot reopen this somehow.

**Pull request closed without merging**
