### PR TITLE
NMS-8200 only try `ulimit -n` if it would raise the number of filehandles

### PR DESCRIPTION
**Pull request by RangerRick**
This patch changes the `$OPENNMS_HOME/bin/install` script to only attempt a `ulimit -n` call to raise the ulimit if the number is higher than the current value.

* JIRA: http://issues.opennms.org/browse/NMS-8200
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS859

### CODE REVIEW

**Comment by soleger** [comment]
Why does this PR have 2 commits in it? It looks like the bugfix is just commit c664648c66fb25f09ad4e8ed60237f87af3d365d.

**Comment by agalue** [comment]
I agree with @soleger. It seems like you're accidentally including a fix that is already merged into foundation-2016, unless you're changing the Hardware Inventory Provisioning Adapter here ;)

**Comment by RangerRick** [comment]
Oh, it's because I made the PR against `develop`, rather than `foundation`.  >_<  I guess that commit made it to foundation but hasn't made it to develop (or got fixed/cherry-picked over).

**Comment by RangerRick** [comment]
https://github.com/OpenNMS/opennms/pull/913

**Pull request closed without merging**
