### PR TITLE
NMS-13997: Fixed SnmpDetector parameters

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-13997

### CODE REVIEW

**Review by RangerRick — APPROVED** [review]
Nice one.  Is there a potential this would apply to `foundation-2021` too?  (OK if it doesn't, just wondering if it's a useful backport.)

**Review by cgorantla — COMMENTED** [review]
This was introduced to work with both Discovery and Provisiond, does this still work with discovery configuration ?

**Comment by christianpape** [comment]
> Nice one. Is there a potential this would apply to `foundation-2021` too? (OK if it doesn't, just wondering if it's a useful backport.)

Rebased it to foundation-2021.

**Comment by christianpape** [comment]
> This was introduced to work with both Discovery and Provisiond, does this still work with discovery configuration ?

Changed the properties to String values.

**Review by cgorantla — APPROVED** [review]

**Review by RangerRick — APPROVED** [review]

**Pull request merged**
