### PR TITLE
jira/NMS-7620

### PR DESCRIPTION
**Pull request by christianpape**
Please review:

http://issues.opennms.org/browse/NMS-7620

### CODE REVIEW

**Comment by pbrane** [comment]
> On Apr 23, 2015, at 4:14 AM, Christian Pape <notifications@github.com> wrote:
> 
> Added right panel to jump to the several dashboard sections

I didn’t see a right panel after my build of your branch, this a.m.

David

**Comment by pbrane** [comment]
I built again, today, just to be sure and I verified that the right panel is not there.

**Comment by pbrane** [comment]
image

**Comment by christianpape** [comment]
I've built it on another machine today and it worked.

**Comment by fooker** [comment]
Works for me, too.

**Comment by pbrane** [comment]
I’m not sure what I could be doing incorrectly.  I tried clearing browser cache and still nothing.  The property setting works fine to prove I’m running this build.

**Comment by pbrane** [comment]
Going to merge this for it works for me.  The only thing I would imagine is that a bit of styling shrink the right margin is needed.

**Comment by pbrane** [comment]
I was building 7619.  Works for me, too, now.
\(‾▿‾\)

David

**Pull request merged**
