### PR TITLE
NMS-15199: bump jettison transient feature dep to 1.4.1

### PR DESCRIPTION
**Pull request by RangerRick**
This PR updates jettison to 1.4.1. 1.5.3 is technically out but bumping it makes overriding things more complicated.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15199

### CODE REVIEW

**Comment by jeffgdotorg** [comment]
This change set looks minimally invasive to me, but I'm not familiar with the implications of changing the `start-level` of a bundle. I'm happy to sign off provided one of the other reviews is on board.

**Review by jeffgdotorg — COMMENTED** [review]
This change set looks minimally invasive to me, but I'm not familiar with the implications of changing the `start-level` of a bundle. I'm happy to sign off provided one of the other reviews is on board.

**Comment by RangerRick** [comment]
The `start-level` changes just exist to match the one used in the CXF feature bundles. Default `start-level` of Karaf internal stuff is mostly in the 1-30 range, with 30 being the most common general startup level.

**Review by christianpape — DISMISSED** [review]
LGTM.

**Review by amay94 — APPROVED** [review]

**Pull request merged**
