### PR TITLE
HZN-933: Fix transaction-per-EventLog inside HibernateEventWriter

### PR DESCRIPTION
**Pull request by soleger**
The logging changes in 19ee8497d5cacc4343c2ba5ce6f2dc59645ca6e1 busted the @Transactional behavior in HibernateEventWriter because the annotation moved to a private method. This fixes the problem by using TransactionOperations.

* JIRA: http://issues.opennms.org/browse/HZN-933
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1158

### CODE REVIEW

**Comment by j-white** [comment]
The Aspectj proxy allows private methods to be transactional: https://github.com/OpenNMS/opennms/blob/develop/features/events/daemon/src/main/resources/META-INF/opennms/applicationContext-eventDaemon.xml#L21

**Comment by j-white** [comment]
I double checked, and the transactional annotation is not being applied here, `org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive()` returns false inside the `processInTransaction()` call.

**Comment by j-white** [comment]
Cherry-picked to release-19.0.0 and merged into develop.

**Comment by soleger** [comment]
Thanks!

**Pull request closed without merging**
