### PR TITLE
NMS-12175: WsManWQLDetectorFactory missing setBeanProperties

### PR DESCRIPTION
**Pull request by dino2gnt**
* JIRA: https://issues.opennms.org/browse/NMS-12175

### CODE REVIEW

**Comment by j-white** [comment]
@cgorantla can you take a look at this one? Looks like a regression from OIA-2.

**Comment by cgorantla** [comment]
Looks like it is. I missed it for this specific class. I checked again if we are missing it in any other places,   looks like newly created ActiveMQDetector also missed this.

I think if we depend on create detector from GenericServiceDetectorFactory using  `createDetector(Map<String, String> properties)`  that will do setBeanProperties.  

@dino2gnt  Do you mind if I push another commit for ActiveMQDetector here ?

**Comment by dino2gnt** [comment]
> @dino2gnt Do you mind if I push another commit for ActiveMQDetector here ?

Please feel free to do so.

**Comment by cgorantla** [comment]
@j-white Should we target this to  `release-24.1.3` ?

**Comment by cgorantla** [comment]
> @j-white Should we target this to `release-24.1.3` ?

I think we can only target `WsManWQLDetectorFactory` part  towards `release-24.1.3`.

**Comment by j-white** [comment]
> > @j-white Should we target this to `release-24.1.3` ?
> I think we can only target `WsManWQLDetectorFactory` part towards `release-24.1.3`.

Yeah. Given 25 is not too far away I though it would be sufficient to merge this in `develop`, but we can put that in `release-24.1.3` if you see fit.

**Pull request merged**
