### PR TITLE
NMS-16045: Upgrade vue and other dependencies

### PR DESCRIPTION
**Pull request by synqotik**
Upgrading Vue, Feather and other dependencies, partly to keep up to date, partly due to build and test errors occurring. Also maintains parity to versions used in Lokahi.

- ensure `node` and `yarn` versions
- changed build order in `build-ui.yaml` to run `build` then `test`
- updated to latest Feather
- `FeatherMegaMenu` export does not follow same pattern as all other feather components. Will require a small change to `@featherds`, but in the meantime added a shim. Note, the page this control is on isn't working anyway, and isn't reachable via OpenNMS menu items
- updated `vue` to 3.3.4
- updated `vite` to 4.x
- updated `fontawesome` version
- added `ace-builds` explicitly, it wasn't always being pulled in by `vue3-ace-editor`
- added Maven step to explicitly install `node-gyp`, this is used by `tree-sitter` in `yarn`. CircleCI build would have errors because it wasn't already installed
- a few other fixes

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16045

### CODE REVIEW

**Review by RangerRick — APPROVED** [review]
lgtm

**Review by mikewrosey — APPROVED** [review]
Looks good. There's a migration guide for Vite, if you want to double check, but it doesn't look like there will be issues. https://vitejs.dev/guide/migration.html

Also, re the mega menu shim, we might want to open an issue for that here https://github.com/feather-design-system/feather-design-system/issues

**Comment by synqotik** [comment]
> Looks good. There's a migration guide for Vite, if you want to double check, but it doesn't look like there will be issues. https://vitejs.dev/guide/migration.html
> 
> Also, re the mega menu shim, we might want to open an issue for that here https://github.com/feather-design-system/feather-design-system/issues

Thanks, yes I'll open a feather issue soon.

I'll reread the Vite migration guide as well.

**Review by scthompsonopen — COMMENTED** [review]
I know I'm late to the party here, but my review was requested and this looks good to me. Great work! I know these updates are never fun. :)

**Comment by synqotik** [comment]
> I know I'm late to the party here, but my review was requested and this looks good to me. Great work! I know these updates are never fun. :)

Thanks!!

**Pull request merged**
