### PR TITLE
NMS-9207: Cleanup events and unused code in capsd, provisiond and Linkd

### PR DESCRIPTION
**Pull request by indigo423**
Cleanup dead code / FIXME / TODO methods in Provisioner and Events. Remove unused dead event definitions which still exist from Capsd and cleanup the events which are now handled by Provisiond. 
Cleaned also other dead and unused events.

* JIRA: http://issues.opennms.org/browse/NMS-9207

### CODE REVIEW

**Comment by indigo423** [comment]
Bamboo is hanging :(

**Comment by indigo423** [comment]
Yeah it got green.

**Comment by indigo423** [comment]
@agalue Added the maintenance script and breaking changes instructions. Anything else left which prevents merging?

**Comment by agalue** [comment]
> On Apr 5, 2017, at 9:00 AM, Ronny Trommer <notifications@github.com> wrote:
> 
> @agalue <https://github.com/agalue> Added the maintenance script and breaking changes instructions. Anything else left which prevents merging?

Have you exhaustively tested all the OpenNMS features that used to be associated with all those events driven by either auto-discover or through requisitions ? I’m asking because both, the Junit tests and the smoke-tests don’t cover all the use cases, and I want to be 100% that this won’t have side effects.

**Comment by indigo423** [comment]
Added testplan in JIRA and started testing the events in running system.

**Comment by indigo423** [comment]
@agalue Finished the testplan in JIRA issue NMS-9207. Is there anything missing or need to be tested as well?

**Comment by agalue** [comment]
> On Apr 21, 2017, at 3:05 AM, Ronny Trommer <notifications@github.com> wrote:
> 
> @agalue <https://github.com/agalue> Finished the testplan in JIRA issue NMS-9207. Is there anything missing or need to be tested as well?


What about taking care of the failing JUnit tests ? Then, I can give it a full test on a VM using the RPMs.

**Comment by indigo423** [comment]
Extracted cleanup in PR #1450 after this PR is accepted the rest is renamed and reopened as new PR.

**Pull request closed without merging**
