### PR TITLE
NMS-10683: WsMan Asset Adapter should handle WQL filters returning more than one result

### PR DESCRIPTION
**Pull request by dino2gnt**
* JIRA: http://issues.opennms.org/browse/NMS-10683

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by mvrueden** [comment]
If `24.0.0` is affected, can we re-target this for `24.1.0`?
I pulled this also into bamboo.

**Comment by mvrueden** [comment]
PR is retargeted to `release-24.1.0`.

**Comment by j-white** [comment]
I'll work on adding test coverage for this.

**Comment by j-white** [comment]
Test coverage added. Closing in favor of: https://github.com/OpenNMS/opennms/pull/2553

**Pull request closed without merging**
