### PR TITLE
NMS-7965: Add support for setting system properties via user supplied .properties files

### PR DESCRIPTION
**Pull request by j-white**
JIRA: http://issues.opennms.org/browse/NMS-7965
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS252

### CODE REVIEW

**Comment by j-white** [comment]
@indigo423 feel free to push any updates to this branch. We may want to include a properties.d folder with an example file in the default etc/ folder.

**Comment by pbrane** [comment]
How do I favorite this!

**Comment by indigo423** [comment]
perfect thank you.

@pbrane what do you mean with favorite this?

**Comment by j-white** [comment]
@indigo423 is there anything additional you wanted to do here?

It may not be a bad idea to add a section to the docs describing the new behavior:

```
The priority for Java system properties is as follows:
. Those set via the Java command line i.e. in opennms.conf via ADDITIONAL_MANAGER_OPTIONS
. opennms.properties.d/*.properties
. opennms.properties
. libraries.properties
. rrd-configuration.properties
. bootstrap.properties

Property files in opennms.properties.d/ are sorted alphabetically.
```

And best practices:

```
* Add all custom properties values to one or more files in $OPENNMS_HOME/etc/opennms.properties.d/
* Avoid modifying any of property files listed above, except pennms.properties.d/
```

**Comment by indigo423** [comment]
@j-white I've added a documentation section in the Admin Guide. I wouldn't add anything else here in this issue, just introducing the opennms.properties.d directory. What do you think?

**Pull request merged**
