### PR TITLE
NMS-14156: do not require a dot before filename suffix

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-14156

### CODE REVIEW

**Comment by cgorantla** [comment]
This needs to be updated in script file and in the docs.

**Comment by christianpape** [comment]
> This needs to be updated in script file and in the docs.

done.

**Comment by cgorantla** [comment]
Since smoke test is merged now, need to update [this](https://github.com/OpenNMS/opennms/blob/develop/smoke-test/src/test/resources/device-config/test.dcb) as well

**Comment by christianpape** [comment]
> Since smoke test is merged now, need to update [this](https://github.com/OpenNMS/opennms/blob/develop/smoke-test/src/test/resources/device-config/test.dcb) as well

done.

**Review by cgorantla — APPROVED** [review]

**Review by fooker — APPROVED** [review]

**Pull request merged**
