### PR TITLE
NMS-7750: Fix for Cannot edit some Asset Info fields

### PR DESCRIPTION
**Pull request by muratyildiz1976**
- All asset info where transferred correctly
- The error occurred in the processing logic in the backend due to incompatibility of attributes of AssetCommand and OnmsAssetRecord classes while using BeanUtils.copyProperties method
- Fixed the issue by copying those lost attributes in a seperate step
- link: http://issues.opennms.org/browse/NMS-7750

### CODE REVIEW

**Comment by mvrueden** [comment]
Hello Murat. The branch foundation does not know how to execute `*IT`-tests. 
Please merge the existing test `AssetServiceImplTest` with the new one `AssetServiceImplTest`.

**Comment by mvrueden** [comment]
I pulled these changes into OpenNMS, branch https://github.com/OpenNMS/opennms/tree/jira/NMS-7750 to see what bamboo thinks about this: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS207

**Comment by mvrueden** [comment]
Hey Murat, this is still not okay. The class `AssetServiceImplIT` must be deleted. All new/changed code must me moved to class `AssetServiceImplTest` before.

**Comment by muratyildiz1976** [comment]
done

**Comment by mvrueden** [comment]
The follow up pull request can be found here: https://github.com/OpenNMS/opennms/pull/408
I close this one.

**Pull request closed without merging**
