### PR TITLE
NMS-8403: Formatting fixes

### PR DESCRIPTION
**Pull request by indigo423**
Fixed to follow one line per sentence convention to identify easily changes with line diffs introduced by using git.

### CODE REVIEW

**Comment by j-white** [comment]
A PR for a PR?

**Comment by indigo423** [comment]
If I just commit to the branch, nobody notice why and what I've changed. I don't want to do this all the time by myself :)

**Comment by j-white** [comment]
People notice commits too, not just PRs.

**Comment by indigo423** [comment]
It's nicer to let someone decide to apply a change instead of fiddeling around in his contribution directly, especially if you change a lot of lines.

**Comment by jeffgdotorg** [comment]
Yo dawg

**Pull request merged**
