### PR TITLE
NMS-7966: NPE when generating eventconf from a MIB with recursive TCs in notification varbind

### PR DESCRIPTION
**Pull request by dschlenk**
Fixes NPE when generating eventconf from a MIB with recursive TCs in notification varbind.

JIRA: http://issues.opennms.org/browse/NMS-7966
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS254

### CODE REVIEW

**Comment by agalue** [comment]
The changes sound reasonable. I think we can push this to 17.0.1, but in order to do that, the pull request has to be done against the branch release-17.0.1 instead of develop (which targets 18.0.0)

**Comment by RangerRick** [comment]
Shouldn't NPE fixes go in foundation-2016?

**Comment by agalue** [comment]
Ben is totally right :) use foundation-2016

**Comment by dschlenk** [comment]
Hey look at how timely I'm responding to this! Sorry. Anyway, should I rebase to foundation-2016 or did that already happen?

**Comment by agalue** [comment]
@dschlenk please rebase it to foundation-2016

**Comment by dschlenk** [comment]
Rebase had a bad time so I made a new branch and applied a patch. Closing this PR in lieu of that one.

**Pull request closed without merging**
