### PR TITLE
NMS-7978: Add threshold description and whitespace changes to match how the OpenNMS web GUI generates XML files

### PR DESCRIPTION
**Pull request by TimMillerDyck**
This is a proposed patch that does the following:

1. thresholds.xml
  * Add descriptions to all thresholds to add documentation on what each threshold is for
  * Change whitespace and ordering to match how the OpenNMS web UI generates the file; I used the web GUI to open each threshold in the editor and then saved it WITH NO CHANGES (other than the description) to get OpenNMS just to rewrite the file formatting. The issue here is it is much easier to diff a new version of the file with the one in production if the whitespace and XML formatting match how the GUI edits the file.

2. eventconf.xml
  * Added a comment about file ordering for documentation purposes
  * Remove extraneous blank lines

JIRA: http://issues.opennms.org/browse/NMS-7978
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS400-1

### CODE REVIEW

**Comment by TimMillerDyck** [comment]
Associated JIRA ticket: http://issues.opennms.org/browse/NMS-7978

**Comment by TimMillerDyck** [comment]
Hello, checking in on this patch. Thanks!

**Comment by TimMillerDyck** [comment]
Hello, I reverted the change that removed the blank lines from eventconf.xml (that is, the blank lines are now unchanged). This is per a message from Seth Leger.

Regards,
Tim

**Comment by indigo423** [comment]
Updated to latest develop branch to let it built with Bamboo. Created a issue branch for NMS-7978 and reopened in #535.

**Pull request closed without merging**
