### PR TITLE
NMS-10576: Document breaking changes to telemetryd

### PR DESCRIPTION
**Pull request by fooker**
* JIRA: http://issues.opennms.org/browse/NMS-10576

### CODE REVIEW

**Comment by mfuhrmann** [comment]
I don't think it's enough to mention that in the What's New section. Since it's a breaking change it should also be added somehow in the docs.
What about this sflow.groovy script which was mention by Ronny?

**Comment by fooker** [comment]
@mfuhrmann The docs already have been changed with the initial code changes. I don't know about any changes required to the grovvy scripts (beside the fact some package names changed if you import ONMS internal packages in your scripts - but there are no guarantees or documentations for that anyways).

**Comment by mfuhrmann** [comment]
@fooker I see. I just checked the docs in this PR. Sorry.

**Comment by fooker** [comment]
@RangerRick can you have a look if this fits into the new structure from your latest changes?

**Comment by fooker** [comment]
> Looks good to me. I committed a few extra bits with native speaker sprinkles and normalizing how we show config changes a bit.

Thanks

**Pull request merged**
