### PR TITLE
NMS-13824: New prometheus graphs and collections ... 

### PR DESCRIPTION
**Pull request by dino2gnt**
& update node-exporter graphs to use today's correct metric names

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13824

### CODE REVIEW

**Comment by dino2gnt** [comment]
Wouldn't mind  targeting something other than `develop` but this alters `collectd-configuration.xml`

**Comment by mmahacek** [comment]
Release-29.x

**Comment by indigo423** [comment]
Is this a super seed from this here: https://github.com/opennms-config-modules/prom-node-exporter? Just as food for thought. IMHO would prefer a OIA plugin based version which can be improved and maintained outside of our Horizon release cycle in a much quicker way and we can much better follow the prometheus whatever exporter lifecycles without requiring an update from OpenNMS itself.

My opinion about pulling  3rd party stuff in our core codebase gets a -0* :)

* +0: 'I don't feel strongly about it, but I'm okay with this.'
* *-0: 'I won't get in the way, but I'd rather we didn't do this.'
* -0.5: 'I don't like this idea, but I can't find any rational justification for my feelings.'
* ++1: 'Wow! I like this! Let's do it!'
* -0.9: 'I really don't like this, but I'm not going to stand in the way if everyone else wants to go ahead with it.'
* +0.9: 'This is a cool idea and i like it, but I don't have time/the skills necessary to help out.'

**Review by indigo423 — APPROVED** [review]

**Comment by dino2gnt** [comment]
> IMHO would prefer a OIA plugin based version

Sure, but since none of this is executable code... :man_shrugging:

**Comment by mfuhrmann** [comment]
@dino2gnt I just stumbled about this PR while reading the release notes of H30. 


> Sure, but since none of this is executable code... man_shrugging

So we can't use the plugin system for collections configs in general when it is not executable code? Afaiu it was always the plan to use OIA for stuff like this (besides additional code).

**Comment by dino2gnt** [comment]
Why would you _want_ to?  From my point of view as a non-developer, OIA does nothing to make this easier and does a lot to make it much more difficult.   Why would I want to write code to leverage an integration API if all I'm doing is writing new data collections and graphs?

Besides, the first stable release of OIA was _six days ago_.

**Comment by dino2gnt** [comment]
You're not doing a good job making it clearer why I, as a contributor, would want to use the OIA for providing a datacollection and associated graphs.  Decoupling it from the OpenNMS release process is meaningless when the goal is for it to be included in the base product. :shrug:

**Pull request merged**
