### PR TITLE
NMS-14266 remove tools/phonebook/pom-xml

### PR DESCRIPTION
**Pull request by dherdt**
### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14266

### CODE REVIEW

**Comment by freddy61025** [comment]
@cgorantla in the issue it said "Meridian-2022.1.2" Is that means it need to target at least foundation-2022 ?

**Comment by cgorantla** [comment]
> @cgorantla in the issue it said "Meridian-2022.1.2" Is that means it need to target at least foundation-2022 ?

yes. Should be re-targeted to `foundation-2022`

**Comment by mmahacek** [comment]
I found the issue while looking through the `foundation-2022` branch, though it looks like the file was originally removed in a `foundation-2021` update and later added back, so I don't know if it's worth to target 2021 since it's currently still a supported release. IANAD

**Review by cgorantla — CHANGES_REQUESTED** [review]
needs to be re-targeted to `foundation-2022`

**Review by cgorantla — APPROVED** [review]

**Pull request merged**
