### PR TITLE
Remove Quick-Add node to avoid confusions and avoid breaking the ReST API

### PR DESCRIPTION
**Pull request by agalue**
Considering the side effects on the Requisitions ReST API, I decided to remove everything related with the Quick-Add node view.

Jira: http://issues.opennms.org/browse/NMS-8160
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS512

### CODE REVIEW

**Comment by j-white** [comment]
The fix version is marked for 17.1.1, but the PR is for develop.

Is this intended for 17.1.1 and/or 18.0.0?

**Comment by pbrane** [comment]
So, quick add is gone, now?

**Comment by agalue** [comment]
> On Feb 29, 2016, at 11:42 AM, Jesse White <notifications@github.com> wrote:
> The fix version is marked for 17.1.1, but the PR is for develop.
> 
> Is this intended for 17.1.1 and/or 18.0.0?
> 
It was my mistake. It should be against develop-2016. I'll close it and create a new one.

Alejandro Galue
agalue@opennms.org <mailto:agalue@opennms.org>
PGP Key Fingerprint: 5293 6234 1E75 DF30 7821  1823 87AF 972E DAF8 BE2C

**Comment by agalue** [comment]
https://github.com/OpenNMS/opennms/pull/628

**Comment by agalue** [comment]
> On Feb 29, 2016, at 11:53 AM, p-brane <notifications@github.com> wrote:
> 
> So, quick add is gone, now?

It will be. Please check https://github.com/OpenNMS/opennms/pull/628 <https://github.com/OpenNMS/opennms/pull/628> instead.

Alejandro Galue
agalue@opennms.org <mailto:agalue@opennms.org>
PGP Key Fingerprint: 5293 6234 1E75 DF30 7821  1823 87AF 972E DAF8 BE2C

**Pull request closed without merging**
