### PR TITLE
NMS-10639: change dependencies to OpenJDK 11

### PR DESCRIPTION
**Pull request by RangerRick**
* change all java dependencies to OpenJDK 11
* move the java dependency to the minion meta-package
* remove the java dependency from sentinel since it doesn't
  have a meta-package

* JIRA: http://issues.opennms.org/browse/NMS-10639

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by j-white** [comment]
Changes look good.

There are some references to Oracle JDK 8 in the installation guide, should we update those here too?

**Comment by RangerRick** [comment]
Yeah, probably.  :)

**Comment by Naicisum** [comment]
I noticed the documents don't seem to reference the package "java-11-openjdk-devel". However the opennms spec file does. 

For windows, since the Oracle 11 JDK license has changed significantly, how about using/referencing these packages. They are created from OpenJDK by a member from the redhat team for the windows platform.
 - https://github.com/ojdkbuild/ojdkbuild

My experience on the rhel side is that by installing "java-11-openjdk-devel" you get "java-11-openjdk" and "java-11-openjdk-headless" packages. Was it intentional not to use the JDK for minion/sentinel?

**Comment by RangerRick** [comment]
As I understand it, the only reason we need the JDK specifically on the OpenNMS side is because of some runtime compilation stuff the web UI uses, and that's not an issue in minion or Sentinel.

As for mentioning Windows, I did the bare minimum of mentioning the right versions, but it's not like Windows is terribly supported in OpenNMS, even if it technically works.  Until we actually put some engineering into making OpenNMS on Windows more supportable, I'd still put it in the "you're on your own" category.  That said, I can add a link.

**Pull request merged**
