### PR TITLE
Make tile server in vaadin node maps configurable

### PR DESCRIPTION
**Pull request by jethrobakker**
JIRA: ?

Todo:
- [ ] OCA signed
- [ ] Create JIRA issue
- [ ] Code review
- [ ] Pass unit tests
- [ ] Merge to develop and close JIRA issue

### CODE REVIEW

**Comment by RangerRick** [comment]
Just pinging this to check if you ever submitted an OCA.  I'd be happy to merge it once you do.

Thanks!

**Comment by jethrobakker** [comment]
No, I have not submitted an OCA and did not create a JIRA issue yet.

**Comment by indigo423** [comment]
@jethrobakker is there a problem signing the OCA? I can help you with creating the JIRA issue?

**Comment by opennms-bamboo** [comment]
Welcome jethrobakker.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username jethrobakker.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @jethrobakker.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @jethrobakker.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by soleger** [comment]
I'm going to close this request. This change is trivial and is only necessary in the rare case that a user wants to manually edit the tileserver for the maps. This issue is already documented in bug http://issues.opennms.org/browse/NMS-7241 as well.

**Comment by opennms-bamboo** [comment]
Welcome @jethrobakker.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @jethrobakker.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Pull request closed without merging**
