### PR TITLE
NMS-13647: Flow Thresholds

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-13647

### CODE REVIEW

**Comment by indigo423** [comment]
Can we add a piece of documentation that explains the RRD step size and the default flush interval setting you can use in Karaf? I think this might be interesting to people regarding graphing and thresholding resolution.

**Review by indigo423 — APPROVED** [review]
Nice to have for me if we can add a piece of documentation that explains the RRD step size and the default flush interval setting you set in Karaf and is by default 5 minutes? I think this might be interesting to people regarding graphing versus thresholding resolution.

**Review by indigo423 — APPROVED** [review]
Thank you! Can't wait to play with this feature :)

**Comment by j-white** [comment]
Looks awesome! Excited for this one too.

**Review by cgorantla — APPROVED** [review]

**Pull request merged**
