### PR TITLE
NMS-9460: fix various JAXB issues

### PR DESCRIPTION
**Pull request by RangerRick**
This issue is a rollup of a number of JIRA issues (NMS-9447, NMS-9426, and NMS-9454) related to the JAXB refactor.  It includes 2 new smoke tests for the threshold and KSC report editors.

* JIRA: http://issues.opennms.org/browse/NMS-9460

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by mvrueden** [comment]
@RangerRick is some manual testing required here?

**Comment by RangerRick** [comment]
@mvrueden If you want to, but I did add smoke tests for the biggest bits I touched.

**Comment by mvrueden** [comment]
@indigo423 found another issue which should be fixed with this PR: https://issues.opennms.org/browse/NMS-9489
@RangerRick it might be useful to provide a test which catches this in the future.

**Comment by j-white** [comment]
NMS-9489 is a duplicate of NMS-9454 which as you mentioned is already fixed here.

I added a test to verify that the import schedule is properly built.

**Pull request merged**
