### PR TITLE
NMS-13179: Reworked Interpolator results

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-13179

### CODE REVIEW

**Review by fooker — APPROVED** [review]

**Comment by indigo423** [comment]
This here looks a bit weird and very rough? It seems like you can expose more information and not just the scope, right?
Screenshot 2021-06-08 at 18 16 40

**Comment by indigo423** [comment]
> This here looks a bit weird and very rough? It seems like you can expose more information and not just the scope, right?
> Screenshot 2021-06-08 at 18 16 40

Suggestion: What about adding 2 columns "Match" and "Scope" instead of just dumping a series of key values?

**Comment by christianpape** [comment]
Reworked the page. Now a value's tooltip contains the match and scope data.

**Review by indigo423 — APPROVED** [review]
I like this approach with your tooltip idea much better! Well done
Screenshot 2021-06-09 at 09 18 30

**Comment by fooker** [comment]
> I like this approach with your tooltip idea much better! Well done
> Screenshot 2021-06-09 at 09 18 30

@indigo423 How does the tooltip look like if the parameter contains multiple placeholders?

**Comment by indigo423** [comment]
Screenshot 2021-06-09 at 11 09 47

**Pull request merged**
