### PR TITLE
NMS-7828: Fix. Manage and Unmanage Interfaces NPE.

### PR DESCRIPTION
**Pull request by muratyildiz1976**
And removed one table which made no sense from UI:
 * JIRA: http://issues.opennms.org/browse/NMS-7828
 * Bamboo: ????

Edited by mvrueden: Added Jira link

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome @murat1976.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @murat1976.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @muratyildiz1976.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @muratyildiz1976.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by mvrueden** [comment]
Hello Murat,
thank you very much for your contribution and the signed OpenNMS Contributor Agreement.

Can you please undo all the unnecessary white-space and formatting changes?

Thank you very much.

**Comment by mvrueden** [comment]
This pull request was closed, because it should be merged into foundation.

**Pull request closed without merging**
