### PR TITLE
NMS-8739: top 20 nodes by I/O wait

### PR DESCRIPTION
**Pull request by unicolet**
See issue [NMS-8739](http://issues.opennms.org/browse/NMS-8739).

A simple jasper reports that shows the top 20 nodes by I/O Wait.
Works for net-snmp nodes (sorry, no windows) and requires that Store By Foreign Source is enabled.

Crafted with love in Fulda by me and @indigo423 
- JIRA: http://issues.opennms.org/browse/NMS-8739

### CODE REVIEW

**Comment by indigo423** [comment]
My personal point of view. I would recommend to make a dedicated repository for this kind of reports for several reasons:

* The report serves a special use case and is not possible to enable it by default
* You need to have OpenNMS to be configured in a certain way -> README in the repo
* The report needs to maintain a own life cycle and a github repo provides all the tooling, version numbers, depends on a specific version of OpenNMS, issue tracking etc. etc.

**Comment by soleger** [comment]
@indigo423 I'm not clear what your comments mean from the PR. Does this report depend on something repo outside of the OpenNMS codebase?

**Comment by indigo423** [comment]
I would create a GitHub repository, drop in the JRXML file and a README how to install it and how to configure OpenNMS to be able to use the report. Here is a suggestion, make a version of the report and say compatible with Horizon 18.x.y / Meridian 2016.x.y. I would vote to maintain this kind of reports outside of the opennms core repository. Let them be forkable for others and let people open issues on the  report itself for improvements and not entangle the lifecycle of the report with OpenNMS own lifecycle.

**Comment by mvrueden** [comment]
Hey Ulf, please check the OCA.

**Comment by j-white** [comment]
Pushed into `pr/jira/NMS-8739`.

**Comment by indigo423** [comment]
@j-white 
I suggest to let the report template live in something like here: https://github.com/opennms-forge/jasper-reports-top-io-wait

It allows people to fork, improve and open issues for it as it's own. It is also documented how to install the report in any version of OpenNMS Horizon / OpenNMS Meridian. It doesn't has impact on support when it is maintained inside the opennms repository.

**Comment by j-white** [comment]
I'm all for it. The report is disabled by default anyhow.

@unicolet, what do you think?

**Comment by unicolet** [comment]
@j-white I prefer to have it in opennms and to enable it, if needed :-)

**Comment by indigo423** [comment]
I'll follow the majority of votes, don't take my opinion as a blocker :)

**Comment by mvrueden** [comment]
Maintaining existing reports is quite honest a pain in the ass. Every JasperReport version upgrade, requires us to maintain the reports. 

Therefore, I think if a report can be enabled by default and is a really good report, which helps most of the people using opennms out there, it is reasonable to pull it into the opennms codebase. If it cannot be enabled by default, because it requires a certain setup, or it is a special report, only useful for a minority of the opennms users, I don't think we should pull it into the code base. It is up for discussion, if we put it into an "examples" or "contrib" folder, instead, though.

In general I like the idea of having a "opennms/reports" repository instead. 

As this report is not enabled by default, I vote against pulling it into the OpenNMS code base.
If required, I can create a "reports" repository and move it there.

**Comment by j-white** [comment]
After some more discussion we've agreed to merge this into the code-base since we don't currently have a better workflow for handling custom/contributed reports.

I've pushed the changes to `pr/jira/NMS-8739`. Waiting on Bamboo.

**Pull request merged**
