### PR TITLE
NMS-9867 Inconsistent handling of keyboard navigation on top menu

### PR DESCRIPTION
**Pull request by patrick-schweizer**
Fix for https://issues.opennms.org/browse/NMS-9867

### CODE REVIEW

**Comment by mvrueden** [comment]
LGTM (-:

**Comment by pbrane** [comment]
Shouldn’t this be committed to foundation branch?

**Comment by mvrueden** [comment]
It depends where it should go. It is targeted for Meridian-2017.X. If it should go to Meridian-2015.X releases as well, we must cherry-pick it backwards (or should have merged it to foundation in the first place)

**Comment by pbrane** [comment]
It was a PoweredBy customer that reported the issue and the fix should be targeted at a branch that they will be able to use; hence Foundation vs. Meridian.  And, shouldn't this make it to Horizon as well?

**Comment by mvrueden** [comment]
`foundation` -> `Meridian-2015.X`, `Meridian-2016.X` and `Meridian-2017.X`
`foundation-2016` -> `Meridian-2016.X` and `Meridian 2017.X`
`foundation-2017` -> `Meridian-2017.X`

everything merged to any `foundation` branch will end up in the next Horizon release (22.0.0 -> `develop`) and the next current Horizon release (21.0.5 -> `release-21.0.5`)

As mentioned above, it all comes down to which Meridian version this patch should make it. I assumed `Meridian-2017`. If that is not the case, we have to put it in the correct foundation-branch.

**Pull request merged**
