### PR TITLE
NMS-12755: Fix event matching when events for a given UEI are defined across multiple files.

### PR DESCRIPTION
**Pull request by j-white**
JIRA: https://issues.opennms.org/browse/NMS-12755

### CODE REVIEW

**Comment by j-white** [comment]
@dschlenk can you give this a whirl and double check that it fixes your problem?

**Comment by dschlenk** [comment]
@j-white will do! thanks!!!

**Comment by dschlenk** [comment]
@j-white works IRL!

**Comment by j-white** [comment]
Woohoo. I'll merge this and close https://github.com/OpenNMS/opennms/pull/3067 then.

**Pull request merged**
