### PR TITLE
NMS-15334: Catch config reloads when editing new thresholds

### PR DESCRIPTION
**Pull request by amay94**
I was able to recreate the issue by reloading threshd config while I had the page open for editing a new threshold / expression. We don't write the new object to disk until it's fully edited, so reloading the config wipes it from memory. This fix just creates a new default object to update if the previous one has disappeared. 

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15334

### CODE REVIEW

**Review by synqotik — APPROVED** [review]
Code and logic look good and make sense to me. Also, nice job refactoring!

**Review by RangerRick — APPROVED** [review]
I don't know the guts well enough to say, but is it possible the config would have changed/reloaded but _without_ the number of entries changing? Either way, this is better than before. :D

**Review by christianpape — APPROVED** [review]
LGTM.

**Comment by amay94** [comment]
> I don't know the guts well enough to say, but is it possible the config would have changed/reloaded but without the number of entries changing? Either way, this is better than before. :D

If someone had manually updated the threshd config file and added a new threshold to this specific group while the editing page was open, this could happen. To address that, I'd want to get rid of the `thresholdIndex` parameter being passed around and only add the new threshold / expression once when editing is complete.

**Pull request merged**
