### PR TITLE
NMS-13954: Add vue/chart.js resource graphs

### PR DESCRIPTION
**Pull request by mikewrosey**
Adds vue / chartjs resource graphs.
Adds typcriptified pieces of Backshift / flot-legend.

https://user-images.githubusercontent.com/8680122/151608056-3f997df4-6d81-4ff3-a78a-de5a83084851.mp4

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13954

### CODE REVIEW

**Comment by j-white** [comment]
Awesome, great to see a fresh look on our charts.

**Comment by dino2gnt** [comment]
Do VDEFs work correctly yet?

**Comment by mikewrosey** [comment]
> Do VDEFs work correctly yet?

There's no real improvements to the backshift or legend pieces, beyond an update to ES6+ with typescript, so everything *should* work the same as the current resource graphs. Looks like only aggregation functions work with VDEF.

**Comment by j-white** [comment]
Looks good - I tried in on a few different graphs - and seems consistent with the existing visualizations.

There are a lot of improvements we could make UX wise, but the important bit here is the graph component.

**Review by j-white — APPROVED** [review]

**Pull request merged**
