### PR TITLE
NMS-13511: Use Karaf shell commands to secure Minion Karaf shell access

### PR DESCRIPTION
**Pull request by indigo423**
### All Contributors

* [ ] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [ ] Have you made a comment in that issue which points back to this PR?
* [ ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

Use Karaf shell commands instead of editing files in the file system manually.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13511

### CODE REVIEW

**Review by mmahacek — APPROVED** [review]
These steps are a lot simpler and should be easier to maintain.  My only comment is that since the RHEL/Ubuntu options point to the same document, is there any reason to combine them to prevent possible confusion at the steps being the same? The end result only having a "non-docker" (exact wording TBD) and Docker options in the Securing Karaf section.

**Comment by indigo423** [comment]
> These steps are a lot simpler and should be easier to maintain. My only comment is that since the RHEL/Ubuntu options point to the same document, is there any reason to combine them to prevent possible confusion at the steps being the same? The end result only having a "non-docker" (exact wording TBD) and Docker options in the Securing Karaf section.

Yeah, thanks for asking :) The Meridian docs exclude the Ubuntu/Debian. But I agree. Maybe we can do it like Grafana and just name it "Linux" and "Docker".

Screenshot 2021-08-19 at 09 40 57

**Comment by indigo423** [comment]
@mmahacek Here the change I've made remove the duplicate entry for CentOS/RHEL and Ubuntu/Debian:

Screenshot 2021-08-23 at 11 49 44

**Review by agalue — APPROVED** [review]
LGTM

**Pull request merged**
