### PR TITLE
NMS-7296: Documentation Dashboard

### PR DESCRIPTION
**Pull request by indigo423**
- Created user documentation for the OpenNMS Dashboard
- Created screenshots for all components
- Embedded and described all components
- Added advanced section for user name based surveillance view and user restriction filters

JIRA: http://issues.opennms.org/browse/NMS-7296

Todo:
- [x] Native speaker review
- [ ] Merge to develop and close JIRA issue

### CODE REVIEW

**Comment by rfdrake** [comment]
For some reason when I made my patch it opened a second pull-request rather than appending to this one.  New one is #202

**Comment by indigo423** [comment]
@rfdrake thank you very much. I've merged your changes to the original pull request. So you commit is reflected. I've seen most issue with editing a file directly in GitHub is only possible if you click on "View" for the file. The pen to edit is only in this mode available.

**Comment by rfdrake** [comment]
On 01/13/2015 06:33 PM, Ronny Trommer wrote:
>
> @rfdrake <https://github.com/rfdrake> thank you very much. I've merged
> your changes to the original pull request. So you commit is reflected.
> I've seen most issue with editing a file directly in GitHub is only
> possible if you click on "View" for the file. The pen to edit is only
> in this mode available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenNMS/opennms/pull/197#issuecomment-69843044>.
>
I wasn't able to use the pen because I don't have merge rights in the
opennms tree, so I'm only able to submit pull requests.  I did a few
more today in the same broken format.  I hope it isn't too much hassle.

Thanks,
Robert

**Comment by indigo423** [comment]
@rfdrake Don't worry I can handle this. As long I can find the issue number. Thank you so much for finding all this little glitches, this is really cool.

**Pull request merged**
