### PR TITLE
NMS-15489: Describe Usage Statistics feature

### PR DESCRIPTION
**Pull request by emarsh1995**
- Remove `deployment/images/deployment/core/data-sources.png`
- Update `deployment/core/getting-started.adoc`
- Update `operation/deep-dive/admin/configuration/data-collection.adoc`
- Update `operation/quick-start/users.adoc`

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://opennms.atlassian.net/) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the Jira link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the Jira issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here, or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready. Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15489

### CODE REVIEW

**Review by Bonrob2 — DISMISSED** [review]
LGTM, thanks!

**Comment by Bonrob2** [comment]
@jeffgdotorg, if I understood correctly, this is being implemented post 31.0.8? Shall I hold off on merging?

**Comment by mmahacek** [comment]
We already have been collecting the stats (for opted-in users) for many versions. I'm not sure what's changing in the next version.

**Comment by Bonrob2** [comment]
> We already have been collecting the stats (for opted-in users) for many versions. I'm not sure what's changing in the next version.

It's no longer opt-in. It's done by default and you have to opt out.

**Comment by synqotik** [comment]
@Bonrob2 @mmahacek Note that Horizon 32 will make some updates:

- statistics collection is enabled by default (unless user previously opted-out)
- new notice screen which is just a notice with 2 buttons, "Learn More" (link to new UI page and acknowledge) and "Dismiss" (acknowledge)
- New Vue UI page which allows enable/disable, viewing items in a much nicer format, allows copying full json stats

We'll need more documentation updates, will follow up.

**Comment by jeffgdotorg** [comment]
@Bonrob2 the consent behavior changes, and the terminology change from "Data Choices" to "Usage Statistics", will not land until Horizon 32. There's still valuable work in this PR that I don't want us to lose; some of it does not pertain directly to the usage statistics but appears to be stuff that Emily noticed needed doing while she was in the neighborhood.

Relevant to some of the conversation above, I also want to draw a line between *collecting* the usage stats (always happening, regardless of the opt-in / opt-out status of the system)  and *sharing* those stats.

My suggestion:
1. Rebase this PR to `develop` and merge with my suggestions
2. Create a separate PR that pulls back the non-usage statistics work to `foundation-2020` since I think most or all of it applies that far back.

**Comment by Bonrob2** [comment]
> 
> My suggestion:
> 
>     1. Rebase this PR to `develop` and merge with my suggestions
> 
>     2. Create a separate PR that pulls back the non-usage statistics work to `foundation-2020` since I think most or all of it applies that far back.

Sounds good. I'll do that this morning, so that E's changes make it into the next release.

**Review by Bonrob2 — APPROVED** [review]
LGTM!

**Pull request merged**
