### PR TITLE
NMS-13112: Fix Telemetryd daemon reloading 

### PR DESCRIPTION
**Pull request by cgorantla**
### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13112

### CODE REVIEW

**Comment by cgorantla** [comment]
@RangerRick Think this can go for tomorrow's release if smoke-test-full passes.
Verified both bugs on `develop`

**Comment by cgorantla** [comment]
One issue with enabling flows on minion by default. 
Both OpenNMS & Minion uses the same `9999` port for netflow and both are enabled by default.
Probably we can change minion port to something else.


ports | grep -i 9999
[sudo] password for chandra: 
udp6       0      0 :::9999                 :::*                                209157/java         
udp6       0      0 :::9999                 :::*                                205763/java

**Review by christianpape — APPROVED** [review]
Looks good to me.

**Comment by cgorantla** [comment]
For now removed NMS-13110 changes as smoke tests are failing probably due to conflicting configs.

**Comment by cgorantla** [comment]
smoke test fill suite is pasing. Merging.

**Pull request merged**
