### PR TITLE
NMS-8690: The ReST end point /foreignSourcesConfig/assets contains invalid fields

### PR DESCRIPTION
**Pull request by agalue**
The ReST end point /foreignSourcesConfig/assets contains invalid fields

* JIRA: http://issues.opennms.org/browse/NMS-8690
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS962

### CODE REVIEW

**Comment by agalue** [comment]
I just figured out that I made the branch and the PR against develop, and I need it against foundation-2016. The change is fairly simple, so maybe we can merge this one and then cherry-pick the solution on foundation-2016. Or, we can close this one, delete the branch, re-create the branch against foundation-2016, apply the fix and create the PR again. Let me know what's better.

**Comment by soleger** [comment]
Closing to reopen against foundation-2016.

**Comment by soleger** [comment]
I'm working on manually merging this now.

**Comment by soleger** [comment]
This can't be merged back to foundation because of Java 8 syntax. Closing this PR and retargeting it for foundation-2016.

**Pull request closed without merging**
