### PR TITLE
NMS-8120: Fixed a paragraph in the "Automatic Discovery" provisioning chapter that wasn't making any sense.

### PR DESCRIPTION
**Pull request by StCyr**
Please review if the original intent is preserved.

JIRA: http://issues.opennms.org/browse/NMS-8120
Bamboo: ?

### CODE REVIEW

**Comment by StCyr** [comment]
http://issues.opennms.org/browse/NMS-8120

**Comment by indigo423** [comment]
It would make sense to fix this for 17.0.1. 

@RangerRick Does it make sense to set the target to foundation-2016 instead of develop branch?

**Comment by RangerRick** [comment]
Foundation 2016 makes sense for this, yes.

**Comment by StCyr** [comment]
new PR = https://github.com/OpenNMS/opennms/pull/592

**Pull request closed without merging**
