### PR TITLE
NMS-7855: Fix. distributed details page broken.

### PR DESCRIPTION
**Pull request by muratyildiz1976**
* Jira: http://issues.opennms.org/browse/NMS-7855

Edit by mvrueden: Added Jira link.

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome @murat1976.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @murat1976.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @muratyildiz1976.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @muratyildiz1976.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by soleger** [comment]
Can you describe what problem you are fixing here? Which browser are you using? Do you have any screenshots of the issue?

**Comment by muratyildiz1976** [comment]
yes of course. 

its a kind of NPE. 
 
i am using chrome (Version 45.0.2454.101 (64-bit))

i have attached 2 screenshot to the issue:
http://issues.opennms.org/browse/NMS-7828

it can be reproduced like that:
(go to) main menue -> admin -> configure opennms -> manage and unmanage interfaces and services

then click 'unselect all', and then click 'apply changes', then the NPE is thrown.

the stacktrace is copied in the issue.

**Comment by muratyildiz1976** [comment]
hi again

forget the screenshot which are currently in the issue.

i wanted to attach the right ones but currently i cannot login into jira.

**Comment by mvrueden** [comment]
There seems to be some misunderstanding. 
This is a fix for http://issues.opennms.org/browse/NMS-7855 but @muratyildiz1976 described problems of issue http://issues.opennms.org/browse/NMS-7828. 

Back to topic:
I tried to reproduce the issue described in NMS-7855 and was not able to reproduce it.
I tried with the following browsers: 
 * Firefox 41.0.1
 * Chrome 45.0.2454.101 (64-bit) 
 * Safari 9.0 (11601.1.56)
 * Internet Explorer 11.0.10240.16431
 * Edge (was not able to determine version)

So to me it looks like we need more information on the issue in general.

**Comment by mvrueden** [comment]
This pull request should be merged into foundation instead of release-16.0.4 branch. Closing...

**Pull request closed without merging**
