### PR TITLE
CLOUD-602: Create schema document describing Minion configuration

### PR DESCRIPTION
**Pull request by mattixtech**
This PR adds a configuration schema document which acts as a source of documentation for the various configuration options that apply to the Minion container. The primary intent of this document is to be used to feed data-driven UI in MaaS but additionally going forward we could also use it to generate some useful documentation.

In this iteration of the document only the keys and labels are described along with their types. Future enhancements will be made to provide descriptions, additional validation, as well as examples.

This PR also enhances the confd template for configuring telemetry allowing additional configuration to be easily supplied in the case of single port listener configuration.

As an FYI, this document is expected to evolve in the following ways in the short to medium term:
- validation added for all the options where applicable
- descriptions and examples added for all the options
- CI updated to push a versioned copy of this document to our cloud to be consumed by MaaS
- A linter added to validate this document against a yaml equivalent of XSD which will run as part of CI

### All Contributors

* [*] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [*] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [*] Have you made a comment in that issue which points back to this PR?
* [*] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [*] If this is a new or updated feature, is there documentation for the new behavior?
* [*] If this is new code, are there unit and/or integration tests?
* [*] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/CLOUD-602

### CODE REVIEW

**Review by RangerRick — APPROVED** [review]
Seems reasonable to me. I assume the TODOs will eventually be part of a different PR (since they seem to all be just validation/labeling and not relevant to working cod?)

**Comment by mattixtech** [comment]
> Seems reasonable to me. I assume the TODOs will eventually be part of a different PR (since they seem to all be just validation/labeling and not relevant to working cod?)

Yep, plan is to tackle that stuff next. At the moment validation has been deferred so we don't need it imminently as part of this PR.

**Review by bouff — APPROVED** [review]
LGTM as well. 👍

**Review by indigo423 — APPROVED** [review]
👍

**Pull request merged**
