### PR TITLE
NMS-10281: We have a regression in the SNMP core API for get effective address (snmp-proxy)

### PR DESCRIPTION
**Pull request by patrick-schweizer**
* JIRA: https://issues.opennms.org/browse/NMS-10281

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by mvrueden** [comment]
It looks only like test changes to me. @j-white, @patrick-schweizer what is missing here to actually merge it?

**Comment by j-white** [comment]
Feedback is in the JIRA issue, requested changes are:
1) Use the MockSnmpAgent instead of a naive UDP listener
2) Bind two different sockets on the localhost and use the proxy functionality for both of these

**Comment by patrick-schweizer** [comment]
removing labels "triage" and "waiting for feedback" => Jesse and me went over it yesterday. Now we are waiting for bamboo.

**Comment by mvrueden** [comment]
The job was deleted from bamboo. I manually created it, should build now: https://bamboo.opennms.org/browse/OPENNMS-ONMS2951

**Comment by patrick-schweizer** [comment]
> The job was deleted from bamboo. I manually created it, should build now: https://bamboo.opennms.org/browse/OPENNMS-ONMS2951

thank you!

**Pull request merged**
