### PR TITLE
NMS-9291: Logging for TCP output queue

### PR DESCRIPTION
**Pull request by tdefilip**
- Add logging of queue checks/offers/drains and queue size/capacity statistics.

JIRA: http://issues.opennms.org/browse/NMS-9291

Todo Review:
- [ ] Typo and grammar
- [ ] Formatting and conventions
- [ ] Content

### CODE REVIEW

**Comment by j-white** [comment]
This looks like a good use case for using a `MetricRegistry` along with a `Slf4jReporter`:
    http://metrics.dropwizard.io/3.1.0/manual/core/#slf4j

**Comment by tdefilip** [comment]
If I'm understand how to use the metric registry, I still need to maintain the various counter members.  But instead of having a bunch of get methods, I can just register all such values with the registry (which I would pass in to various constructors) and then dump the registry using Slf4jReporter?

**Comment by j-white** [comment]
Yeah, that's the idea. This makes it easier to manage and gives more detailed statistics in most cases.

**Comment by tdefilip** [comment]
I've added use of the MetricRegistry.  I have not included the Slf4jReporter since it looks like resetting the counters would be much more difficult that way; additionally, the queue size and remaining capacity are not part of the registry, so it looks like it would be difficult to get the reporter to include them.

Let me know if they are a must-have.

**Comment by j-white** [comment]
We don't really gain much by using the MetricRegistry this way.

I'll go ahead and merge the patch before we made the MetricRegistry changes.

**Comment by j-white** [comment]
I've pushed [a377d](https://github.com/OpenNMS/opennms/pull/1462/commits/a377d807c08c49742dcb2e4da0a20d45ae3d6136) to `pr/jira/NMS-9291`. Waiting on Bamboo.

**Comment by j-white** [comment]
Manually merged into `foundation-2016`.

**Comment by tdefilip** [comment]
Thanks!

**Pull request closed without merging**
