### PR TITLE
 NMS-16535: Reorganize date time and notification in main navigation

### PR DESCRIPTION
**Pull request by indigo423**
Clarify date and time in separate lines, to a) save some space and b) make it easier to read. Group notification components for user and team notification and the indicator if the system has notifications enabled together.

Screenshot 2024-09-23 at 16 36 48

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16535

### CODE REVIEW

**Review by fooker — APPROVED** [review]

**Comment by synqotik** [comment]
From a Product standpoint, we'd prefer to leave the layout as-is, except for putting date/time on 2 lines as proposed.

Preference for now is to have the "gear" icons, etc. all the way to the right as in the current design.

**Review by synqotik — CHANGES_REQUESTED** [review]
Requesting that the layout not be changed, but only change the layout of the date/time to be 2 lines, with the new `DEFAULT_FORMAT_PATTERN`.

**Comment by indigo423** [comment]
Thanks for taking a look at it.

**Comment by indigo423** [comment]
> Requesting that the layout not be changed, but only change the layout of the date/time to be 2 lines, with the new `DEFAULT_FORMAT_PATTERN`.

Doesn‘t make sense to me just changing the date time format because it doesn‘t solve the problem I wanted to address. Just having it two Lines at the Same place introduces other issues like alignment. Top right corner for date/time is a common pattern in UI’s in cultures who read left to right.

Notification related components are grouped in my proposal, because they relate to each other. Menu items are grouped and the gearbox is only available for users with the role Admin, which makes it a bit hard for me to follow your argument.

Feel free take the changes from my PR to change the date/time format.

**Pull request closed without merging**
