### PR TITLE
NMS-13042: Handle error scenarios

### PR DESCRIPTION
**Pull request by cgorantla**
Currently Snmp4JStrategy doesn't throw specific exception for timeout and
error scenarios. This results in null response which cause ArrayIndexBound exception

This PR should handle those error scenarios.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13042

### CODE REVIEW

**Review by RangerRick — APPROVED** [review]
This _seems_ good to me... it does scare me adding thrown exceptions to something as core as the SNMP4J strategy though... are we sure there aren't any side-effects elsewhere?  Feel like at the least you should run this in a `-smoke` branch.

**Comment by cgorantla** [comment]
> This _seems_ good to me... it does scare me adding thrown exceptions to something as core as the SNMP4J strategy though... are we sure there aren't any side-effects elsewhere? Feel like at the least you should run this in a `-smoke` branch.

The calling method catches all the exceptions. So I  think should be safe.

**Comment by cgorantla** [comment]
> > This _seems_ good to me... it does scare me adding thrown exceptions to something as core as the SNMP4J strategy though... are we sure there aren't any side-effects elsewhere? Feel like at the least you should run this in a `-smoke` branch.
> 
> The calling method catches all the exceptions. So I think should be safe.

Also SNMP4JWalker seems to do similar thing.  Odd that this error was not caught earlier as it is simple timeout issue. Going to do some digging.

**Comment by cgorantla** [comment]
> > > This _seems_ good to me... it does scare me adding thrown exceptions to something as core as the SNMP4J strategy though... are we sure there aren't any side-effects elsewhere? Feel like at the least you should run this in a `-smoke` branch.
> > 
> > 
> > The calling method catches all the exceptions. So I think should be safe.
> 
> Also SNMP4JWalker seems to do similar thing. Odd that this error was not caught earlier as it is simple timeout issue. Going to do some digging.

Okay. Looks like SNMPInterfacePoller is the only place that uses get with multiple oids.  All others are get with one oid which would not throw this exception.

**Pull request merged**
