### PR TITLE
Database-Reporting: More Cleanup (maybe final?)

### PR DESCRIPTION
**Pull request by mvrueden**
Here are some more cleanups related to the Database Reporting in the `features/drift2` branch.
The changes include:
 - Better Success/error handling when creating a report (no more modals)
 - Actual Parameter validation. No more String for Integer parameters
 - Fix (absolute) date parsing (didn't work before, always took default)
 - Add tooltips were useful
 - Remove TODOs
 - Fix wrong color used on classification ui when entity error occurred
 - Some Cleanups in general

This should be the last (generic) PR related to `Enterprise Reporting 2.0`.
All follow up issues should be related to a concrete issue. 

Please give this a try and let me know if there are more general changes we should apply before this is being merged back to `develop`.

### CODE REVIEW

**Comment by mvrueden** [comment]
I fixed the issue you encountered and various other things. Just a side note: you can work around the NPE by just setting timeouts in the endpoint UI.

**Comment by j-white** [comment]
Gave this another spin. Working well for me.

Looks like the `DatabaseReportPageIT` is still failing/flapping though 🙁

**Comment by j-white** [comment]
This branch passed in Bamboo, and passed in CircleCI once I merged in the latest changes from the release-25.0.0 branch.

Went ahead and merged this since it fixes some pending problems in the `features/drift2` branch.

**Comment by mvrueden** [comment]
Still flapping though: https://circleci.com/gh/OpenNMS/opennms/9189#tests/containers/5

**Pull request merged**
