### PR TITLE
NMS-8104: init script checkXmlFiles() fails to pick up errors

### PR DESCRIPTION
**Pull request by bobwest**
Fix return status of checkXmlFiles() in opennms init script

### CODE REVIEW

**Comment by j-white** [comment]
@mvrueden where's Ulf?

**Comment by mvrueden** [comment]
@j-white I do not understand the question.
If you refer to the OCA Github Plugin: 
Ulf verified that @bobwest signed the OCA, which stating to https://www.opennms.org/wiki/Executed_contributor_agreements he has.
So Ulf is working fine.

**Comment by j-white** [comment]
Oups, I didn't see the check. Ignore me. All is well.

**Comment by j-white** [comment]
Looks good. Thanks!

**Pull request merged**
