### PR TITLE
HZN-1455: Java 9 Support

### PR DESCRIPTION
**Pull request by RangerRick**
This PR includes the changes necessary for building under Java 8, but running under Java 9.  This includes an upgrade of our embedded liquibase from 2 to 3.

The only outstanding issue I know of is an error in `output.log` related to XMP.  We should consider removing XMP support unless Bobby Krupczak updates the XMP APIs to make Java 9+ happy.

* JIRA: http://issues.opennms.org/browse/HZN-1455

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by RangerRick** [comment]
This is marked triage until we can test it some more.  Looks like there are some failures in `karaf.log` that I fear will require the karaf 4.2 update.  At least, we may need to update to a newer pax-web, because that pulls in a newer version of `org.ow2.asm` which I suspect we need for newer JVMs?  Dunno.

```
2019-01-23T15:21:26,146 ERROR org.apache.aries.blueprint.core:1.8.3(16) [features-1-thread-1] org.apache.aries.blueprint.container.BlueprintContainerImpl: Unable to start blueprin
t container for bundle org.opennms.container.extender/24.0.0.SNAPSHOT
org.osgi.service.blueprint.container.ComponentDefinitionException: java.lang.IllegalArgumentException
        at org.apache.aries.blueprint.container.ReferenceRecipe.internalCreate(ReferenceRecipe.java:123) ~[?:?]
        at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88) ~[?:?]
...
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[?:?]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[?:?]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[?:?]
        at org.apache.aries.proxy.impl.common.AbstractWovenProxyAdapter.readClass(AbstractWovenProxyAdapter.java:694) ~[?:?]
        at org.apache.aries.proxy.impl.interfaces.InterfaceCombiningClassAdapter.generateBytes(InterfaceCombiningClassAdapter.java:117) ~[?:?]
        at org.apache.aries.proxy.impl.interfaces.ProxyClassLoader.createProxyClass(ProxyClassLoader.java:163) ~[?:?]
        at org.apache.aries.proxy.impl.interfaces.InterfaceProxyGenerator.getProxyInstance(InterfaceProxyGenerator.java:97) ~[?:?]
        at org.apache.aries.proxy.impl.AsmProxyManager.createNewProxy(AsmProxyManager.java:80) ~[?:?]
        at org.apache.aries.proxy.impl.AbstractProxyManager.createDelegatingInterceptingProxy(AbstractProxyManager.java:77) ~[?:?]
        at org.apache.aries.proxy.impl.AbstractProxyManager.createDelegatingProxy(AbstractProxyManager.java:42) ~[?:?]
        at org.apache.aries.blueprint.container.AbstractServiceReferenceRecipe.createProxy(AbstractServiceReferenceRecipe.java:332) ~[?:?]
        at org.apache.aries.blueprint.container.ReferenceRecipe.internalCreate(ReferenceRecipe.java:107) ~[?:?]
        ... 32 more
```

**Comment by j-white** [comment]
We can still look at merging this even if Java 9 support is not complete provided that it doesn't break anything existing.

It's easier to review a bunch of smaller PRs, then one huge PR with all of the changes required for Java 9 support.

**Comment by mvrueden** [comment]
Yeah, I think that makes sense.
We should probably decide if we want to merge this in a broken state and so maybe delay a possible 24.0.0 release. However if this is not planned anytime soon, nevermind my comment 😄

**Comment by RangerRick** [comment]
Almost all of these changes can be split out into separate things (I think it's actually the PostgreSQL 9.4 JDBC update that's throwing the builds off)

I'll do separate PRs for that, the liquibase upgrade, and the jetty upgrade and close this for now until all of that is handled.

**Pull request closed without merging**
