### PR TITLE
NMS-13137: add UI for setting page limits

### PR DESCRIPTION
**Pull request by RangerRick**
This PR adds a pull-down for changing the page limit on alarms, events, notifications, and outages.

Screen Shot 2021-02-23 at 5 35 59 PM

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13137

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome CI/CD System (cicd-system@opennms.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username CI/CD System (cicd-system@opennms.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](https://wiki.opennms.org/wiki/images/6/6b/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit https://wiki.opennms.org/wiki/Contributor_Agreement

**Comment by christianpape** [comment]
Hi, I just tested the branch. It seems to work fine. There is only one issue. 
* I browse to the event list (event count = 53)
* Now I click on `Next` and I receive the second page event/list?sortby=id&acktype=unack&limit=20&multiple=1
* Now I change the limit to for example 100 and I get a page event/list?sortby=id&acktype=unack&limit=100&multiple=1
which results in an empty page since there are no events 100+
Unfortunately the controls are also gone, so I cannot hit the `Previous` button.

**Comment by RangerRick** [comment]
> Maybe it is a good idea to reset `multiple` when `limit` is changed.

Good point, that makes sense.

**Comment by RangerRick** [comment]
@christianpape alright, added some logic to reset multiple if limit changes.  Seems to do the right thing in my testing.

**Review by christianpape — APPROVED** [review]
Nice. Works perfect.

**Pull request merged**
