### PR TITLE
NMS-12269: Netscaler vServer SNMP collection and graph definitions

### PR DESCRIPTION
**Pull request by jeffgdotorg**
### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [x] If this is a new or updated feature, is there documentation for the new behavior?
* [x] If this is new code, are there unit and/or integration tests?
* [x] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12269
* Bamboo (Continuous Integration): https://bamboo.opennms.org/

### CODE REVIEW

**Comment by j-white** [comment]
> * [x]  If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

**Comment by indigo423** [comment]
Just as food for thought, when you separate the changes into dedicated files, e.g. `netscaler-vserver.xml` and `netscaler-vserver.graph.properties` you would add files and would not require someone to merge them into their existing config files.

**Comment by jeffgdotorg** [comment]
@indigo423 I've reworked my changes as separate files, per your suggestion. Would you mind having another look and weighing in, please?

**Comment by j-white** [comment]
We've avoided modifying `datacollection-config.xml` up until now, not sure this change warrants it.

**Comment by RangerRick** [comment]
We can always leave it out of `datacollection-config.xml` and make a note in the upgrade notes.  That's what we've done in the past.

**Pull request merged**
