### PR TITLE
HZN-626: Fixed ActiveMQ counters and graph definitions

### PR DESCRIPTION
**Pull request by soleger**
* JIRA: http://issues.opennms.org/browse/HZN-626

### CODE REVIEW

**Comment by j-white** [comment]
We also need to include upgrade instructions here now, since the RRDs need to be recreated in order for the attribute types to be changed.

**Comment by RangerRick** [comment]
Oops, this got closed because the `release-19.0.0` branch went away.  Should this be a `develop` thing, or should we re-point it at `foundation-2017`?  (I'll point it at `foundation-2017` until we can decide...)

**Comment by soleger** [comment]
These counters will all be zero unless you're using a Minion, correct? I just want to make sure that I'm phrasing the release notes correctly.

**Comment by j-white** [comment]
Mostly zeros unless Minion is used. There are still some connections and consumers without any Minions though.

**Pull request merged**
