### PR TITLE
NMS-9816: Add Disk IO monitoring capabilities with Net-SNMP

### PR DESCRIPTION
**Pull request by indigo423**
Enable disk IO metrics for read/writes in bytes and operations in default system definition to get collected by default. Added metrics for disk load in percent for 1, 5 and 15-minute averages and created RRD graph definitions for each value as percentage graph and an aggregated graph with all three values similar to a load average graph.

Added 64-bit counters for reading and write bytes and if they are supported, suppress the graph with the 32-bit counter.

* JIRA: http://issues.opennms.org/browse/NMS-9816

### CODE REVIEW

**Comment by pbrane** [comment]
These are really nice configurations!  Do these metrics require changes to NetSNMP configuration?

**Comment by indigo423** [comment]
@pbrane no changes required, they are provided by default.

**Comment by j-white** [comment]
Looks good to me, but I'd opt for targeting develop instead of foundation-2017 since:
A) We're modifying an existing group
B) There's the potential to start collecting *alot* more metrics

**Comment by indigo423** [comment]
@j-white no problem with retargeting to develop, just picked foundation with improving support in mind. I'll fix this.

**Comment by indigo423** [comment]
Changed base to develop, I also noticed the whole file has a 3 space indentation. If we decide to not not fix this problem I can revert the separate commit https://github.com/OpenNMS/opennms/pull/1815/commits/7743342e8f2b900da1b83bd757d895d394e39312

**Comment by indigo423** [comment]
@RangerRick do you know why Bamboo is not running on this branch?

**Comment by indigo423** [comment]
@j-white Just looked at the issue NMS-9789 was a little bit confused, cause the PR in the issue points to something with vaccumd cleanup config.

This PR makes #1812 obsolete.

**Comment by indigo423** [comment]
@mfuhrmann @j-white for sanity reasons I suggest two options:

* Close NMS-9816 and move everything to NMS-9789
* Do the other way around

I can fix this just let me know which way you prefer.

**Comment by indigo423** [comment]
A good point raised in the other PR, the new metrics are added to a new group to prevent breaking `storeByGroup` configs, what do you think?

**Comment by indigo423** [comment]
I have picked the changes from @mfuhrmann and added them to this PR which was easier. We can close #1812 and the related issue.

**Comment by indigo423** [comment]
The build failed with building some smoke test docker images :/ https://bamboo.opennms.org/browse/OPENNMS-ONMS1993-SMOKE-2

**Comment by indigo423** [comment]
@RangerRick for some reasons the docker build in the smoke tests fail :/

**Comment by RangerRick** [comment]
Trying re-running it now.  Might have just hit a temporary yum outage or something.

**Comment by j-white** [comment]
The formatting changes seem out of place here. If there's an issue with the 3 space indentation then let's address that separately since many other files are now formatted this way.

**Comment by j-white** [comment]
👍

**Pull request merged**
