### PR TITLE
Feature refactor trapd hzn 629

### PR DESCRIPTION
**Pull request by cernerpradeep**
HZN-629 Create blueprint.xml for the Trapd receiver. 

Creating pull request for review and help. 

For the junit to complete successfully we need to  inject list of snmpv3users in blueprint. Need help in injecting the same. I tried to create beans manually and send but since the values were null, SnmpUtils.registerForTraps(this, this, address, m_snmpTrapPort, m_snmpV3Users);  is throwing exception.

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome Pradeep S (pradeep.s1@cerner.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Pradeep S (pradeep.s1@cerner.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @DP044946.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @DP044946.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome Pradeep S (pradeep.s1@cerner.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Pradeep S (pradeep.s1@cerner.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @DP044946.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @DP044946.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by cernerpradeep** [comment]
I created a new branch for HZN-629. Changes related to 629 will only be pushed from that branch. Hence closing this PR.

**Pull request closed without merging**
