### PR TITLE
NMS-13125: user ID and group ID must not contain any HTML markup

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-13125

### CODE REVIEW

**Review by RangerRick — COMMENTED** [review]
It doesn't appear you ended up using any of the `import org.opennms.core.utils.WebSecurityUtils` bits that were added, is that right?

**Comment by christianpape** [comment]
> It doesn't appear you ended up using any of the `import org.opennms.core.utils.WebSecurityUtils` bits that were added, is that right?

You're right. I removed these unused imports.

**Review by RangerRick — APPROVED** [review]
LGTM, I like that you're doing the validation in both the UI _and_ the backend.

**Comment by RangerRick** [comment]
I wonder if we should backport this to earlier foundation branches though, seems like this stuff is likely relevant there too.

**Pull request merged**
