### PR TITLE
BSM-51: Implementation for hierarchy layout of topology map

### PR DESCRIPTION
**Pull request by muratyildiz1976**
Implemented an algorithm to transform a layout (e.g. circle layout) to a hierarchy layout.

Jira: http://issues.opennms.org/browse/BSM-51
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS250

### CODE REVIEW

**Comment by indigo423** [comment]
@muratyildiz1976 is develop the right target?

**Comment by muratyildiz1976** [comment]
yes i think so

**Comment by indigo423** [comment]
You can fix it by closing this pull request and create a new one against the correct target branch.

**Comment by muratyildiz1976** [comment]
where it should be merged to ?

**Comment by muratyildiz1976** [comment]
Okay thanks, i will close this and change the target

**Comment by indigo423** [comment]
no problem. :tada:

**Comment by muratyildiz1976** [comment]
This pull request has to be closed because accidently the develop branch was selected as target.

**Comment by muratyildiz1976** [comment]
Hi Ronny,

den Branch features/BSM finde ich aber nirgends

Gruß,
Murat

**Comment by muratyildiz1976** [comment]
jetzt habe ich features/bsm gefunden ich merge da jetzt rein

**Pull request closed without merging**
