### PR TITLE
NMS-10313 : Be able to use Proxy for any Monitor or Collector that uses HttpClient via UrlFactory

### PR DESCRIPTION
**Pull request by patrick-schweizer**
* JIRA: https://issues.opennms.org/browse/NMS-10313

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by j-white** [comment]
Also looks good. Again, we should update the relevant documentation.

**Comment by patrick-schweizer** [comment]
@j-white I added documentation

**Comment by agalue** [comment]
This appear to cover only the XML Collector. Is this correct ? Is that the only feature that has to be tested ?

**Comment by j-white** [comment]
Looks fine to me. Having it as part of the request object seems more natural since that's where the other HTTP settings are set.

**Comment by agalue** [comment]
Of course, maybe tuning the docs to be more precise about where to put the flag would be useful.

**Comment by patrick-schweizer** [comment]
@agalue I updated the documentation. Could you take a look? Thanks!

**Comment by agalue** [comment]
Looks good, but I would additionally add a small note to say something like: 

The request parameters are optional. On the above example, `use-system-proxy` is one of the available parameters that can be used. This one is to let the XML Collector know that it should send the requests through the system Proxy.

Maybe not with those words, but you get the idea.

This is because the other valid parameters are not documented ;)

**Comment by patrick-schweizer** [comment]
@agalue I added documentation for all parameters. That should make it clearer. Could you take another look? Thanks!

**Comment by patrick-schweizer** [comment]
@agalue , @j-white are we good to merge? Or is there still something open? Cheers Patrick

**Pull request merged**
