### PR TITLE
NMS-9830: Plugin install fails

### PR DESCRIPTION
**Pull request by gallenc**
Fix for issue
https://issues.opennms.org/browse/NMS-9830 Plugin install fails

Updates OpenNMS to use new version of plugin manager (1.0.6) which has fix for this bug
The original bug was caused with the upgrade to karaf 4.x which now throws an UnsupportedOperationException when 
org.apache.karaf.features.FeaturesService. validateRepository(url) is called

build completes successfully in Bamboo
https://bamboo.opennms.org/browse/OPENNMS-ONMS2027/latest

### CODE REVIEW

**Comment by j-white** [comment]
Can we increase the test coverage for this feature to help prevent problems like this from reoccurring?

**Comment by gallenc** [comment]
I added some smoke tests to ensure plugins can be loaded and unloaded.

since this pul  equest was created an integration test started failing due to february date wrap.  request created 
https://github.com/OpenNMS/opennms/commits/df26a8dd0e0fd93f3945ddaa8447122cf80a251b/features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

**Comment by gallenc** [comment]
i have added smoke tests to install and uninstall a plugin.

the failing integration test is unrelated and due to date wrap issues in february fixed in develop 9 days ago by Seth.
see https://github.com/OpenNMS/opennms/commits/df26a8dd0e0fd93f3945ddaa8447122cf80a251b/features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

**Comment by gallenc** [comment]
closed by mistake :)

**Comment by j-white** [comment]
@gallenc Thanks for writing that test. This will help make sure we don't break this inadvertently again.

The failing integration test you referenced was also fixed in the `release-21.0.4` branch.

Do you see any issues with targeting this to `release-21.0.4` instead of `develop`? I'd be nice to address this in the next point release as opposed to waiting for the next major.

**Comment by gallenc** [comment]
Hi
Yes this should work in 21.0.4 no problem and also should be back portable
to latest meridian  . Do you need me to do anything more or can you apply
the fix to  21.0.4 ?

Thanls
Craig

**Comment by j-white** [comment]
I've cherry-picked your changes to `jira/NMS-9830-bp`, when that build passes I'll go ahead and merge it to `release-21.0.4`.

**Comment by j-white** [comment]
Fixed in `release-21.0.4`.

**Pull request closed without merging**
