### PR TITLE
HZN-1263: Make "delete existing rules" optional when importing rules …

### PR DESCRIPTION
**Pull request by patrick-schweizer**
https://issues.opennms.org/browse/HZN-1263

### CODE REVIEW

**Comment by RangerRick** [comment]
@patrick-schweizer Looks like the test you added is failing in Bamboo... had a chance to look at it yet?

**Comment by patrick-schweizer** [comment]
@RangerRick thanks for the reminder 8-) will check now..

**Comment by patrick-schweizer** [comment]
@mvrueden could you take a look please? Thanks!

**Comment by mvrueden** [comment]
LGTM 👍

**Pull request merged**
