### PR TITLE
NMS-9427: Fixed NPE in Vaadin dashboard

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-9427

### CODE REVIEW

**Comment by mvrueden** [comment]
Shouldn't we provide a test for this?!

**Comment by mvrueden** [comment]
Looks good to me, if bamboo passes, this can be merged.

**Comment by mvrueden** [comment]
Does this also occurr in foundation-2017? If can we retarget it?

**Comment by christianpape** [comment]
The ResourceId changes are not in foundation-2017. So, this can't be applied for foundation-2017.

**Pull request merged**
