### PR TITLE
XmpDetector and associated files plus enhancement to IpInterfaceScan for ipmatch string matching.

### PR DESCRIPTION
**Pull request by rdkgit**
Todo:
- [x] OCA signed
- [ ] Split in two issues
- [ ] Review
- [ ] Pass unit tests
- [ ] Merge and close JIRA issue

### CODE REVIEW

**Comment by indigo423** [comment]
@rdkgit is it possible to split the two enhancements in two pull requests? One pull request for the "XmpDetector enhancement" and second one for the "InterfaceScan ipmatch string matching". I can create the JIRA issues for this topics.

Thank you for your contribution.

**Comment by rdkgit** [comment]
Hi!

Looks like someone already applied the string tweak to IpInterfaceScan class.

I'm not sure I know how to do a pull request for just the detector. I'm a scientist not a software engineer!!  Seriously, if you can guide me, I'll submit the separate pull request.

Thanks,

Bobby

**Comment by indigo423** [comment]
@rdkgit as long as you're a Fookin' Rocket Scientist no problem :) I'll try to work through your pull request. Thank you for the fast feedback.

**Comment by rdkgit** [comment]
Hi!

Hey, I do need to learn more about working and playing well with others via git so I'd love to learn how to do that.  I have much larger onms contribution plans viz a viz my cartographer project.  I'm fixing to write a proposal doc to circulate around for you guys to look over.

Thanks,

Bobby

**Comment by indigo423** [comment]
Hey there, sorry for the delay. I would do the following steps to recreate a new pull request with just the new XMP detector:
1. Create a JIRA issue. If you don't have JIRA account you can skip this one. Easy to add later
2. You've forked OpenNMS to your private repo. Make a branch from develop with a title something like "Create detector for XMP"
3. You did already some work in your develop branch. If your commits are granular enough, you can cherry-pick commits by the hash id to your new branch. In worst case you have to redo the job manually in your new created branch.
4. Create a new pull request from your new branch to opennms/develop
5. We can then close this issue with a reference to your new pull request

Hope it helps, please let me know if the explanation was to short. Have a nice evening.

**Comment by indigo423** [comment]
This pull request is closed unmerged and reopened just with the XMP detector in #215.

**Pull request closed without merging**
