### PR TITLE
NMS-13323: Use HTTPS for all repository URLs

### PR DESCRIPTION
**Pull request by fooker**
### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13323

### CODE REVIEW

**Comment by RangerRick** [comment]
Can't do this until maven is on https  :)

**Comment by fooker** [comment]
> Can't do this until (opennms) maven is on https :)

For sure. There is an issue to https://issues.opennms.org/browse/ITOPS-230 to change this.

**Comment by fooker** [comment]
Also depending on https://github.com/OpenNMS/rancid-api/pull/1

**Review by RangerRick — APPROVED** [review]
looks good to me, and looks like it passed! 👍

**Pull request merged**
