### PR TITLE
NMS-12155: Group Duty Schedules Formatting Issues

### PR DESCRIPTION
**Pull request by cgorantla**
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12155
* Bamboo (Continuous Integration): https://bamboo.opennms.org/

### CODE REVIEW

**Comment by cgorantla** [comment]
Screenshot from 2019-07-11 17-12-40
Screenshot from 2019-07-11 17-04-30

**Comment by cgorantla** [comment]
Fix for group duty schedule page

Screenshot from 2019-07-11 17-04-30

**Comment by j-white** [comment]
Is `develop` the right target branch here?

**Comment by cgorantla** [comment]
#2581 should handle this for foundation-2018

**Comment by cgorantla** [comment]
Updated PR to reflect what should be fixed in develop.  #2581 should handle other issues

**Pull request merged**
