### PR TITLE
NMS-7991: Create Documentation for PageSequenceMonitor

### PR DESCRIPTION
**Pull request by reissmann**
- Created parameter description - please check for completeness
- Created simple example
- Created example n session variables
- Created example on per-page response time

JIRA: http://issues.opennms.org/browse/NMS-7991

Todo Review:
- [ ] Typo and grammar
- [ ] Formatting and conventions
- [ ] Content

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome @reissmann.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @reissmann.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @reissmann.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @reissmann.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by indigo423** [comment]
This issue is duplicated with http://issues.opennms.org/browse/HZN-151.

**Comment by indigo423** [comment]
The full list for missing monitors can be found here: http://issues.opennms.org/browse/HZN-95

**Comment by mvrueden** [comment]
Hey @indigo423 can you please explain what "This is issue is duplicated" and "The full list of missing documentation can be found here" means to @reissmann. Is there anything to do? Is something wrong with this Pull Request? Please enlighten us :)

**Comment by indigo423** [comment]
@mvrueden have you clicked on the link behind "here" and really looked at the issue including the tasks?! There is an already working branch, they have both to be merged.

**Comment by indigo423** [comment]
The contribution of this pull request is merged with the existing working branch and is reflected in PR #464.

**Pull request closed without merging**
