### PR TITLE
NMS-12866: Only show non-perspective outages in recent outages

### PR DESCRIPTION
**Pull request by fooker**
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12866

This filters out the non-perspective outages from the recent outages view and added some minor improvements/fixes to the outages lists.

### CODE REVIEW

**Review by christianpape — APPROVED** [review]
Nice.

**Comment by indigo423** [comment]
Tested the feature and is much better now. The only thing I've noticed, we derrive from the normal and introduce "Grey" as UP. This is it consistent with the rest of the UI as we show UP things in Green :)

Screenshot 2020-09-03 at 14 26 09

For others, here some screenshots how it is shown on Interface and Node level

Screenshot 2020-09-03 at 14 30 11

Screenshot 2020-09-03 at 14 27 08

Screenshot 2020-09-03 at 14 30 07

**Review by indigo423 — CHANGES_REQUESTED** [review]
enjoy-the-little-things

**Comment by fooker** [comment]
> Tested the feature and is much better now. The only thing I've noticed, we derrive from the normal and introduce "Grey" as UP. This is it consistent with the rest of the UI as we show UP things in Green :)

Down=Red and Up=Grey mimics the behavior from the Recent Outages list on the same page.

**Review by indigo423 — COMMENTED** [review]
Regarding the color thing, just a suggestion and not a blocker for me.

**Pull request merged**
