### PR TITLE
NMS-10554: Added more information to nodeDeleted event

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-10554

### CODE REVIEW

**Review by mfuhrmann — COMMENTED** [review]
@christianpape Is there no need to change the event `uei.opennms.org/nodes/nodeDown` as suggested in https://issues.opennms.org/browse/NMS-10554 ?
The idea was to give the user a chance to understand what happened.

**Comment by christianpape** [comment]
> @christianpape Is there no need to change the event `uei.opennms.org/nodes/nodeDown` as suggested in https://issues.opennms.org/browse/NMS-10554 ?
> The idea was to give the user a chance to understand what happened.

nodeDown event? You mean nodeDeleted, right? Yeah, I can add these changes.

**Comment by mfuhrmann** [comment]
@christianpape Yes. Meant `nodeDeleted` :grin: Thanks for adding it.

**Comment by mfuhrmann** [comment]
I can't check if the code is correctly, but the usability improvement is given. :+1:

**Review by mfuhrmann — APPROVED** [review]

**Review by fooker — APPROVED** [review]

**Pull request merged**
