### PR TITLE
NMS-13079: Changed version for frontend-maven-plugin to 1.11.0 to fix compilation 404 error

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-13079

### CODE REVIEW

**Comment by RangerRick** [comment]
what's the 404? specifically a develop version difference, or should this go back to `foundation-2019`?

**Comment by RangerRick** [comment]
Oh I see, M1 only.  :D

Probably still worth backporting.

**Review by RangerRick — APPROVED** [review]

**Comment by opennms-bamboo** [comment]
Welcome CI/CD System (cicd-system@opennms.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username CI/CD System (cicd-system@opennms.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](https://wiki.opennms.org/wiki/images/6/6b/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit https://wiki.opennms.org/wiki/Contributor_Agreement

**Comment by christianpape** [comment]
Sorry, hit the close button.

**Comment by christianpape** [comment]
Rebased to foundation-2019

**Pull request merged**
