### PR TITLE
xml collect docs heading fix

### PR DESCRIPTION
**Pull request by mmahacek**
"Configuration and use" section appears twice

### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* Jira (Issue Tracker): No Jira

### CODE REVIEW

**Review by garcia-sr — APPROVED** [review]
Reviewed the updates to the XML collector page. LGTM.

**Review by Bonrob2 — APPROVED** [review]
LGTM!

**Comment by ProjectJYL** [comment]
the collector is expected to work with a file url besides a HTTP endpoint. Is this something we can make visible to the docs as well? A short blurb or an example?

**Comment by mmahacek** [comment]
> the collector is expected to work with a file url besides a HTTP endpoint. Is this something we can make visible to the docs as well? A short blurb or an example?

Is it? I thought I had looked at it and didn't see file system support. (happy to be proven wrong)

**Comment by ProjectJYL** [comment]
I thought it was not supported until I saw the example in this [commit](https://github.com/OpenNMS/opennms/pull/5087/commits/341c7688419dd0e17ccb54def11bb895fff8dbae) that's opened a few months back. There is an example using file url. Then, I just tested it myself yesterday with my own example and the result was positive.

**Comment by RangerRick** [comment]
> Is it? I thought I had looked at it and didn't see file system support. (happy to be proven wrong)

Ain't no rules says a dog can't play basketball.

**Comment by mmahacek** [comment]
Replaced by https://github.com/OpenNMS/opennms/pull/6134

**Pull request closed without merging**
