### PR TITLE
HZN-616: add Debian packages for Minion

### PR DESCRIPTION
**Pull request by RangerRick**
This PR adds a Debian package for the Minion. ([JIRA](http://issues.opennms.org/browse/HZN-616))

* more refactoring of common "build" stuff into a script that both the Debian and RPM builds can use
* create a `debian/` directory that contains the Debian-specific Minion build stuff
* rearranges the directories with symlinks to better match Debian policy:
  * Minion root: `/usr/share/minion`
  * etc: `/etc/minion`
  * data: `/var/lib/minion/data`
  * deploy: `/var/lib/minion/deploy`
  * logs: `/var/log/minion/`
* modify `makedeb.sh` to also build the Minion package

### CODE REVIEW

**Comment by j-white** [comment]
Here's a few things I noticed on a first pass:

#### 1) The ssh keys aren't generated properly by the packages

```
$ ls -alh /etc/minion/host.key*
-rw-r--r-- 1 root root 0 May  1 14:52 /etc/minion/host.key
```
This leads to errors when connecting via SSH:

```
$ ssh -v -p 8201  admin@localhost
...
Unable to negotiate with 127.0.0.1 port 8201: no matching host key type found. Their offer: ssh-dss
```
#### 2) The package hierarchy is different than the RPMs

In the RPMs we split the container and the various feature repositories, whereas there are all bundled together here.

Each approach has its pros and cons, but I feel like we should at least make it consitent.

#### 3) Docs

We should update the installation guide with a similar section for Debian.

See http://docs.opennms.org/opennms/branches/jira-HZN-616/guide-install/guide-install.html#gi-install-minion-rhel.

#### 4) Non-root support

In the RPM packages we added support for running as non-root, but continue to use the `root` user by default since CentOS/RHEL 7 are using Kernel versions prior to `3.11`.

I don't think this is the case for most Debian  based distributions, so perhaps we should consider making the service run as the `minion` user by default.

**Comment by RangerRick** [comment]
Still need to update the docs, but I think I got a handle on the packaging and non-root support.

```
ranger@debian-8-amd64:/tmp/debs$ lintian *.deb; sudo dpkg -i *.deb
N: 106 tags overridden (4 errors, 102 warnings)
(Reading database ... 49348 files and directories currently installed.)
Preparing to unpack opennms-minion_20.0.0-0.20170503.onms1501.jira.hzn.616.21_all.deb ...
Unpacking opennms-minion (20.0.0-0.20170503.onms1501.jira.hzn.616.21) over (20.0.0-0.20170503.onms1501.jira.hzn.616.20) ...
Preparing to unpack opennms-minion-container_20.0.0-0.20170503.onms1501.jira.hzn.616.21_all.deb ...
Unpacking opennms-minion-container (20.0.0-0.20170503.onms1501.jira.hzn.616.21) over (20.0.0-0.20170503.onms1501.jira.hzn.616.20) ...
Preparing to unpack opennms-minion-features-core_20.0.0-0.20170503.onms1501.jira.hzn.616.21_all.deb ...
Unpacking opennms-minion-features-core (20.0.0-0.20170503.onms1501.jira.hzn.616.21) over (20.0.0-0.20170503.onms1501.jira.hzn.616.20) ...
Preparing to unpack opennms-minion-features-default_20.0.0-0.20170503.onms1501.jira.hzn.616.21_all.deb ...
Unpacking opennms-minion-features-default (20.0.0-0.20170503.onms1501.jira.hzn.616.21) over (20.0.0-0.20170503.onms1501.jira.hzn.616.20) ...
Setting up opennms-minion-container (20.0.0-0.20170503.onms1501.jira.hzn.616.21) ...
Installing new version of config file /etc/minion/profile.cfg ...
Attempting to configure sysctl to allow ping as non-root (net.ipv4.ping_group_range=0-116).
This might need a reboot before this takes effect.
Setting up opennms-minion-features-core (20.0.0-0.20170503.onms1501.jira.hzn.616.21) ...
Setting up opennms-minion-features-default (20.0.0-0.20170503.onms1501.jira.hzn.616.21) ...
Setting up opennms-minion (20.0.0-0.20170503.onms1501.jira.hzn.616.21) ...
Processing triggers for systemd (215-17+deb8u6) ...
ranger@debian-8-amd64:/tmp/debs$ sudo sysctl -a | grep ping_group
net.ipv4.ping_group_range = 0	116
ranger@debian-8-amd64:/tmp/debs$ sudo service minion start
ranger@debian-8-amd64:/tmp/debs$ sudo systemctl status minion
● minion.service - LSB: OpenNMS Minion
   Loaded: loaded (/etc/init.d/minion)
   Active: active (running) since Wed 2017-05-03 13:20:41 EDT; 4s ago
  Process: 21534 ExecStart=/etc/init.d/minion start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/minion.service
           ├─21694 /bin/bash /usr/share/minion/bin/karaf server
           └─21742 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -XX:+HeapDumpOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -Djava.endorsed.dirs=/usr/l...

May 03 13:20:41 debian-8-amd64 runuser[21534]: pam_unix(runuser:session): session opened for user minion by (uid=0)
May 03 13:20:41 debian-8-amd64 systemd[1]: Started LSB: OpenNMS Minion.
```

👍

**Comment by RangerRick** [comment]
Alright, documentation added.  Lemme know what you think, @j-white.

**Comment by j-white** [comment]
I gave this another go, and everything is working great :+1:

Should be good to merge unless anyone else has any feedback.

**Pull request merged**
