### PR TITLE
NMS-12299: add/update service files for systemd

### PR DESCRIPTION
**Pull request by RangerRick**
This PR is based on https://github.com/OpenNMS/opennms/pull/2720 -- do not merge it until the other is merged first.

### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [x] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12299
* Bamboo (Continuous Integration): https://bamboo.opennms.org/

### CODE REVIEW

**Comment by RangerRick** [comment]
> After installing on Ubuntu, the `opennms.service` I would expect the service unit file on Ubuntu on `/lib/systemd/system` cause it hasn't completed the [/usr merge](https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/) and on CentOS7 in `/usr/lib/systemd/system` as described for a location for unit files coming from installed packages from [here](https://www.freedesktop.org/software/systemd/man/systemd.unit.html):
> 
> > /usr/lib/systemd/system: System units installed by the distribution package manager

On Debian they end up wherever debhelper puts them so I'm assuming they're in the "right" place.

> Why do we call `/etc/init.d/opennms` as a link and not directly `{/usr/share,/opt}/opennms/bin/opennms` in the unit file?

Because it's complicated to handle the "defaults" stuff easily direct from the service file and this way we know the other setup/environmental things that happen in normal init happen there too.

**Comment by j-white** [comment]
Gave these a whirl, ran into this:
{noformat}
# systemctl start minion
Job for minion.service failed because a timeout was exceeded. See "systemctl status minion.service" and "journalctl -xe" for details.
[root@minion minion]# systemctl status minion.service
● minion.service - The OpenNMS Minion distributed client.
   Loaded: loaded (/usr/lib/systemd/system/minion.service; disabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Wed 2019-09-25 17:30:36 CEST; 12s ago
  Process: 2764 ExecStart=/etc/init.d/minion start (code=exited, status=0/SUCCESS)

Sep 25 17:29:02 minion.informatik.hs-fulda.de systemd[1]: Starting The OpenNMS Minion distributed client....
Sep 25 17:29:09 minion.informatik.hs-fulda.de minion[2764]: /etc/init.d/minion: line 188: /opt/minion/log/minion.pid: No such file or directory
Sep 25 17:29:09 minion.informatik.hs-fulda.de systemd[1]: Can't open PID file /opt/minion/log/minion.pid (yet?) after start: No such file or directory
Sep 25 17:30:32 minion.informatik.hs-fulda.de systemd[1]: minion.service start operation timed out. Terminating.
Sep 25 17:30:36 minion.informatik.hs-fulda.de systemd[1]: Failed to start The OpenNMS Minion distributed client..
Sep 25 17:30:36 minion.informatik.hs-fulda.de systemd[1]: Unit minion.service entered failed state.
Sep 25 17:30:36 minion.informatik.hs-fulda.de systemd[1]: minion.service failed.
{noformat}

**Comment by indigo423** [comment]
> > After installing on Ubuntu, the `opennms.service` I would expect the service unit file on Ubuntu on `/lib/systemd/system` cause it hasn't completed the [/usr merge](https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/) and on CentOS7 in `/usr/lib/systemd/system` as described for a location for unit files coming from installed packages from [here](https://www.freedesktop.org/software/systemd/man/systemd.unit.html):
> > > /usr/lib/systemd/system: System units installed by the distribution package manager
> 
> On Debian they end up wherever debhelper puts them so I'm assuming they're in the "right" place.
> 
> > Why do we call `/etc/init.d/opennms` as a link and not directly `{/usr/share,/opt}/opennms/bin/opennms` in the unit file?
> 
> Because it's complicated to handle the "defaults" stuff easily direct from the service file and this way we know the other setup/environmental things that happen in normal init happen there too.

Thanks for the explanation, make sense to me was no blocker for me just curious :)

**Comment by indigo423** [comment]
> Sep 26 12:19:54 localhost.localdomain sentinel[27448]: /etc/init.d/sentinel: line 188: /opt/sentinel/log/sentinel.pid: No such file or directory

There is no `/opt/sentinel/log` directory. Logs are in `/opt/sentinel/data/log`.

**Comment by RangerRick** [comment]
Yeah, much as I'd like to see this get in, it needs to wait for the next release.  I'll look at this more for 25.1.0.

**Comment by indigo423** [comment]
On Ubuntu the Minion works but the error message on Sentinel is different:

```
root@vagrant:/usr/share/opennms/bin# journalctl -u sentinel
-- Logs begin at Thu 2019-09-26 12:48:39 UTC, end at Thu 2019-09-26 13:36:44 UTC. --
Sep 26 13:36:44 vagrant systemd[1]: Starting The OpenNMS Sentinel distributed client....
Sep 26 13:36:44 vagrant sentinel[24551]: /etc/init.d/sentinel: 43: /etc/init.d/sentinel: /bin/find-java.sh: not found
Sep 26 13:36:44 vagrant sentinel[24551]: /etc/init.d/sentinel: 174: /etc/init.d/sentinel: /bin/ensure-user-ping.sh: not found
Sep 26 13:36:44 vagrant systemd[1]: sentinel.service: Control process exited, code=exited status=4
Sep 26 13:36:44 vagrant systemd[1]: sentinel.service: Failed with result 'exit-code'.
Sep 26 13:36:44 vagrant systemd[1]: Failed to start The OpenNMS Sentinel distributed client..
```

**Comment by indigo423** [comment]
Should be tested as well, restart the Minion when the broker is not working.

**Comment by RangerRick** [comment]
Alright, as far as I can tell, all standing issues with these packages on centos and debian are fixed.  A number of small things conspired to make them fail, and I think I have all cases handled now.  @indigo423 lemme know if everything works for you now.

**Comment by indigo423** [comment]
Test plan:

## DEB Packages Ubuntu
- [ ] Test systemctl start / stop opennms, minion, sentinel
- [ ] Test systemctl status opennms, minion, sentinel
- [ ] Test running and saved PID for opennms, minion, sentinel

## RPM Packages CentOS 7
- [ ] Test systemctl start / stop opennms, minion, sentinel
- [ ] Test systemctl status opennms, minion, sentinel
- [ ] Test running and saved PID for opennms, minion, sentinel

**Comment by indigo423** [comment]
When I try to stop the Minion with `systemctl stop minion` I get the following error message:

```
root@frr-01:/usr/share/minion# journalctl -u minion
-- Logs begin at Thu 2019-10-10 16:03:23 UTC, end at Fri 2019-10-11 16:14:26 UTC. --
Oct 11 16:11:02 frr-01 systemd[1]: Starting LSB: OpenNMS Minion...
Oct 11 16:11:02 frr-01 systemd[1]: Started LSB: OpenNMS Minion.
Oct 11 16:13:26 frr-01 systemd[1]: Stopping LSB: OpenNMS Minion...
Oct 11 16:13:32 frr-01 minion[15432]: Stopping Minion: Can't connect to the container. The container is not running.
Oct 11 16:13:38 frr-01 minion[15432]: Can't connect to the container. The container is not running.
Oct 11 16:13:44 frr-01 minion[15432]: Can't connect to the container. The container is not running.
Oct 11 16:13:50 frr-01 minion[15432]: Can't connect to the container. The container is not running.
Oct 11 16:13:56 frr-01 minion[15432]: Can't connect to the container. The container is not running.
Oct 11 16:14:02 frr-01 minion[15432]: Can't connect to the container. The container is not running.
Oct 11 16:14:08 frr-01 minion[15432]: Can't connect to the container. The container is not running.
Oct 11 16:14:14 frr-01 minion[15432]: Can't connect to the container. The container is not running.
Oct 11 16:14:20 frr-01 minion[15432]: Can't connect to the container. The container is not running.
Oct 11 16:14:26 frr-01 minion[15432]: FAILED
Oct 11 16:14:26 frr-01 minion[15432]: Killing Minion: FAILED
Oct 11 16:14:26 frr-01 minion[15432]: Force-killing Minion: FAILED
Oct 11 16:14:26 frr-01 systemd[1]: minion.service: Control process exited, code=exited status=1
Oct 11 16:14:26 frr-01 systemd[1]: minion.service: Failed with result 'exit-code'.
Oct 11 16:14:26 frr-01 systemd[1]: Stopped LSB: OpenNMS Minion.
```

**Comment by indigo423** [comment]
DEB-Packages: When I try to stop the Sentinel with systemctl stop sentinel it takes quit a long time a I get the following error message:

root@frr-01:/usr/share/sentinel/etc# journalctl -u sentinel
-- Logs begin at Thu 2019-10-10 16:03:23 UTC, end at Fri 2019-10-11 16:25:01 UTC. --
Oct 11 16:21:11 frr-01 systemd[1]: Starting LSB: OpenNMS Sentinel...
Oct 11 16:21:11 frr-01 runuser[18650]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:21:11 frr-01 runuser[18650]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:21:11 frr-01 runuser[18653]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:21:11 frr-01 runuser[18653]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:21:11 frr-01 systemd[1]: Started LSB: OpenNMS Sentinel.
Oct 11 16:23:50 frr-01 systemd[1]: Stopping LSB: OpenNMS Sentinel...
Oct 11 16:23:51 frr-01 runuser[19059]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:23:51 frr-01 runuser[19059]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:23:51 frr-01 runuser[19061]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:23:52 frr-01 runuser[19061]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:23:57 frr-01 runuser[19145]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:23:57 frr-01 runuser[19145]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:23:57 frr-01 runuser[19147]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:23:59 frr-01 sentinel[18877]: Stopping Sentinel: Can't connect to the container. The container is not runnin
Oct 11 16:23:59 frr-01 runuser[19147]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:04 frr-01 runuser[19231]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:04 frr-01 runuser[19231]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:04 frr-01 runuser[19233]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:05 frr-01 sentinel[18877]: Can't connect to the container. The container is not running.
Oct 11 16:24:05 frr-01 runuser[19233]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:10 frr-01 runuser[19317]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:10 frr-01 runuser[19317]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:10 frr-01 runuser[19319]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:12 frr-01 sentinel[18877]: Can't connect to the container. The container is not running.
Oct 11 16:24:12 frr-01 runuser[19319]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:17 frr-01 runuser[19402]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:17 frr-01 runuser[19402]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:17 frr-01 runuser[19404]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:18 frr-01 sentinel[18877]: Can't connect to the container. The container is not running.
Oct 11 16:24:19 frr-01 runuser[19404]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:24 frr-01 runuser[19487]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:24 frr-01 runuser[19487]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:24 frr-01 runuser[19489]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:25 frr-01 sentinel[18877]: Can't connect to the container. The container is not running.
Oct 11 16:24:25 frr-01 runuser[19489]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:30 frr-01 runuser[19573]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:30 frr-01 runuser[19573]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:30 frr-01 runuser[19575]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:32 frr-01 sentinel[18877]: Can't connect to the container. The container is not running.
Oct 11 16:24:32 frr-01 runuser[19575]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:37 frr-01 runuser[19658]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:37 frr-01 runuser[19658]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:37 frr-01 runuser[19660]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:39 frr-01 sentinel[18877]: Can't connect to the container. The container is not running.
Oct 11 16:24:39 frr-01 runuser[19660]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:44 frr-01 runuser[19743]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:44 frr-01 runuser[19743]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:44 frr-01 runuser[19745]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:46 frr-01 sentinel[18877]: Can't connect to the container. The container is not running.
Oct 11 16:24:47 frr-01 runuser[19745]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:52 frr-01 runuser[19829]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:52 frr-01 runuser[19829]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:52 frr-01 runuser[19831]: pam_unix(runuser:session): session opened for user sentinel by (uid=0)
Oct 11 16:24:53 frr-01 sentinel[18877]: Can't connect to the container. The container is not running.
Oct 11 16:24:54 frr-01 runuser[19831]: pam_unix(runuser:session): session closed for user sentinel
Oct 11 16:24:59 frr-01 sentinel[18877]: FAILED
Oct 11 16:24:59 frr-01 sentinel[18877]: Killing Sentinel: FAILED
Oct 11 16:24:59 frr-01 sentinel[18877]: Force-killing Sentinel: OK
Oct 11 16:24:59 frr-01 systemd[1]: Stopped LSB: OpenNMS Sentinel.
```

The Sentinel is started and I cannot connect to the Karaf shell. Checked with `ss -lnpt sport = :8301` and no TCP port listening. The Karaf is running as a process and `systemctl status sentinel` reports correctly status running. When I use the `/usr/share/sentinel/bin/start` command the Karaf shell is available and I can connect.

**Comment by RangerRick** [comment]
Hrm, weird, that sounds a lot like the previous packages' bug.  Can you give me the output of `systemctl status sentinel` and `dpkg -l opennms-sentinel` ?

**Comment by indigo423** [comment]
> Hrm, weird, that sounds a lot like the previous packages' bug. Can you give me the output of `systemctl status sentinel` and `dpkg -l opennms-sentinel` ?

Yes I'll do. Just because you mention the packages bug. I'll verify by installing with manual download and dpkg as you mentioned to rule out the repo issue.

**Comment by indigo423** [comment]
When I try to stop the Minion on Debian, it is going to be force killed by systemd.

Status and PID when Minion is running:
```
root@frr-01:~# systemctl status minion
● minion.service - The OpenNMS Minion distributed client.
   Loaded: loaded (/lib/systemd/system/minion.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-10-12 18:09:27 UTC; 4min 59s ago
  Process: 28857 ExecStop=/etc/init.d/minion stop (code=exited, status=0/SUCCESS)
  Process: 29314 ExecStart=/etc/init.d/minion start (code=exited, status=0/SUCCESS)
 Main PID: 29579 (java)
    Tasks: 141 (limit: 2261)
   CGroup: /system.slice/minion.service
           ├─29533 /bin/sh /usr/share/minion/bin/karaf server
           └─29579 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xms128M -Xmx512M -XX:+UnlockDiagnosticVMOptions -Dcom.sun.management.jmxremote -XX:+HeapDumpOnOutOfMemoryError --add-reads=java.xml=java.logging --add-exports=java.base/org.a

Oct 12 18:09:21 frr-01 systemd[1]: Starting The OpenNMS Minion distributed client....
Oct 12 18:09:27 frr-01 systemd[1]: minion.service: Supervising process 29579 which is not our child. We'll most likely not notice when it exits.
Oct 12 18:09:27 frr-01 systemd[1]: Started The OpenNMS Minion distributed client..
```

Stopping the Minion:
```
root@frr-01:~# systemctl stop minion
root@frr-01:~# systemctl status minion
● minion.service - The OpenNMS Minion distributed client.
   Loaded: loaded (/lib/systemd/system/minion.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sat 2019-10-12 18:15:27 UTC; 1min 56s ago
  Process: 30169 ExecStop=/etc/init.d/minion stop (code=exited, status=0/SUCCESS)
  Process: 29314 ExecStart=/etc/init.d/minion start (code=exited, status=0/SUCCESS)
 Main PID: 29579

Oct 12 18:09:21 frr-01 systemd[1]: Starting The OpenNMS Minion distributed client....
Oct 12 18:09:27 frr-01 systemd[1]: minion.service: Supervising process 29579 which is not our child. We'll most likely not notice when it exits.
Oct 12 18:09:27 frr-01 systemd[1]: Started The OpenNMS Minion distributed client..
Oct 12 18:14:31 frr-01 systemd[1]: Stopping The OpenNMS Minion distributed client....
Oct 12 18:15:22 frr-01 minion[30169]: Stopping Minion: FAILED
Oct 12 18:15:27 frr-01 minion[30169]: Force-killing Minion: OK
Oct 12 18:15:27 frr-01 systemd[1]: minion.service: Killing process 29579 (n/a) with signal SIGKILL.
Oct 12 18:15:27 frr-01 systemd[1]: minion.service: Killing process 29579 (n/a) with signal SIGKILL.
Oct 12 18:15:27 frr-01 systemd[1]: Stopped The OpenNMS Minion distributed client..
```

**Comment by indigo423** [comment]
Sentinel on Debian works fine. 

```
Oct 13 14:13:10 frr-01 sentinel[32615]: Stopping Sentinel: OK
Oct 13 14:13:10 frr-01 systemd[1]: sentinel.service: Killing process 32473 (n/a) with signal SIGKILL.
Oct 13 14:13:10 frr-01 systemd[1]: sentinel.service: Killing process 32473 (n/a) with signal SIGKILL.
Oct 13 14:13:10 frr-01 systemd[1]: Stopped The OpenNMS Sentinel distributed client..
```
The only thing which looks fishy to me is, stopping the Minion on Debian fails.

**Comment by RangerRick** [comment]
I have seen this (needing to force-kill) with Minion as well in my testing, and I'm not convinced it's an issue with the startup/stop scripts.  If I look in the Karaf logs, I see the "shutdown" thread is triggered, but the JVM is never exiting.

When I was testing, my Minion wasn't actually hooked up to an OpenNMS so I chalked it up to failing to tear down cleanly because it didn't have a full connection to OpenNMS.  Were you doing the same in your testing, or did you have an actual running/working Minion?

**Comment by indigo423** [comment]
I can confirm, configured the Minion with a Horizon instance and stopping works fine:

```
Oct 14 14:43:23 frr-01 minion[38743]: Stopping Minion: OK
Oct 14 14:43:23 frr-01 systemd[1]: minion.service: Killing process 38110 (n/a) with signal SIGKILL.
Oct 14 14:43:23 frr-01 systemd[1]: minion.service: Killing process 38110 (n/a) with signal SIGKILL.
Oct 14 14:43:23 frr-01 systemd[1]: Stopped The OpenNMS Minion distributed client.
```

**Comment by RangerRick** [comment]
\o/

**Pull request merged**
