### PR TITLE
HZN-1307: Initial Sentinel work

### PR DESCRIPTION
**Pull request by mvrueden**
This PR implements changes to allow the telemetry daemon to be run within a standalone container (sentinel).

This is still WIP but I wanted to give everyone a chance to provide input early on.

# Stuff left TODO
- Remove TODOs
- provide documentation
- Make stuff nicer (e.g. the opennms-dataschema.xml and opennms-server.xml exposition below)
- Provide some kind of statistics/diagnostics, e.g. how many sentinels are started at the moment (similar to the minion heartbeat maybe)
- is `features/minion/core/repository` AND `features/minion/repository` needed, or can we merge this to `features/minion/repository`. 
- rework features definitions, especially all `opennms-telemetry-*` features to see if they are actually used or must be rewritten/removed

# How to setup a sentinel

## Sentinel Part
Ensure Java is installed: `java -version`.

Ensure JAVA_HOME is set: `echo $JAVA_HOME`, e.g. `export JAVA_HOME=/usr/lib/jvm/jdk-1.8.0/`

Start a raw apache-karaf-4.1.5 container and add the following repositories:
```
repo-add mvn:org.apache.karaf.features/spring/4.1.5/xml/features
repo-add mvn:org.opennms.karaf/opennms/22.0.0-SNAPSHOT/xml/karaf-extensions
repo-add mvn:org.opennms.karaf/opennms/22.0.0-SNAPSHOT/xml/features
repo-add mvn:org.opennms.karaf/opennms/22.0.0-SNAPSHOT/xml/sentinel
```

Afterwards, install the following features:
```
# Scv is required for sentinel-jms
feature:install scv
# is required to read application-context files
feature:install opennms-spring-extender
# Is required for sentinel:ping, the Identity and possibility to configure the sentinel 
feature:install sentinel-core
# Required to load configurations remotely via HTTP from OpenNMS and 
# basically opennms-dao and opennms-dao-api including custom datasource configuration (see below)
feature:install sentinel-persistence

feature:install sentinel-jms
feature:install opennms-core-ipc-sink-camel-server
feature:install sentinel-telemetry
feature:install sentinel-flows
```

Afterwards a custom adapter can be started, like so:
```
admin@minion()> config:edit org.opennms.features.telemetry.adapters-netflow5
admin@minion()> config:property-set name Netflow-5
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.adapters.netflow.v5.Netflow5Adapter
admin@minion()> config:update
```
This will consume messages sent to `OpenNMS.Sink.Telemetry-Netflow-5`.

In case you need some custom configuration, refer to https://github.com/OpenNMS/opennms/blob/b5eecf62f3a7077c15ea25f3f61d20d420f618c3/features/sentinel/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L14-L24

To configure the datasource, refer to
https://github.com/OpenNMS/opennms/blob/49c02f2277d570aeda8c0312b1cf1b7a090568dc/features/distributed/datasource/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L16-L31

## Minion Part
At the moment a minion is always required to make use of the sentinel capabilities.
To do so, a listener must created

```
$ ssh -p 8201 admin@localhost
...
admin@minion()> config:edit org.opennms.features.telemetry.listeners-udp-8877
admin@minion()> config:property-set name Netflow-5
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.listeners.udp.UdpListener
admin@minion()> config:property-set listener.port 8877
admin@minion()> config:update
```
This will listen for udp packages on port `8877` and will sent it to `OpenNMS.Sink.Telemetry-Netflow-5`. 
Therefore the name here is not very crucial, BUT it must match with the name of the adapter on the sentinel, otherwise messages are not consumed properly.

Also note, that if there is the any adapter with a protocol name of `Netflow-5` in the `telemetryd-configuration.xml` defined in OpenNMS, OpenNMS will also consume messages sent by minions. This should not be a problem per se, but ensure that there is no listener defined, which also listens for udp packages, as those are not distributed, but only processed by opennms.

# Distributed Configuration

Each `AbstractJaxbConfigurationDao` now implements an interface `JaxbConfigDao` (module `core/xml`). With the also new annotation `@ConfigProxy` it is possible to mark an `JaxbConfigurationDao` implementation to proxy requests to `getConfig()` (former `getContainer().getObject()`). The proxied request is performing an HTTP GET Request against the OpenNMS Rest API `/opennms/rest/config` to fetch the config from there instead of doing a local lookup). 
See `ConfigRestService` and `ConfigProxyAnnotationBeanPostProcessor` for details on how this is implemented.
In order to make use of this new functionality, a DAO must implement an interface and also have the `@ConfigProxy` annotation present. 
Besides that a bean of type `ConfigProxyAnnotationBeanPostProcessor` must be present in the current bundle scope. Please use the class `DefaultTelemetrydConfigDAO` and the respective module as reference.

# General Structure

**core/spring-extender**
This module is similar to the functionality from the gemini-blueprint project, but does not integrate with karaf that heavily. This module just listens for bundles with “Spring-Context” META-INF definitions and starts an application context from that bundle.
This allows us to re-use the functionality of gemini-blueprint, but are not required to remove aries-blueprint.

Another difference to gemini-blueprint is, that this bundle supports loading an spring application context from itself (required to bootstrap the ServiceRegistry)

Why do we need this?
Almost all modules which are at the moment only visible to the jetty classloader heavily rely on Spring. However those modules will not work out of the box inside a standalone karaf. To allow us to re-use the `applicationContext-*.xml` and also `component-*.xml` files, the `geminini-blueprint` project is used. 

In order to get it to work, some `applicationContext-*.xml` files have to be splitted. The idea is the following:
* e.g. `applicationContext-dao.xml` is loaded by OpenNMS
* e.g. `component-dao.xml` is loaded when running inside OpenNMS AND a distributable container such as sentinel or minion
 * e.g. `applicationContext-osgi.xml` is loaded when running inside a distributable container

A usual `applicationContext-osgi.xml` file would look something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:osgi="http://www.springframework.org/schema/osgi"
       xmlns:onmsgi="http://xmlns.opennms.org/xsd/spring/onms-osgi"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.2.xsd
          http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.2.xsd
          http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-4.2.xsd
          http://www.springframework.org/schema/osgi http://www.springframework.org/schema/osgi/spring-osgi.xsd
          http://xmlns.opennms.org/xsd/spring/onms-osgi http://xmlns.opennms.org/xsd/spring/onms-osgi.xsd">

     <!-- NOTE: Contains only Minion/Sentinel-specific beans -->

    <!-- Resolve references, which are usually provided by the OpenNMS Runtime Environment -->
    <osgi:reference id="serviceRegistry" interface="org.opennms.core.soa.ServiceRegistry" />

</beans>
```
The idea is, that it pulls in all required dependencies in order to load the bundle successfully. 
In most cases that is probably only the `ServiceRegistry`.

**features/sentinel**
All implementations specific to sentinel

**features/minion**
All implementations specific to minion

**container/features**
Contains all feature definitions for minion, sentinel, opennms

**features/distributed**
All modules which are shared between distributed containers, such as sentinel and minion.
A sub module is not intended to run inside the opennms’ karaf container.

**features/distributed/dao-api**
A module which merges (with maven-shade-plugin) all DAO APIs into one uber dao-api bundle.
For example the API modules of the persistence from bsm and classification as well as opennms-dao-api are merged here.

**features/distributed/dao-impl**
A module which merges all DAO implementations into one uber dao-impl bundle.
As all DAOs require the sessionFactory to be instantiated.
Until now the SessionFactory class was accessible via the system bundle. 
Therefore we need all DAO implementations to be in one bundle.
(The reason for this is, that the SessionFactory is not an interface).

An alternative to this could be to implement a SessionFactoryProvider interface which is used by the DAOs instead.
However this requires more code changes.

**features/distribution/dao-distributed**
This module contains DAO implementations which need to be slightly different than the ones shipped by OpenNMS.
At the moment only the DistPollerDAO is implemented here, to provide a custom “whoami()” implementation and throws a bunch of UnsupportedOperationExceptions for unsupported operations.

**features/distribution/config**
Contains the ConfigProxyAnnotationBeanPostProcessor which is required to proxy jaxb configuration objects

**features/distributed/datasource**
Exposes possibliity to configure the opennms datasource via an `org.opennms.netmgt.distributed.datasource.cfg` file.
Besides this it also exposes dummy configurations for `database-schema.xml` and  `opennms-server.xml`.
This should probably be changed at some point.

# Additional Changes
Besides the general structure mentioned above, the following changes have been implemented:

A new `Identity` interface was introduced to also add a `SystemType` (`Minion` | `Sentinel`). This `Identity` is only used by the new `DistPollerDaoDistributed` (former `DistPollerDaoMinion`).
The `MinionIdentity` interface is still available. In the long run, the `MinionIdentity` should be replaced with the new Identity concept.

Everything from `features/minion/core` was moved to `features/distributed/core` and is re-used by sentinel

At the moment each distributable container must provide at least the following services:
`Identity` (and optionally the `MinionIdentity` in case of a minion container). The `RestConfig` and if required an implementation of the `MinionPingCommand`/`SentinelPingCommand`. Refer to bundles `features/sentinel/core` or `features/minion/core/core-impl` for more details.

### CODE REVIEW

**Comment by j-white** [comment]
Nice work, getting this to work end to end isn't easy.

Is there some extra things I need to do in order for this to work in a vanilla Karaf instance? Following the instructions, I currently fail with:
```
2018-05-18 12:44:06,503 | ERROR | t Creation Timer | WaiterApplicationContextExecutor | 75 - spring-extender - 22.0.0.SNAPSHOT | Unable to create application context for [org.opennms.features.distributed.dao-imp
l], unsatisfied dependencies: Dependency on [(objectClass=javax.sql.DataSource)] (from bean [&dataSource]), Dependency on [(objectClass=org.opennms.netmgt.config.api.DatabaseSchemaConfig)] (from bean [&databaseS
chemaConfigFactory]), Dependency on [(objectClass=org.opennms.netmgt.config.api.OpennmsServerConfig)] (from bean [&opennmsServerConfig])
org.springframework.context.ApplicationContextException: Application context initialization for 'org.opennms.features.distributed.dao-impl' has timed out waiting for (|(objectClass=javax.sql.DataSource)(objectCl
ass=org.opennms.netmgt.config.api.DatabaseSchemaConfig)(objectClass=org.opennms.netmgt.config.api.OpennmsServerConfig))
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.timeout(DependencyWaiterApplicationContextExecutor.java:489) [75:spring-extender:22.0.0.S
NAPSHOT]
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.access$000(DependencyWaiterApplicationContextExecutor.java:54) [75:spring-extender:22.0.0
.SNAPSHOT]
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$WatchDogTask.run(DependencyWaiterApplicationContextExecutor.java:109) [75:spring-extender
:22.0.0.SNAPSHOT]
        at java.util.TimerThread.mainLoop(Timer.java:555) [?:?]
        at java.util.TimerThread.run(Timer.java:505) [?:?]
```

**Comment by j-white** [comment]
How do you want to proceed from here? Do you want to get this merged into `features/sentinel` and work on improving the different points and TODOs you've raised in there? Or do we tackle the different components one by one and get them merge them into `features/sentinel` and/or `develop` as we go?

**Comment by mvrueden** [comment]
On the issue you encountered:
As of now this is an issue, caused by some refactorings AFTER I opened this PR and must be addressed accordingly.

How to continue:
There are some refactorings required in develop in order to move forward and address most of the TODOs in this PR. One, for example is this already opened PR https://github.com/OpenNMS/opennms/pull/1994. Besides that most of the issues labeled as `sentinel` (https://issues.opennms.org/issues/?jql=labels%20%3D%20sentinel) should be worked on in `develop` before this can be merged. 

At that point we are probably already having the system tests to work, from where we can move on.

**Comment by mvrueden** [comment]
I updated the branch and documentation above, installing/starting it should work now.

**Comment by mvrueden** [comment]
I am going to close this. I created a branch `jira/HZN-1307` which will be used instead.

**Pull request closed without merging**
