### PR TITLE
HZN-1499: Added "ON DELETE CASCADE" to metadata liquibase changelog

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/HZN-1499

### CODE REVIEW

**Comment by j-white** [comment]
Looks good. Given that we're altering the existing migrations instead of adding a new one, can we provide instructions here on how to upgrade? We have some users running 24.0.0-SNAPSHOT, and `install -dis` will break for them when they upgrade with this patch.

**Comment by christianpape** [comment]
We can delete and recreate the constraint in another changeset. What do you think.

**Comment by j-white** [comment]
Either way works, we just need a solution that allows users to upgrade.

Manually running some SQL for the few that are running snapshots is OK.

**Comment by christianpape** [comment]
Created an additional changeset. So, upgrades will work...

**Pull request merged**
