### PR TITLE
NMS-8113: Whats new section in release notes

### PR DESCRIPTION
**Pull request by indigo423**
Introduced Whats New section for major releases and detailed changelogs for minor releases generated from JIRA. Removed requirements and known issues for the reason they are outdated and not maintained. Requirements are duplicated and should be covered in the install guide of OpenNMS.

Cleaned up placeholder files and cleaned up structure for high level overview in major versions and changelog details in minor versions. The content from WHATSNEW.md is migrated to whatsnew-17.adoc and is content of the main section of OpenNMS 17.

Fixed wrong syntax for anchors which can be used as internal reference.

JIRA: http://issues.opennms.org/browse/NMS-8113
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS459-2

### CODE REVIEW

**Comment by indigo423** [comment]
Unfortunately GitHub doesn't follow the link on WHATSNEW.adoc, it just shows the path to the file :/

**Comment by indigo423** [comment]
The result from this branch can be found here: http://docs.opennms.org/opennms/branches/NMS-8113/releasenotes/releasenotes.html

**Comment by indigo423** [comment]
@RangerRick what do you think about this change?

**Comment by RangerRick** [comment]
I'm cool with putting whatsnew in the release notes, but how did you resolve the symlink thing?  Should we just make a WHATSNEW.md that links to the release notes then?

**Comment by indigo423** [comment]
@RangerRick There is nothing I can do, if you click in GitHub on a symlink it will show the path to the target. If you checkout the code on hard disk, the link is resolved correctly. Can we live with something like that?

**Comment by RangerRick** [comment]
Sorry, that's not what I meant.  By "link" I meant, "leave WHATSNEW.md and have it literally contain only a markdown HTML link to the what's new that is in the docs directory."

**Comment by indigo423** [comment]
@RangerRick I got it, took a while to understand what you mean :) I've created the the what's new file with a relative link, so it should work nevertheless which branch you are.

**Comment by indigo423** [comment]
Basically we could add this link also directly to the READM.md which is shown directly. Just as a quick thought.

**Comment by soleger** [comment]
It only looks like the WHATSNEW content from OpenNMS 17 is included but there were also good WHATSNEW files for 14, 15, and 16. Can we link these into the release notes as well?

**Comment by indigo423** [comment]
@soleger good point. I've migrated the whats new files from 14, 15 and 16 and included them as well. So when you go to the release notes you have all in one document.

**Comment by soleger** [comment]
Hey Ronny, the commits look good! I'm going to run the branch one more time in Bamboo so that we can preview the latest commits on the docs site and then we can merge it.

**Pull request merged**
