### PR TITLE
jira/NMS-7542

### PR DESCRIPTION
**Pull request by christianpape**
Please review and merge fix for issue:
http://issues.opennms.org/browse/NMS-7542

### CODE REVIEW

**Comment by pbrane** [comment]
I built this branch 3 times and tried 3 different browsers.  Even though I can see the code changes in the branch the UI is still has the old layout.

**Comment by christianpape** [comment]
I had similar issues with 17.0.0-SNAPSHOT but "./clean.pl" and "rm -rf ~/.m2/repository/org/opennms" solved these issues for me.

**Comment by christianpape** [comment]
alarms-old

**Comment by christianpape** [comment]
alarms-new

**Comment by RangerRick** [comment]
This PR got develop merged into it so I can't merge it to the release-16.0.0 branch. Mind rebasing it?

**Comment by RangerRick** [comment]
Or I guess cherry-picking the changes or making a new PR I guess, since this already got merged to develop also.

**Comment by christianpape** [comment]
Please see this PR against release-16.0.0:

https://github.com/OpenNMS/opennms/pull/264

**Pull request merged**
