### PR TITLE
NMS-13575: Removed wrong line in debian/rules

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-13717

### CODE REVIEW

**Review by cgorantla — APPROVED** [review]

**Comment by j-white** [comment]
`release-28.x` -> `release-29.x`?

**Comment by RangerRick** [comment]
Does this need to be fixed in the RPM spec too? Or is just the Debian side affected?

**Comment by christianpape** [comment]
> `release-28.x` -> `release-29.x`?

The original issue is part of 28.x. Will fixes in 28.x not merged upwards?

**Comment by christianpape** [comment]
> Does this need to be fixed in the RPM spec too? Or is just the Debian side affected?

You fixed that part for me in the original issue:
https://github.com/OpenNMS/opennms/pull/3678/commits/2deb84f6888af8388db6a6bd034f2f3f86c85f85

**Review by fooker — APPROVED** [review]

**Comment by RangerRick** [comment]
> > `release-28.x` -> `release-29.x`?
> 
> The original issue is part of 28.x. Will fixes in 28.x not merged upwards to 29.x?

It should merge forward still, so it's fine either way.  28 is a dead end though, seems pretty likely we'll be doing 29 this month.

**Pull request merged**
