### PR TITLE
NMS-10450: allow postgresql 11

### PR DESCRIPTION
**Pull request by RangerRick**
This PR just bumps the accepted postgresql version to < 12, now that 11 is out.

* JIRA: http://issues.opennms.org/browse/NMS-10450

Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your changes.

### CODE REVIEW

**Comment by RangerRick** [comment]
I had run it on some of the 11 betas a while back, but hadn't tried final yet.

**Comment by RangerRick** [comment]
oops, this was supposed to be foundation-2018, not 23.0.1.  I'm cool with letting it sit until after the release.  There's a workaround for installing with 11.

**Comment by syepes** [comment]
+1 For this one
@RangerRick Whats the workaround?

**Comment by RangerRick** [comment]
add `-Q` on the command-line when running `install -dis`

**Pull request merged**
