### PR TITLE
WIP PE-17: Upgrade Liquibase from 3.6.3 to 4.4.3

### PR DESCRIPTION
**Pull request by patrick-schweizer**
This PR upgrades the liquibase dependency from 3.6.3 to 4.4.3

* https://issues.opennms.org/browse/PE-17

### CODE REVIEW

**Comment by patrick-schweizer** [comment]
The new version of liquibase doesn't publish a jar with the test classes on the maven repository anymore.
in 3.6.3 we had: https://repo1.maven.org/maven2/org/liquibase/liquibase-core/3.6.3/liquibase-core-3.6.3-tests.jar
in 4.4.3 https://repo1.maven.org/maven2/org/liquibase/liquibase-core/4.4.3/liquibase-core-4.4.3-tests.jar doesn't exist.
I solved this for now by copying the used test classes into our repo. Not sure if this is the right thing to do?

**Comment by RangerRick** [comment]
> The new version of liquibase doesn't publish a jar with the test classes on the maven repository anymore.
> in 3.6.3 we had: https://repo1.maven.org/maven2/org/liquibase/liquibase-core/3.6.3/liquibase-core-3.6.3-tests.jar
> in 4.4.3 https://repo1.maven.org/maven2/org/liquibase/liquibase-core/4.4.3/liquibase-core-4.4.3-tests.jar doesn't exist.
> I solved this for now by copying the used test classes into our repo. Not sure if this is the right thing to do?

Good question. How deep is our usage of them? Is it reasonable to just implement it ourselves instead?

**Comment by patrick-schweizer** [comment]
> > The new version of liquibase doesn't publish a jar with the test classes on the maven repository anymore.
> > in 3.6.3 we had: https://repo1.maven.org/maven2/org/liquibase/liquibase-core/3.6.3/liquibase-core-3.6.3-tests.jar
> > in 4.4.3 https://repo1.maven.org/maven2/org/liquibase/liquibase-core/4.4.3/liquibase-core-4.4.3-tests.jar doesn't exist.
> > I solved this for now by copying the used test classes into our repo. Not sure if this is the right thing to do?
> 
> Good question. How deep is our usage of them? Is it reasonable to just implement it ourselves instead?

I think this shouldn't be a problem. It's just a handful of classes. I will implement them myself...

**Comment by patrick-schweizer** [comment]
There seems to be a problem with the way Liquibase handles files. I ran into file handle problems locally. I assume it is connected to this reported bug:
https://github.com/liquibase/liquibase/issues/1815

=> I put the upgrade on hold for now until this is resolved on their end. There should be a fix coming up in the near future. The liquibase update to 4.4.3 is not blocking the CM work.

Further TODO: Liquibase 4.x doesn't seem to allow absolute file paths. We use them. This needs to be resolved as well.

**Pull request closed without merging**
