### PR TITLE
HZN-518: Make OTRS Integration properly handle namespace in soap responses

### PR DESCRIPTION
**Pull request by StCyr**
Fixed the OTRS Webservice wsdl description file to generate java code that properly handle namespace in the soap response.

JIRA: http://issues.opennms.org/browse/HZN-518
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS249

### CODE REVIEW

**Comment by StCyr** [comment]
with the original wsdl file, wsdl2java creates a GenericTicketConnectorInterface.java file that contains the following declarations:

    @WebMethod(operationName = "TicketCreate", action = "http://www.otrs.org/TicketConnector/TicketCreate")
    @WebResult(name = "TicketCreateResponse", targetNamespace = "", partName = "TicketCreateResponse")
    public OTRSTicketCreateResponse ticketCreate(
        @WebParam(partName = "TicketCreate", name = "TicketCreate", targetNamespace = "http://www.otrs.org/TicketConnector/")
        OTRSTicketCreate ticketCreate
    );

With the new wsdl file, these become:

    @WebMethod(operationName = "TicketCreate", action = "http://www.otrs.org/TicketConnector/TicketCreate")
    @WebResult(name = "TicketCreateResponse", targetNamespace = "http://www.otrs.org/TicketConnector/", partName = "TicketCreateResponse")
    public OTRSTicketCreateResponse ticketCreate(
        @WebParam(partName = "TicketCreate", name = "TicketCreate", targetNamespace = "http://www.otrs.org/TicketConnector/")
        OTRSTicketCreate ticketCreate
    );

Where the @WebResult annotation specify the expected targetNamespace.

I believe this should fix the issue.

**Comment by StCyr** [comment]
JIRA: http://issues.opennms.org/browse/HZN-518

**Comment by StCyr** [comment]
I have found a newer wsdl file in the otrs github repository:  https://github.com/OTRS/otrs/blob/master/development/webservices/GenericTicketConnectorSOAP.wsdl

I believe it should also fix the problem.

I'm busy now recompiling the stuff with this wsdl file.

**Comment by StCyr** [comment]
So, things go better with the newer wsdl file. But still they are not perfect: Now, it's the ArticleID response element that has a problem:

org.apache.cxf.interceptor.Fault: Unmarshalling Error: unexpected element (uri:"http://www.otrs.org/TicketConnector/", local:"ArticleID"). Expected elements are <{}TicketID>,<{}TicketNumber>,<{}Error>,<{}ArticleID>

**Comment by StCyr** [comment]
hi @indigo423 @soleger,

I've just tested that this new wsdl file works for ticket creation and ticket closing, from opennms  to otrs.

Would you consider including it in 17.0.0?

Cyrille

**Comment by soleger** [comment]
Absolutely! Support for the latest OTRS API is one of the biggest community contributions in 17.0.0. We really appreciate your help on fixing these WSDL incompatibilities. Thanks!

**Comment by fooker** [comment]
As this was not merged in v17.0.0 please open another pull request against branch ```release-17.0.1```.

**Pull request closed without merging**
