### PR TITLE
NMS-10458: Calculate availability based on complete downtime

### PR DESCRIPTION
**Pull request by brynjare**
* JIRA: https://issues.opennms.org/browse/NMS-10458

Properly calculate 24 hour availability (Service Level Monitoring) for nodes with multiple services.

### CODE REVIEW

**Comment by j-white** [comment]
Can we add unit test coverage for this?

**Comment by mvrueden** [comment]
Waiting for tests.

**Comment by brynjare** [comment]
> 
> 
> Waiting for tests. Let me know if you need assistance with that.

Sorry about the complete lack of response from my side!

I have been working on other aspects of our monitoring - or other projects entirely - for the past few months, so I never had a chance to even begin looking into test coverage.

If anyone else would be able to add tests for this, I would very much appreciate the help!

**Comment by mvrueden** [comment]
I am taking over and will write tests (at some point)

**Comment by mvrueden** [comment]
Pulled this in to OpenNMS and provided Test. See https://github.com/OpenNMS/opennms/tree/jira/NMS-10458

If bamboo goes green, this can be merged from my point of view.

**Comment by mvrueden** [comment]
I had to rebase against latest `foundation-2018`. Should go green now.

**Comment by RangerRick** [comment]
rebased again, this build had my broken smoke test changes

**Comment by mvrueden** [comment]
Bamboo went green. I manually merged `origin/jira/NMS-10458` to `foundation-2018`. Closing this. Thank you very much for your contribution :)

**Pull request closed without merging**
