### PR TITLE
NMS-13552: Added JVM option

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-13552

### CODE REVIEW

**Comment by cgorantla** [comment]
We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.

**Comment by RangerRick** [comment]
Also, is this useful as a general debugging thing? If so, should it go back to `foundation-2021` or even older?

**Review by RangerRick — CHANGES_REQUESTED** [review]
This should probably at least go back to foundation-2021 since it's about debugging production Minion issues.

**Comment by christianpape** [comment]
> We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.

This optimization mechanism only applies to the following type of exceptions:
* NullPointerException
* ArithmeticException
* ArrayIndexOutOfBoundsException
* ArrayStoreException
* ClassCastException

In my opinion are these exceptions I want to know of.

**Comment by cgorantla** [comment]
> > We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.
> 
> This optimization mechanism only applies to the following type of exceptions:
> 
> * NullPointerException
> * ArithmeticException
> * ArrayIndexOutOfBoundsException
> * ArrayStoreException
> * ClassCastException
> 
> In my opinion are these exceptions I want to know of.

yes, keep the optimization but use RATE_LIMITED_LOGGER where we are logging exceptions that are repetitive. 
It will still log the exception but it will emit 1 such log instead of 100.

**Comment by christianpape** [comment]
> > > We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.
> > 
> > 
> > This optimization mechanism only applies to the following type of exceptions:
> > 
> > * NullPointerException
> > * ArithmeticException
> > * ArrayIndexOutOfBoundsException
> > * ArrayStoreException
> > * ClassCastException
> > 
> > In my opinion are these exceptions I want to know of.
> 
> yes, keep the optimization but use RATE_LIMITED_LOGGER where we are logging exceptions that are repetitive.
> It will still log the exception but it will emit 1 such log instead of 100.



> > > We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.
> > 
> > 
> > This optimization mechanism only applies to the following type of exceptions:
> > 
> > * NullPointerException
> > * ArithmeticException
> > * ArrayIndexOutOfBoundsException
> > * ArrayStoreException
> > * ClassCastException
> > 
> > In my opinion are these exceptions I want to know of.
> 
> yes, keep the optimization but use RATE_LIMITED_LOGGER where we are logging exceptions that are repetitive.
> It will still log the exception but it will emit 1 such log instead of 100.

Since these are runtime exceptions and can appear everywhere in the code, we would then need to rate-limit each and every logging statement where an exception is logged. Before we do this, we could just close this PR and keep the behaviour as it is.

Another way is not to add this option by default and to just add documentation and write troubleshooting hints about this behaviour. So, an user is able to set this option if this hits us again.

In my opinion the exceptions this optimization handles are not domain-specific or something like that. These are nothing like timeouts, connection erros, parsing error or something like this, because for these we have out own exceptions implementations in place. These exceptions like NullPointer, ArrayIndexOutOfBounds, ClassCast, ArtihmeticException indicate erroneous code with logical errors. 

Furthermore, this optimization mechanism is in place since Java v1.5. It never hit us before. So I really don't care whether we include the option or not. I thought it was a good idea, but changing the logging code for everything that runs in the Minion doesn't make sense to me.

**Comment by cgorantla** [comment]
> > > > We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.
> > > 
> > > 
> > > This optimization mechanism only applies to the following type of exceptions:
> > > 
> > > * NullPointerException
> > > * ArithmeticException
> > > * ArrayIndexOutOfBoundsException
> > > * ArrayStoreException
> > > * ClassCastException
> > > 
> > > In my opinion are these exceptions I want to know of.
> > 
> > 
> > yes, keep the optimization but use RATE_LIMITED_LOGGER where we are logging exceptions that are repetitive.
> > It will still log the exception but it will emit 1 such log instead of 100.
> 
> > > > We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.
> > > 
> > > 
> > > This optimization mechanism only applies to the following type of exceptions:
> > > 
> > > * NullPointerException
> > > * ArithmeticException
> > > * ArrayIndexOutOfBoundsException
> > > * ArrayStoreException
> > > * ClassCastException
> > > 
> > > In my opinion are these exceptions I want to know of.
> > 
> > 
> > yes, keep the optimization but use RATE_LIMITED_LOGGER where we are logging exceptions that are repetitive.
> > It will still log the exception but it will emit 1 such log instead of 100.
> 
> Since these are runtime exceptions and can appear everywhere in the code, we would then need to rate-limit each and every logging statement where an exception is logged. Before we do this, we could just close this PR and keep the behaviour as it is.
> 
> Another way is not to add this option by default and to just add documentation and write troubleshooting hints about this behaviour. So, an user is able to set this option if this hits us again.
> 
> In my opinion the exceptions this optimization handles are not domain-specific or something like that. These are nothing like timeouts, connection erros, parsing error or something like this, because for these we have out own exceptions implementations in place. These exceptions like NullPointer, ArrayIndexOutOfBounds, ClassCast, ArtihmeticException indicate erroneous code with logical errors.
> 
> Furthermore, this optimization mechanism is in place since Java v1.5. It never hit us before. So I really don't care whether we include the option or not. I thought it was a good idea, but changing the logging code for everything that runs in the Minion doesn't make sense to me.

I'm definitely not suggesting to change logging everywhere. Just for the case where this issue originated from. 
May be [here](https://github.com/OpenNMS/opennms/blob/develop/features/telemetry/listeners/src/main/java/org/opennms/netmgt/telemetry/listeners/UdpListener.java#L204)

**Comment by christianpape** [comment]
> > > > > We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.
> > > > 
> > > > 
> > > > This optimization mechanism only applies to the following type of exceptions:
> > > > 
> > > > * NullPointerException
> > > > * ArithmeticException
> > > > * ArrayIndexOutOfBoundsException
> > > > * ArrayStoreException
> > > > * ClassCastException
> > > > 
> > > > In my opinion are these exceptions I want to know of.
> > > 
> > > 
> > > yes, keep the optimization but use RATE_LIMITED_LOGGER where we are logging exceptions that are repetitive.
> > > It will still log the exception but it will emit 1 such log instead of 100.
> > 
> > 
> > > > > We may also want to use [RateLimitedLogger](https://github.com/OpenNMS/opennms/blob/071d95719eb91e5dc6bc3c085ec35a1f35196013/features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java#L89) to limit the rate at which same logs are repeated.
> > > > 
> > > > 
> > > > This optimization mechanism only applies to the following type of exceptions:
> > > > 
> > > > * NullPointerException
> > > > * ArithmeticException
> > > > * ArrayIndexOutOfBoundsException
> > > > * ArrayStoreException
> > > > * ClassCastException
> > > > 
> > > > In my opinion are these exceptions I want to know of.
> > > 
> > > 
> > > yes, keep the optimization but use RATE_LIMITED_LOGGER where we are logging exceptions that are repetitive.
> > > It will still log the exception but it will emit 1 such log instead of 100.
> > 
> > 
> > Since these are runtime exceptions and can appear everywhere in the code, we would then need to rate-limit each and every logging statement where an exception is logged. Before we do this, we could just close this PR and keep the behaviour as it is.
> > Another way is not to add this option by default and to just add documentation and write troubleshooting hints about this behaviour. So, an user is able to set this option if this hits us again.
> > In my opinion the exceptions this optimization handles are not domain-specific or something like that. These are nothing like timeouts, connection erros, parsing error or something like this, because for these we have out own exceptions implementations in place. These exceptions like NullPointer, ArrayIndexOutOfBounds, ClassCast, ArtihmeticException indicate erroneous code with logical errors.
> > Furthermore, this optimization mechanism is in place since Java v1.5. It never hit us before. So I really don't care whether we include the option or not. I thought it was a good idea, but changing the logging code for everything that runs in the Minion doesn't make sense to me.
> 
> I'm definitely not suggesting to change logging everywhere. Just for the case where this issue originated from.
> May be [here](https://github.com/OpenNMS/opennms/blob/develop/features/telemetry/listeners/src/main/java/org/opennms/netmgt/telemetry/listeners/UdpListener.java#L204)

Ah ok. Got it. Sorry, I misunderstood you.

**Review by cgorantla — APPROVED** [review]
LGTM!

**Pull request merged**
