### PR TITLE
Sys performance sink

### PR DESCRIPTION
**Pull request by cernerpradeep**
Hi Seth,

As discussed in the call. This PR is created for your reference to check the code changes to sink pattern with syslogs.

Thanks,
Pradeep

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome Pavan (pavanrp1@gmail.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Pavan (pavanrp1@gmail.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by indigo423** [comment]
Do we have a issue number for this PR in our JIRA to get it tracked in our release notes?

**Comment by cernerpradeep** [comment]
Hi Ronny,
@indigo423 
There is no issue/jira created for this. This is related to the code changes done by Jesse to increase the performance of syslogs. We added kafka support to this, we found major performance improvement. So Seth wanted to check the code changes we have done.

Thanks,
Pradeep

**Comment by indigo423** [comment]
Yes, I just asked, cause if this patch in your pull request is accepted and gets merged, there will be no reference in our release management system JIRA. If you associate a Pull Request to a JIRA issue makes it aware in our release management to track your changes along with the version numbers and it will be also reflected in the automatically generated release notes from JIRA. If you provide Pull Requests without JIRA issues associated to them, it will be hard to figure out later, if there is a) something we have to back port to MERIDIAN and/or b) fixing issues relating your code changes. Just want to make sure someone is aware of it, I know sometimes it could be intended to merge it without a JIRA issue.

**Comment by opennms-bamboo** [comment]
Welcome Pavan (pavanrp1@gmail.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Pavan (pavanrp1@gmail.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome Pavan (pavanrp1@gmail.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Pavan (pavanrp1@gmail.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome Pavan (pavanrp1@gmail.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Pavan (pavanrp1@gmail.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome Pavan (pavanrp1@gmail.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Pavan (pavanrp1@gmail.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by soleger** [comment]
This PR has been made obsolete by the continued refactoring of the sink code that is being committed to OpenNMS 19. Closing PR.

**Comment by opennms-bamboo** [comment]
Welcome Pavan (pavanrp1@gmail.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username Pavan (pavanrp1@gmail.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Pull request closed without merging**
