### PR TITLE
HttpRemotingContextTest -> HttpRemotingContextIT since it requires a temp DB

### PR DESCRIPTION
**Pull request by dschlenk**
Also added required bits to maven to turn on ITs when requested per @deejgregor.

### CODE REVIEW

**Comment by opennms-bamboo** [comment]
Welcome David Schlenk (dschlenk@converge-one.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username David Schlenk (dschlenk@converge-one.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by dschlenk** [comment]
Hi @opennms-bamboo, my email address changed from david.schlenk@spanlink.com to dschlenk@converge-one.com. Do I need a new OCA?

**Comment by mvrueden** [comment]
Hey David,

no, you do not need a new OCA.
There are two ways of getting the OCA check to pass:

1. add the new email address to your github account -> Settings -> Emails
2. I can add a mapping for dschleck@converge-one.com to dschlenk 

If you want it to pass quickly, perform 1, because 2 is not yet implemented. But I am working on it.

- Markus

**Comment by opennms-bamboo** [comment]
Welcome David Schlenk (dschlenk@converge-one.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username David Schlenk (dschlenk@converge-one.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by mvrueden** [comment]
Hey Ulf, please approve dschlenk@converge-one.com as dschlenk.

**Comment by mvrueden** [comment]
I have finished implementing the mapping function. You are good to go now :)

**Pull request merged**
