### PR TITLE
NMS-8181: Create data collection configuration from vCenter 6

### PR DESCRIPTION
**Pull request by mfuhrmann**
- JIRA: http://issues.opennms.org/browse/NMS-8181
- Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1095

### CODE REVIEW

**Comment by christianpape** [comment]
Nice work. Do we need new graph definitions or will the config work with the old ones?

**Comment by mfuhrmann** [comment]
You're right Christian. I've added the v6 graphs.

**Comment by christianpape** [comment]
Can be merged as soon as Bamboo goes green...

**Comment by soleger** [comment]
This is OK but almost all of the graph definitions could be combined so that similar metrics are on the same graph instead of having one graph per metric. This would reduce the number of graphs from 200+ down to dozens.

This branch is off of a very old copy of develop as well. It cannot run in Bamboo correctly until the latest develop code has been merged into the branch.

**Comment by mvrueden** [comment]
Hey Ulf, please check the OCA.

**Comment by j-white** [comment]
I've pushed this into `pr/jira/NMS-8181`, will merge once Bamboo goes green.

**Comment by opennms-bamboo** [comment]
Welcome @web-flow.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @web-flow.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @web-flow.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @web-flow.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by opennms-bamboo** [comment]
Welcome @web-flow.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username @web-flow.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by j-white** [comment]
It looks like `PropertiesGraphDaoIT` is failing on this one.

**Comment by christianpape** [comment]
Fixed the failing test but the new build is still queued in Bamboo...

**Pull request merged**
