### PR TITLE
NMS-10721: Fixed session handling for Netflow v9

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-10721

### CODE REVIEW

**Comment by j-white** [comment]
Can we re-target this `release-24.1.1`?

**Comment by christianpape** [comment]
It seems that these changes will not resolve the issue, but nevertheless these changes are necessary for the mentioned NF9 data to be parsed at all. We also found the cause of the problem. We're currently working on a fix...

**Comment by j-white** [comment]
This seems to solve the problem with the multiple we've been observing. Probably worth merging this as-is?

**Comment by fooker** [comment]
> This seems to solve the problem with the multiple we've been observing. Probably worth merging this as-is?

Makes sense

**Pull request merged**
