### PR TITLE
NMS-12324: fix upgrade of multi-package minion

### PR DESCRIPTION
**Pull request by RangerRick**
### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12324
* Bamboo (Continuous Integration): https://bamboo.opennms.org/

### CODE REVIEW

**Comment by RangerRick** [comment]
Alright, this should be good to go.  I ended up going with creating empty packages for the "old" packages which depend on `opennms-minion` so that if the new minion package gets removed, they go away too.

**Comment by j-white** [comment]
Tested on CentOS 7 with Minion 24.0.0 installed:
```
$ rpm -qa | grep minion                                        opennms-minion-container-24.0.0-1.noarch
opennms-minion-features-core-24.0.0-1.noarch
opennms-minion-24.0.0-1.noarch
opennms-minion-features-default-24.0.0-1.noarch
```

Get conflicts when trying to upgrade
```
$ sudo yum install opennms-minion
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.netflash.net
 * extras: mirror.netflash.net
 * updates: mirror.netflash.net
Resolving Dependencies
--> Running transaction check
---> Package opennms-minion.noarch 0:24.0.0-1 will be updated
---> Package opennms-minion.noarch 0:25.0.0-0.20191018.opennms332.jira.nms.12324.10 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================
 Package        Arch   Version    Repository                                   Size
====================================================================================
Updating:
 opennms-minion noarch 25.0.0-0.20191018.opennms332.jira.nms.12324.10
                                  opennms-repo-branches-jira-NMS-12324-common 253 M

Transaction Summary
====================================================================================
Upgrade  1 Package

Total download size: 253 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for opennms-repo-branches-jira-NMS-12324-common
opennms-minion-25.0.0-0.20191018.opennms332.jira.nms.12324.1 | 253 MB  00:00:50
Running transaction check
Running transaction test


Transaction check error:
  file /etc/init.d/minion from install of opennms-minion-25.0.0-0.20191018.opennms332.jira.nms.12324.10.noarch conflicts with file from package opennms-minion-container-24.0.0-1.noarch
  file /opt/minion/bin/_lib.sh from install of opennms-minion-25.0.0-0.20191018.opennms332.jira.nms.12324.10.noarch conflicts with file from package opennms-minion-container-24.0.0-1.noarch
...
```

**Comment by RangerRick** [comment]
Huh, alright. Maybe something's different between 24.0.0 and the 24.1.3 I tested.  Wonder if I need the `Obsoletes:` stuff after all.

**Comment by RangerRick** [comment]
Ohhhhh, you did a `yum install` of only the specific package while leaving the sub-packages alone, not just a `yum upgrade`.  Ergh.  Not even sure how to fix that without still depending on the dummy packages.

**Comment by RangerRick** [comment]
Aha!  Magic incantation involves `Conflicts:` against old versions of the other packages.  Yum seems to do the right thing:

```
[root@centos7-x64 opennms]# yum --enablerepo=opennms-repo-local install opennms-minion
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
 * base: ftp.usf.edu
 * extras: distro.ibiblio.org
 * updates: ftpmirror.your.org
base                                                                                                                                                                                     | 3.6 kB  00:00:00
extras                                                                                                                                                                                   | 2.9 kB  00:00:00
opennms-repo-local                                                                                                                                                                       | 2.9 kB  00:00:00
opennms-repo-stable-common                                                                                                                                                               | 1.2 kB  00:00:00
opennms-repo-stable-rhel7                                                                                                                                                                | 1.2 kB  00:00:00
updates                                                                                                                                                                                  | 2.9 kB  00:00:00
(1/7): opennms-repo-local/primary_db                                                                                                                                                     | 5.5 kB  00:00:00
(2/7): extras/7/x86_64/primary_db                                                                                                                                                        | 152 kB  00:00:00
(3/7): opennms-repo-stable-common/primary                                                                                                                                                |  22 kB  00:00:00
(4/7): base/7/x86_64/group_gz                                                                                                                                                            | 165 kB  00:00:00
(5/7): opennms-repo-stable-rhel7/primary                                                                                                                                                 |  11 kB  00:00:00
(6/7): updates/7/x86_64/primary_db                                                                                                                                                       | 2.8 MB  00:00:00
(7/7): base/7/x86_64/primary_db                                                                                                                                                          | 6.0 MB  00:00:00
opennms-repo-stable-common                                                                                                                                                                              180/180
opennms-repo-stable-rhel7                                                                                                                                                                                 45/45
Resolving Dependencies
--> Running transaction check
---> Package opennms-minion.noarch 0:24.0.0-1 will be updated
---> Package opennms-minion.noarch 0:25.0.0-0.20191022.1 will be an update
--> Processing Conflict: opennms-minion-25.0.0-0.20191022.1.noarch conflicts opennms-minion-features-default < 25.0.0-0.20191022.1
--> Restarting Dependency Resolution with new changes.
--> Running transaction check
---> Package opennms-minion-features-default.noarch 0:24.0.0-1 will be updated
---> Package opennms-minion-features-default.noarch 0:25.0.0-0.20191022.1 will be an update
--> Processing Conflict: opennms-minion-25.0.0-0.20191022.1.noarch conflicts opennms-minion-features-core < 25.0.0-0.20191022.1
--> Restarting Dependency Resolution with new changes.
--> Running transaction check
---> Package opennms-minion-features-core.noarch 0:24.0.0-1 will be updated
---> Package opennms-minion-features-core.noarch 0:25.0.0-0.20191022.1 will be an update
--> Processing Conflict: opennms-minion-25.0.0-0.20191022.1.noarch conflicts opennms-minion-container < 25.0.0-0.20191022.1
--> Restarting Dependency Resolution with new changes.
--> Running transaction check
---> Package opennms-minion-container.noarch 0:24.0.0-1 will be updated
---> Package opennms-minion-container.noarch 0:25.0.0-0.20191022.1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================================================
 Package                                                       Arch                                 Version                                              Repository                                        Size
================================================================================================================================================================================================================
Updating:
 opennms-minion                                                noarch                               25.0.0-0.20191022.1                                  opennms-repo-local                               235 M
 opennms-minion-container                                      noarch                               25.0.0-0.20191022.1                                  opennms-repo-local                               1.6 k
 opennms-minion-features-core                                  noarch                               25.0.0-0.20191022.1                                  opennms-repo-local                               1.6 k
 opennms-minion-features-default                               noarch                               25.0.0-0.20191022.1                                  opennms-repo-local                               1.6 k

Transaction Summary
================================================================================================================================================================================================================
Upgrade  4 Packages

Total download size: 235 M
Is this ok [y/d/N]:
```

New build/commit incoming.

**Comment by j-white** [comment]
Tested with latest RPMs and the upgrade worked cleanly 👍

**Pull request merged**
