### PR TITLE
NMS-8823: Outage ReST service forNode use case calculates dates incorrectly

### PR DESCRIPTION
**Pull request by agalue**
Outage ReST service forNode use case calculates dates incorrectly

* JIRA: http://issues.opennms.org/browse/NMS-8823
* Bamboo: Do not worry, we add a link to our continuous integration system here

### CODE REVIEW

**Comment by agalue** [comment]
It would be good to port this solution to foundation (for Meridian 2015). The reason why I didn't do it is because opennms-webapp-rest doesn't exist in foundation, besides other ReST changes.

**Comment by j-white** [comment]
Looks good. Shouldn't we target `foundation-2016` with this one instead of `develop`?

**Comment by agalue** [comment]
GitHub is not smart enough to figure out the base branch.

**Comment by j-white** [comment]
FYI, you can change the branch now without needing to re-create the PR: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by forestfhb** [comment]
Know nothing!

**Pull request closed without merging**
