### PR TITLE
NMS-10182: Migrate User-Guide to Admin-Guide

### PR DESCRIPTION
**Pull request by indigo423**
Migrated the content of the User-Guide into the Admin-Guide. Removed the Maven modules for User-Guide. The links in the WebUI are removed and the Smoke-Tests adjusted.

* JIRA: https://issues.opennms.org/browse/NMS-10182

### CODE REVIEW

**Comment by indigo423** [comment]
@RangerRick do we have to test something with the `opennms-docs` package in RPM and DEB?

**Comment by RangerRick** [comment]
@indigo423 I don't think they care how many subdirectories there are in the packages.

**Comment by indigo423** [comment]
I ran in an issue with installing opennms-doc package from YUM and this is empty. Debian worked fine. See more details in [NMS-10182](https://issues.opennms.org/browse/NMS-10182)

**Comment by indigo423** [comment]
Installed branch and local and remote docs are working.

**Pull request merged**
