### PR TITLE
NMS-8444: Search in logMessage and description in events/alarms

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/NMS-8444

### CODE REVIEW

**Comment by j-white** [comment]
Can we re-target this to `release-24.0.0`? I'd prefer we avoid modifying the foundation branches unless necessary.

**Comment by christianpape** [comment]
Re-targeted to release-24.0.0

**Comment by christianpape** [comment]
Yes, missed that. Should be fixed now.

**Comment by RangerRick** [comment]
LGTM

**Pull request merged**
