### PR TITLE
NMS-12969: Topology Map: Application

### PR DESCRIPTION
**Pull request by patrick-schweizer**
This PR addresses these two issues:

-  [NMS-12969: Topology Map: Application: Color of app wrong for acknowledged alarm](https://issues.opennms.org/browse/NMS-12969)
- [NMS-12968: Display the alarm status correctly in topology map for applications](https://issues.opennms.org/browse/NMS-12969)

Background: So far we looked only at the alarms of a node now we look at the perspective alarms of a service.

This is how the map looks after the logic change:
image

We see that app1 has one perspective alarm on the http service. Therefor the http service is marked orange.
The other services are still green.
The alarms are acknowledged, therefor we see no numbers
The color of the app is the same color as the most severe service.

app3 shows 2 services with unacknowledged alarms. Therefor the services have numbers. The app has the sum (2) of alarms of its services.
The severity of the app is the same as the most severe service.

app3 shows 1 service with unacknowledged alarm. It has no other services. Therefor the application gets the severity "major" since all it's services are down.

### CODE REVIEW

**Review by christianpape — APPROVED** [review]
Looks good to me.

**Comment by RangerRick** [comment]
@patrick-schweizer can I go ahead and merge this to get it into H27 tomorrow?

**Comment by RangerRick** [comment]
Considering this is a fix for the topology map stuff to go along with the new perspective monitoring changes, I'm going to go ahead and merge this so we have time to get everything through the pipeline.  Been seeing a lot of flapping lately and need to give it more time.

**Comment by RangerRick** [comment]
Oops, looks like this branch didn't have `-smoke` on the end, so the topology UI was never smoke tested.  the `GraphRestServiceIT` was [throwing 500s](https://app.circleci.com/pipelines/github/OpenNMS/opennms/8115/workflows/f6c94e2a-2728-4591-ad18-e6ad9ac1b7f5/jobs/43774).

**Pull request merged**
