### PR TITLE
NMS-8215: Reload chart configuration instead of Notifd configuration

### PR DESCRIPTION
**Pull request by indigo423**
Reload Chart configuration instead of Notification configuration.

* JIRA: http://issues.opennms.org/browse/NMS-8215
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS537

### CODE REVIEW

**Comment by indigo423** [comment]
@RangerRick The issue was tagged to 18, do you changed already the auto merge behavior? Is this the correct target branch then?

**Comment by RangerRick** [comment]
@indigo423 I don't understand the question.  There is no change to auto-merge because develop was and is already 18.  foundation-2016 auto-merges to develop and that's it.

If you're just asking if foundation-2016 is the correct place to merge bugfixes, then yes, definitely.  That gets them into 18 and meridian 2016.

**Comment by indigo423** [comment]
@RangerRick does it go also to 17.1.1? You mentioned something about 17.1.1 is not auto merged anymore?

**Comment by agalue** [comment]
> On Mar 10, 2016, at 5:25 PM, Ronny Trommer <notifications@github.com> wrote:
> 
> does it go also to 17.1.1?

17.1.1 has been released, so no it doesn't ;)

**Pull request merged**
